### ISSUE TITLE
Add resources for newsletter in UI & UX category

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#100]
Currently the table for [Newsletter](https://github.com/jfmartinz/ResourceHub/tree/main/UI-UX%20Design#interview) is empty. Your task is to find a newsletter resources.

- At least add 5 newsletter related to UI & UX design
- It  should be related to UI & UX design
- Follow the format when adding a resources
- You can search newsletter for UI & UX

Make sure you read the [contributing.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)  before doing changes

**Comment by Chandan-Kumar-Mahato** [comment]
I would be happy to solve this issues , and thankful to you for giving me this opportunity.

**Comment by jfmartinz** [comment]
> I would be happy to solve this issues , and thankful to you for giving me this opportunity.

Goodluck
