### ISSUE TITLE
💡 [FEATURE] - Add Operating System Interview Section

### ISSUE THREAD

**Issue by ImmidiSivani** [jfmartinz/ResourceHub#1008]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to add Interview Section in Operating System.

### Explain your solution

I will add OS interview preparation resources.

**Comment by jfmartinz** [comment]
Does OS have interview prep? Maybe you can another one except this

**Comment by ImmidiSivani** [comment]
In some technical interviews  for the position  like  system engineering  etc.. basic OS questions  will be asked  so I would like to add that.

**Comment by jfmartinz** [comment]
Okay. Sure

**Comment by jfmartinz** [comment]
Add it, follow the format for adding new table, thanks
