### ISSUE TITLE
🐞 [BUG] UI is not responsive for small screen sizes

### ISSUE THREAD

**Issue by Pranav0606** [jfmartinz/ResourceHub#1009]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The UI of home page is not responsive.

**Comment by jfmartinz** [comment]
Read this #998. Ill close this issue for now.

**Comment by Pranav0606** [comment]
Hey, can I create a PR under #998 issue?
