### ISSUE TITLE
🐞 [BUG] - padding/ margin between the navbar items

### ISSUE THREAD

**Issue by nikki-05** [jfmartinz/ResourceHub#1010]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

Hello, the space between the items on the navigation bar does not look appealing. Modifying this will help the users to have a clear visual of the site and be after alteration it will make the design consistent with different devices
![Screenshot 2024-06-09 210817](https://github.com/jfmartinz/ResourceHub/assets/109809432/dec9b331-cd2b-4e76-8e7d-ce8045ac94b9)
   @jfmartinz sir,  please assign this issue to me maybe

### Expected behavior

The margin spaces or the padding should have been done better 

### Steps to reproduce

1. I went to the repository 
2. then, I opened the site on my laptop.

**Comment by jfmartinz** [comment]
Read this #998. Ill close this issue for now.
