### ISSUE TITLE
➕ [RESOURCE] - <Add Competitive Programming Roadmap>

### ISSUE THREAD

**Issue by Chandana-756** [jfmartinz/ResourceHub#1013]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

I would like to add competitive programming roadmap

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
Maybe you can add it in the DSA category

**Comment by Chandana-756** [comment]
> Maybe you can add it in the DSA category

Ok

**Comment by Chandana-756** [comment]
> Maybe you can add it in the DSA category

Can I create a separate folder for Competitive Programming  inside the DSA folder

**Comment by jfmartinz** [comment]
Okay.
