### ISSUE TITLE
💡 [FEATURE] - Adding Cards for other redirecting students to the learning resources

### ISSUE THREAD

**Issue by Archiesachin** [jfmartinz/ResourceHub#1014]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

There is no way of accessing the learning resources for the students. 
Adding cards for that resources on the home page

![Screenshot (1079)](https://github.com/jfmartinz/ResourceHub/assets/103347688/4e8bb7ca-e4d6-4aa4-b374-a2f012452c08)

Please assign me this issue under GSSOC'24

**Comment by jfmartinz** [comment]
Currently the website is still in development (redesigning). Read this #998
