### ISSUE TITLE
I wanted to add a search bar in the webpage

### ISSUE THREAD

**Issue by Vedanshimishra** [jfmartinz/ResourceHub#1017]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I wanted to add a search bar as whenever a user comes up to the webpage it is required by him to search the topics he wants to know about rather than opening each and every topic and searching about it.
![image](https://github.com/jfmartinz/ResourceHub/assets/143635091/2f240008-ebad-4e56-a58a-77d961df697d)

### Explain your solution

So i wanted to create a search bar which will help user to search his wanted topic.

**Comment by jfmartinz** [comment]
Currently the website is still in development (redesigning). Read this #998
