### ISSUE TITLE
🐞 [BUG] - The Testimonials Cards are not placed correctly

### ISSUE THREAD

**Issue by Amitanand0123** [jfmartinz/ResourceHub#1018]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The cards of the Testimonial section are not properly aligned.
![image](https://github.com/jfmartinz/ResourceHub/assets/140126906/2688c3a9-cc64-480b-8ab2-80c245ed76de)

### Expected behavior

The cards should form a proper table like structure to look more visually appealing for the user.

**Comment by Amitanand0123** [comment]
@jfmartinz Please assign me this issue as I will work on this. I will solve this bug by making a card container then sub card container in it and providing flex property to it align it properly.

**Comment by jfmartinz** [comment]
Currently the website is still in development (redesigning). Read this #998
