### ISSUE TITLE
🐞 [BUG] - Benefits section are not curated properly.

### ISSUE THREAD

**Issue by Amitanand0123** [jfmartinz/ResourceHub#1021]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The Benefits section under the Testimonials section is not curated properly.

![image](https://github.com/jfmartinz/ResourceHub/assets/140126906/78e123e5-7303-425e-928d-75de06101ae9)

**Comment by Amitanand0123** [comment]
@jfmartinz Please assign me this issue under the Gssoc label as I will fix it by styling it properly.

**Comment by jfmartinz** [comment]
Currently the website is still in development (redesigning). Read this #998
