### ISSUE TITLE
Footer Enhancement

### ISSUE THREAD

**Issue by taniya542** [jfmartinz/ResourceHub#1029]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The footer is not very aligned, symmetrical, and looks uncreative.

### Explain your solution

The footer can be redesigned to make things look clearer, and each part can have its own section in the footer. moreover, social handle links can be added to the footer to enhance its enhancement.

### Additional Context

Please assign this issue to me under GSSOC 24

**Comment by jfmartinz** [comment]
We're currently redesigning the site.

Read #998
