### ISSUE TITLE
Fixing css in mobile view making website responsive

### ISSUE THREAD

**Issue by dhairyagothi** [jfmartinz/ResourceHub#1031]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![Screenshot_20240610_121522](https://github.com/jfmartinz/ResourceHub/assets/142989448/f032437d-d168-4f80-a096-18dc9553bd1a)
Fixing css can make website look good

**Comment by jfmartinz** [comment]
The Chrome Extension tutorial provides a comprehensive resource for learning how to build and deploy Chrome Extensions using JavaScript.
