### ISSUE TITLE
The search bar border is not showing

### ISSUE THREAD

**Issue by am-1145** [jfmartinz/ResourceHub#1032]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The search bar border is not showing due to which it is not looking good.
![image](https://github.com/jfmartinz/ResourceHub/assets/96623227/e1aaa26a-eb32-4920-ae1f-c0b74e3d86b5)

### Expected behavior

If it looks like this it will look good

![image](https://github.com/jfmartinz/ResourceHub/assets/96623227/005acbe8-6506-4d2c-9316-c9fd944e3e24)

**Comment by jfmartinz** [comment]
The Chrome Extension tutorial provides a comprehensive resource for learning how to build and deploy Chrome Extensions using JavaScript.
