### ISSUE TITLE
Enhance the About UI Design

### ISSUE THREAD

**Issue by narayani9120** [jfmartinz/ResourceHub#1035]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Attractive design can draw users in and encourage them to spend more time exploring the app or website .Good UI design considers diverse user needs, making the interface accessible to people
![image](https://github.com/jfmartinz/ResourceHub/assets/125353066/8851357c-e658-43a4-ae44-b4bbefe40435)

**Comment by jfmartinz** [comment]
The Chrome Extension tutorial provides a comprehensive resource for learning how to build and deploy Chrome Extensions using JavaScript.
