### ISSUE TITLE
Add resources on UI & UX Design Interview Preparation

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#104]
The Interview section of our UI & UX design category repository is currently in need of additional resources. Your task is to add a valuable resources that can be included in the [interview](https://github.com/jfmartinz/ResourceHub/tree/main/UI-UX%20Design#interview) section. 

- At least 3 resources
-  It should be related to UI & UX design

Read [contributing.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before making changes

**Comment by Blackmercii2** [comment]
Hi can you assign the issue to me?

**Comment by jfmartinz** [comment]
> Hi can you assign the issue to me?

You can make your changes and make a pr already. I will put labels on it in the pr. Thanks
