### ISSUE TITLE
Add a Rate us Option

### ISSUE THREAD

**Issue by sailaja-adapa** [jfmartinz/ResourceHub#1062]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

**Comment by sailaja-adapa** [comment]
will you assing me this issue @jfmartinz

**Comment by sailaja-adapa** [comment]
@jfmartinz will you assign me this issue

**Comment by anjali3467** [comment]
will you assign me this issue
