### ISSUE TITLE
Add Icons to navbar options

### ISSUE THREAD

**Issue by sailaja-adapa** [jfmartinz/ResourceHub#1063]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add icons to navbar options it will make our website to look attractive

Can you please assign me this issue under gssoc'24

**Comment by sailaja-adapa** [comment]
will you assign me this issue @jfmartinz

**Comment by jfmartinz** [comment]
We're currently redesigning the site.

Read #998

**Comment by sailaja-adapa** [comment]
Yeah okk @jfmartinz
