### ISSUE TITLE
➕ [RESOURCE] - <title>ADD RESPONSIVENESS to THE NAVBAR

### ISSUE THREAD

**Issue by PAPIYA-DUTTA** [jfmartinz/ResourceHub#1065]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

Want to add more responsiveness to the navbar

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
We're currently redesigning the site.

Read #998
