### ISSUE TITLE
💡 [FEATURE] - <title>add login and signup option

### ISSUE THREAD

**Issue by PAPIYA-DUTTA** [jfmartinz/ResourceHub#1066]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by amruthaduvvuri** [comment]
Hello GSSoC Team,

I would like to take on this issue and contribute to resolving it using HTML, CSS, and JavaScript. Please assign this issue to me.

Thank you!

**Comment by jfmartinz** [comment]
No need for this. Ill close it for now
