### ISSUE TITLE
➕ [RESOURCE] - search bar

### ISSUE THREAD

**Issue by dhairyaj2004** [jfmartinz/ResourceHub#1078]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

Search Bar

### Any alternative approaches/features

I can add new search bar with the help of some css templates

### Additional Context

I want to add a proper and visible search bar in home page because it is not visible or highlighted properly and It should be because it is the main part of website

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by dhairyaj2004** [comment]
Heyy @jfmartinz I can make a better search bar. please assign me

**Comment by jfmartinz** [comment]
We're currently redesigning the website #998
