### ISSUE TITLE
💡 [FEATURE] - Add a contact us page

### ISSUE THREAD

**Issue by AbhishiktaRay03** [jfmartinz/ResourceHub#1081]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

A contact us page is always needed in a project so as to provide the users with information to contact the owners of a website in case they encounter a problem or wants to report a bug.

**Comment by jfmartinz** [comment]
We're currently redesigning the website #998
