### ISSUE TITLE
Add Hover Effect in About Page

### ISSUE THREAD

**Issue by katarianikita2003** [jfmartinz/ResourceHub#1084]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

![Screenshot 2024-06-12 005609](https://github.com/jfmartinz/ResourceHub/assets/158465309/7fb28459-822a-496f-b818-b25c3e8e2c61)

Add Hover effect on about page/category section

### Explain your solution

I'll add hover effects on these

**Comment by katarianikita2003** [comment]
I'd like to work on this issue, please assign it to me

**Comment by jfmartinz** [comment]
We're currently redesigning the website #998
