### ISSUE TITLE
Add an Interview section in web development 

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#109]
Adding a new section in [web development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#web-development). 

Your task is to create a new section which is `interview`

Make sure that your pr solved the following:

1. Add a new section interview in [web development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#web-development-) 

Use this format on creating a table
```html
<table width="100%">
  <tr>
    <th>Resource Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><a href="#">Resource Name</a></td>
    <td>Description</td>
  </tr>
</table>
```  

2. Add at least 3 resources in the section. It should be related to web development. It could be articles, github repository, yt or websites. Up to you.
3.  Add it to the [table of contents](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#table-of-contents) below the [games](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#games) section

If you have any questions or clarification. Let me know. Thanks!

**Comment by jfmartinz** [comment]
@Chandan-Kumar-Mahato

**Comment by Chandan-Kumar-Mahato** [comment]
ok

**Comment by Chandan-Kumar-Mahato** [comment]
please assign this to me
.

**Comment by jfmartinz** [comment]
assign to you
