### ISSUE TITLE
Add Web Development Book Resource

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#11]
The web development section of our project currently lacks any book resources, leaving it incomplete. Your task is to find a suitable web development book and add it to our resources table.

**Comment by jfmartinz** [comment]
Hey Do you want this issue? @r4huldeveloper

**Comment by jfmartinz** [comment]
if you need help, you can dm me here in [twitter](https://twitter.com/jfmartinz) @r4huldeveloper

**Comment by jfmartinz** [comment]
I can't assign you @r4huldeveloper, you need to reply here. thank you

**Comment by abhisar-yadav** [comment]
assign me this issue
@jfmartinz

**Comment by jfmartinz** [comment]
> assign me this issue @jfmartinz

assign to you
