### ISSUE TITLE
Add a `best practices` section in web development

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#110]
Adding a new section in [web development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#web-development). 

Your task is to create a new section which is `best practices` It could be best practices in JS, CSS or HTML etc. related to web dev.

Make sure that your pr solved the following:

1. Add a new section `best practices` in [web development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#web-development-) 

Use this format on creating a table
```html
<table width="100%">
  <tr>
    <th>Resource Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><a href="#">Resource Name</a></td>
    <td>Description</td>
  </tr>
</table>
```  

2. Add at least 3 resources in the section. It should be related to web development. It could be articles, github repository, yt or websites. 
3.  Add the new section in to the [table of contents](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#table-of-contents) below the [challenges](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#challenges) section

If you have any questions or clarification. Let me know. Thanks!

**Comment by 08Uzair** [comment]
Please assign this to me

**Comment by jfmartinz** [comment]
Assign to you :)

**Comment by jfmartinz** [comment]
Are you working on it? You should finish it before oct
