### ISSUE TITLE
Responsive site

### ISSUE THREAD

**Issue by Vibha17** [jfmartinz/ResourceHub#1101]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to make site more responsive and improve ui

I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by jfmartinz** [comment]
We're currently redesigning the website #998
