### ISSUE TITLE
💡 [FEATURE] - Add Follow Us section in footer

### ISSUE THREAD

**Issue by harsh02mishra** [jfmartinz/ResourceHub#1102]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding a Follow Us section and placing social media links in the footer ensures they are accessible from every page, increasing the likelihood that visitors will notice and click on them.

**Comment by jfmartinz** [comment]
We're currently redesigning the website #998
