### ISSUE TITLE
➕ [RESOURCE] - Dart Programming Language

### ISSUE THREAD

**Issue by PradnyaGaitonde** [jfmartinz/ResourceHub#1106]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

I want to add a new youtube video resource for Dart programming language.

### Provide the URLs of the resources you are adding

https://www.youtube.com/watch?v=Ej_Pcr4uC2Q

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
This is already present in the project, ill close this issue for now
