### ISSUE TITLE
➕ [RESOURCE] - Express Js 

### ISSUE THREAD

**Issue by PradnyaGaitonde** [jfmartinz/ResourceHub#1107]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

Want to add youtube playlist for Express Js.

### Provide the URLs of the resources you are adding

https://www.youtube.com/playlist?list=PL0Zuz27SZ-6P4vnjQ_PJ5iRYsqJkQhtUu

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
This is also present in the proejct, please check thanks
