### ISSUE TITLE
💡 [FEATURE] -  Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [jfmartinz/ResourceHub#1118]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24 @jf

**Comment by jf** [comment]
> ### Idea Contribution
> 
>     * [x]  I have read all the feature request issues.
> 
>     * [x]  I'm interested in working on this issue
> 
>     * [x]  I'm part of GSSOC organization
> 
> 
> ### Explain feature request
> 
> Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any
> 
> Can you please assign me this issue under gssoc'24 @jf
> ### Explain your solution
> 
> _No response_
> ### Any alternative approaches/features
> 
> _No response_
> ### Additional Context
> 
> _No response_

@sailaja-adapa I would suggest you pay attention to how you @ mention people. Getting such an important detail like that wrong does not look good.

@jfmartinz thoughts? you have not said anything at all through all of this.

**Comment by sailaja-adapa** [comment]
@jf i am really so sorry about this it won't happen again I'm new to Contributions i promise it won't happen again

**Comment by jfmartinz** [comment]
Use my complete username, 'jfmartinz'. 

About the propose feature, we're still redesigning the website. Maybe you could add this once the wbesite is ready and we'll discuss it further. Ill cose rhis issue for now

**Comment by sailaja-adapa** [comment]
yeah ok @jfmartinz
