### ISSUE TITLE
💡 [FEATURE] - Changing Navbar Style

### ISSUE THREAD

**Issue by HJ2207** [jfmartinz/ResourceHub#1126]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to change Navbar style as its not visible while on scrolling when background gets white.
![image](https://github.com/jfmartinz/ResourceHub/assets/146331595/fe3fe7c4-b150-4f75-9098-f76b207013ed)
 

### Explain your solution

I would like to decrease the transparency of the navbar background to make it more visible and also add more space between the start of About content and the Navbar.
![image](https://github.com/jfmartinz/ResourceHub/assets/146331595/1e05a0d1-90f7-488a-910a-48d57e13e799)

### Any alternative approaches/features

Alternative approach could be to modify About Style instead to suit the dark mode by changing the background to dark color and changing font color to lighter colors.

**Comment by jfmartinz** [comment]
We;re currently redesigning the site #998
