### ISSUE TITLE
💡 [FEATURE] - navbar enhancement

### ISSUE THREAD

**Issue by siddhant-2002** [jfmartinz/ResourceHub#1132]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

navbar logo is on extreme left and no hover effects added on the buttons I wanna work on that features

### Explain your solution

i will place logo on good position and add hover effects on the nav buttons

### Any alternative approaches/features

![image](https://github.com/jfmartinz/ResourceHub/assets/112260375/a3ccd383-a4f5-4ea3-979e-eaf6f3e3abed)

**Comment by jfmartinz** [comment]
we're currently redesigning the website. Ill close this for now, thanks

**Comment by siddhant-2002** [comment]
should i help you to redesign it
