### ISSUE TITLE
💡 [FEATURE] - categories styling

### ISSUE THREAD

**Issue by siddhant-2002** [jfmartinz/ResourceHub#1133]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

categories are just written there i want to give them good CSS  or else I can change whole CSS of the page 

### Explain your solution

i can make more stylish and responsive divs adding more CSS and enhancing page view 

### Any alternative approaches/features

![image](https://github.com/jfmartinz/ResourceHub/assets/112260375/56db7e9f-ee04-482b-8bda-bf7a1ad7713e)

### Additional Context

![image](https://github.com/jfmartinz/ResourceHub/assets/112260375/913977d5-b230-4be5-b33e-a2ee314c96b3)

**Comment by jfmartinz** [comment]
Currently redesigning thw ebsite
