### ISSUE TITLE
UI/UX Readme list of improvements

### ISSUE THREAD

**Issue by AntoTracchia** [jfmartinz/ResourceHub#115]
### Idea Contribution

- [x] I have read all the feature request issues.

### Explain feature request

I identified some areas of improvement within the UI/UX Category, as listed below by section:

*  **Tutorials and courses:** 
    - Could be beneficial to add a column to indicate if it's a paid or free resource. For some resources it's clarified in the title, but for consistency with the tables below it would be better to add that info into a column.

* **Tools:**
    - Several links are broken or the resource exists under a new URL. Need to update/remove them.
    - Tools of the same provider could be grouped together to facilitate access (e.g. Adobe tools)
  
* **Design inspiration:**
    - Broken links need to be updated/removed

* **Books:**
    - Different editions or revisits of the same books should be grouped together for easy identification

* **Communities:**
    - Adding a column to indicate in which platform you can find the community (Reddit, LinkedIn, Facebook, etc) can boost clarity.
    - After checking each URL some communities are really inactive, to keep the resource updated it would be good removing them from the list.
        - https://www.linkedin.com/groups/4496205/ - 0 publications a day
        - https://www.linkedin.com/groups/1854192/ - 0 publications a week
        - Last two links of the list in the document are described as different resources but lead to the same Linkedin group. 

* **Interview:**
    - Changing the title to something more descriptive would be good for clarifying what the section is about. I suggest something like "UX/UI Job interview resources" because that implies that we are talking about Job interviews vs any other kind of interviews and also that there are several types of resurces that you can find in that section, like videos, podcasts, articles, etc.

* **Newsletter:**
    - Broken links need to be updated/removed

**Comment by jfmartinz** [comment]
Awesome! I admire your attention to detail, although I think this is very simple things. 

I think you can create 1 pr and then separate each commit

I assign it to you! :)

**Comment by AntoTracchia** [comment]
Thank you! Even though they are simple you'd be surprised how common it is to find this kind of issues while maintaining documentation, so it's still excellent practice. Expect a PR soon, cheers!

**Comment by jfmartinz** [comment]
> Thank you! Even though they are simple you'd be surprised how common it is to find this kind of issues while maintaining documentation, so it's still excellent practice. Expect a PR soon, cheers!

Yes, thank you!

**Comment by cpratik1307** [comment]
I will carry out the work that you assign me for GSSoC.

**Comment by jfmartinz** [comment]
Anyone can take this issue, you seperate commits in order for me to easily understand the changes made.

**Comment by jfmartinz** [comment]
Please seperate your commits, so I can understand each what it does, thank you

**Comment by Divya-1612-reddy** [comment]
What do u mean by separate commit do u expect each section separately

**Comment by jfmartinz** [comment]
Commit every changes you made especially if different issue. for example, tutorials and courses and tools issue should be seperated making it easy to understand, get it?

**Comment by Divya-1612-reddy** [comment]
Yes
