### ISSUE TITLE
🐞 [BUG] : Dark mode gets turned off on refreshing a page 

### ISSUE THREAD

**Issue by Tejashri-Taral** [jfmartinz/ResourceHub#1156]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The dark mode preference does not persist across page refreshes. Each time the page is refreshed, the mode resets to the default instead of maintaining the user-selected mode (dark or light).
I think it is due to the theme state is not being persisted when the page is refreshed.

### Expected behavior

The selected dark or light mode should persist across page refreshes.
If a user selects dark mode, the page should remain in light mode even after refreshing.

### Steps to reproduce

**Steps to reproduce the behavior:**

Go to the website.
Toggle the light mode switch to change the theme.
Refresh the page.
Observe that the theme reverts to the default mode instead of retaining the selected mode.

**Comment by jfmartinz** [comment]
its about local storage, you can search about it

**Comment by jfmartinz** [comment]
Assigned to  you
