### ISSUE TITLE
💡 [FEATURE] - Add back o top button

### ISSUE THREAD

**Issue by Saimanjari777** [jfmartinz/ResourceHub#1158]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

 I would like to add the back to top button to all the pages so that it is easy for the users to navigate through the website.
Please assign this issue to me @jfmartinz

**Comment by jfmartinz** [comment]
Directory is 'new-website'.

**Comment by jfmartinz** [comment]
For the source code of the website
