### ISSUE TITLE
🐞 [BUG] - Buttons not getting clicked in home page

### ISSUE THREAD

**Issue by mehrun171** [jfmartinz/ResourceHub#1159]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In the home page , the Explore resources and how to contribute buttons are not getting clicked i.e their respective pages needs to be created and added in the href...So please assign me this task...
![Screenshot 2024-06-14 232205](https://github.com/jfmartinz/ResourceHub/assets/116735695/4819304e-97cb-4d2d-8d5e-5654247b6f23)
 

### Expected behavior

when we click on those page...the how to contribute page should open and resources page should open...the buttons should be redirected to these pages as we click.

**Comment by jfmartinz** [comment]
Explore resources should head to the categories below. 

![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/15266936-31b8-491b-8d18-8775bb69b1c6)

**Comment by jfmartinz** [comment]
In 'How to Contribute', you should provide the URL of the [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md), which you can find here in the root direcory
