### ISSUE TITLE
💡 [FEATURE] - Create an about us page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#1174]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I will create an about us page for the website as i see it is not created yet

**Comment by jfmartinz** [comment]
This is issue is assigned to someone else. Ill close it for now

**Comment by Ayushmaanagarwal1211** [comment]
@jfmartinz  Hii i see this issue is not resolved yet if you want i can work on it and same for faq page
