### ISSUE TITLE
💡 [FEATURE] - Creation of FAQ's Page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#1175]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by jfmartinz** [comment]
Are you Ayush Nandi?

**Comment by jfmartinz** [comment]
This issue is assigned to someone else

**Comment by Ayushmaanagarwal1211** [comment]
> Are you Ayush Nandi?

No i am Ayushmaan Agarwal  @jfmartinz  if it is not completed please let me know i will do that
