### ISSUE TITLE
💡 [FEATURE] - I want to add arrow button at last

### ISSUE THREAD

**Issue by Shreyaa173** [jfmartinz/ResourceHub#1179]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to add arrow button at last

### Explain your solution

I want to add arrow button at last which takes you to the homepage

**Comment by jfmartinz** [comment]
This issue is duplicate
