### ISSUE TITLE
🐞 [BUG] - github and discord icon is not visible

### ISSUE THREAD

**Issue by Shreyaa173** [jfmartinz/ResourceHub#1180]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

github and discord icon on hovering is not visible in dark theme

### Additional Context

![image](https://github.com/jfmartinz/ResourceHub/assets/144673309/24bef5c3-5d97-4568-b016-3cbb6711d51e)
![image](https://github.com/jfmartinz/ResourceHub/assets/144673309/55debca9-deaf-4c57-8b01-f83f9548fa77)

**Comment by jfmartinz** [comment]
Good attention detail. Assigned it to you
