### ISSUE TITLE
📃 [ENHANCEMENT] - The about us section can be better

### ISSUE THREAD

**Issue by Shreyaa173** [jfmartinz/ResourceHub#1181]
### Issue Verification

- [X] I have verified that this is a new documentation issue.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Documentation Area📚

about us section

### Issue Description✍️

It can be better

### Additional Context

![image](https://github.com/jfmartinz/ResourceHub/assets/144673309/5176aac4-0e9c-4e82-8c0c-55adfab70326)

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
That is not about section. Its a footer. Btw we're currently redesigning the website
