### ISSUE TITLE
💡 [FEATURE] - adding linkedin

### ISSUE THREAD

**Issue by dnyandeepchute** [jfmartinz/ResourceHub#1183]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by anshikatiwari20** [comment]
**Description:**
The feature request involves adding LinkedIn integration to the website.

**Screenshot:**
![Screenshot 2024-06-19 121457](https://github.com/jfmartinz/ResourceHub/assets/143124119/8e6c377b-dc36-4712-8adb-4f5ddc69f519)

I am a GSSoC contributor and would like to work on adding LinkedIn integration as described in issue #1183. Could you please assign this issue to me? Thank you!
