### ISSUE TITLE
💡 [FEATURE] - adding hover effect to links.

### ISSUE THREAD

**Issue by dnyandeepchute** [jfmartinz/ResourceHub#1184]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by jfmartinz** [comment]
Can you provide enough information for your issue? Which links? Can you give screenshots?

**Comment by dnyandeepchute** [comment]
![Screenshot 2024-06-15 132014](https://github.com/jfmartinz/ResourceHub/assets/158272735/7184abe1-347f-4004-b07e-221a74c1f493)

@jfmartinz
