### ISSUE TITLE
Add Web Development Communities Resource

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#12]
The web development section of our project currently lacks any community resources. Your task is to find a suitable web development communities and add them to our resources list. These communities can include Discord servers, YouTube channels, Twitter communities, or any other relevant platforms where web development enthusiasts gather to share knowledge and engage in discussions.

**Comment by krushnarout** [comment]
Hello, @jfmartinz I want to work on this issue.

**Comment by jfmartinz** [comment]
assign to you @krushnarout  ❤️
