### ISSUE TITLE
💡 [FEATURE] - <title> Adding FAQ page which is missing

### ISSUE THREAD

**Issue by SadafKausar2025** [jfmartinz/ResourceHub#1226]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by SadafKausar2025** [comment]
hello @jfmartinz 
can you please assign me this issue

**Comment by jfmartinz** [comment]
This issue is currently assigned to someone. ill close this for now
