### ISSUE TITLE
💡 [FEATURE] - Add feedback form for new website

### ISSUE THREAD

**Issue by sau-mili** [jfmartinz/ResourceHub#1246]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I wish to add the feedback form page 

### Explain your solution

![Screenshot 2024-06-16 174621](https://github.com/jfmartinz/ResourceHub/assets/146661411/7873c5ba-a468-450a-969f-8a68470d88db)

**Comment by jfmartinz** [comment]
Looks good @sau-mili
