### ISSUE TITLE
Introduction to Open source Development

### ISSUE THREAD

**Issue by Nayanika1402** [jfmartinz/ResourceHub#128]
### Idea Contribution

- [X] I have read all the feature request issues.

### Explain feature request

So basically as this repository coontains all the necessary resources all clubbed together in one place,I want to propose the idea of adding Open Source Development in this repository.

### Explain your solution

We know that open source development gives a boost to your coding journey ,so many coders can find this repository helpfull in case they want to gain knowledge regarding it.

**Comment by Nayanika1402** [comment]
@jfmartinz I would like to work on this part under GSSOC'24 if you like my proposal.

**Comment by jfmartinz** [comment]
> ### Idea Contribution
> * [x]  I have read all the feature request issues.
> 
> ### Explain feature request
> So basically as this repository coontains all the necessary resources all clubbed together in one place,I want to propose the idea of adding Open Source Development in this repository.
> 
> ### Explain your solution
> We know that open source development gives a boost to your coding journey ,so many coders can find this repository helpfull in case they want to gain knowledge regarding it.
> 
> ### Any alternative approaches/features
> _No response_
> 
> ### Additional Context
> _No response_

Thats a good idea! so just to clarify before I assign to you the issue, youre going to add another category which is open source?
something like this which existed in the project:
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/8f8bea24-a958-4296-b352-4ec48ea96d36)

**Comment by Nayanika1402** [comment]
Yes I want to add another section called Open Source Development.

**Comment by jfmartinz** [comment]
Okay, assigned it to you!

**Comment by Nayanika1402** [comment]
Thank you.
