### ISSUE TITLE
➕ [RESOURCE] - Adding Computer Networks Course

### ISSUE THREAD

**Issue by Sneha6290** [jfmartinz/ResourceHub#1296]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

Computer Networks -> Paid Courses Section

### Provide the URLs of the resources you are adding

https://www.coursera.org/specializations/computer-network-security

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
Closr this issue for now. Compile all the resources you want to add and then create PR

**Comment by Sneha6290** [comment]
okay @jfmartinz I'll do that
