### ISSUE TITLE
💡 [FEATURE] - Creating a 404 not found page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [jfmartinz/ResourceHub#1298]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

![image](https://github.com/jfmartinz/ResourceHub/assets/125277258/11c76762-1c9a-44c6-b8e9-9094803e5b94)

### Explain your solution

ii can design the page like this
![image](https://github.com/jfmartinz/ResourceHub/assets/125277258/3671e63f-10e5-4b89-b09b-603404fbdf8e)

**Comment by RamakrushnaBiswal** [comment]
hi @jfmartinz i want to work upon it

**Comment by jfmartinz** [comment]
You can edit the existing one if you want since this 404 exists already. 

https://github.com/jfmartinz/ResourceHub/blob/main/Error.html

Other codes is in the root like the css for this html

**Comment by RamakrushnaBiswal** [comment]
hi @jfmartinz review the PR
