### ISSUE TITLE
Add UI or UX Design Tools Resource

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#13]
Our UI/UX design section is missing essential tools. Your task is to find and add valuable UI or UX design tools to our resources list. These tools can include design software, wireframing tools, prototyping software, or any other applications that facilitate the UI/UX design process.

**Comment by prashantjagtap2909** [comment]
Added Figma.......

**Comment by MahakGautam2002** [comment]
Hey @jfmartinz , I can add UI/UX tools , so please assign this issue to me .

**Comment by MahakGautam2002** [comment]
@jfmartinz  ,Added Adobe XD and Proto.io
