### ISSUE TITLE
💡 Design Dedicated "How To Contribute" Webpage To The Website 

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [jfmartinz/ResourceHub#1308]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hey @jfmartinz 

The current "How to Contribute" link on the website redirects to the GitHub repository directly to the CONTRIBUTING.md file. 

![image](https://github.com/jfmartinz/ResourceHub/assets/163530398/02335b65-0062-476f-8e0b-96d77142ab8a)

To provide a better user experience, a dedicated web page explaining how to contribute to the project should be designed and integrated into the website

### Explain your solution

- **For Example Like This**

![image](https://github.com/jfmartinz/ResourceHub/assets/163530398/49b21758-f54c-48dd-9c82-bd1cf3247671)

This page will provide detailed instructions and guidelines on how users can contribute to the project, making it easier for new contributors to get started.

### Additional Context

Could you please assign this issue to me under GSSOC24 ?

**Comment by jfmartinz** [comment]
I will add the level once I see the code. Assigned it to you!
