### ISSUE TITLE
🐞 [BUG] - In dark mode the arrow in scroll to top button gets hidden

### ISSUE THREAD

**Issue by Braj-01** [jfmartinz/ResourceHub#1311]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The scroll to top button containing arrow inside it gets invisible in dark mode

**Comment by jfmartinz** [comment]
Duplicate issue
