### ISSUE TITLE
💡 [FEATURE] - <Implement Dark Mode Toggle Button>

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [jfmartinz/ResourceHub#1312]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request
 Users increasingly prefer the option to switch between dark mode and light mode for better readability and reduced eye strain, especially in low-light environments. Implementing a dark mode toggle button will enhance user experience by providing a customizable interface that caters to individual preferences.

### Explain your solution

UI/UX Design,CSS Modification

### Any alternative approaches/features

Scheduled Theme Switching

**Comment by jfmartinz** [comment]
We do have this feature already, ill cose this issue for now
