### ISSUE TITLE
🐞 [BUG] - Dark Mode Setting Resets Upon Page Refresh and "Go to Top" Button Visibility Issue in Dark Mode

### ISSUE THREAD

**Issue by RohithChitrada** [jfmartinz/ResourceHub#1316]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

Upon refreshing the page, the dark mode feature fails to persist and automatically reverts to the default light mode. This issue disrupts user preferences, causing an inconsistent experience where users expecting dark mode find themselves reverted to a lighter theme unexpectedly.

In dark mode, the "Go to Top" button is displaying as completely white, which causes it to blend into the background and obscures its directional indicator
![Screenshot 2024-06-18 222219](https://github.com/jfmartinz/ResourceHub/assets/120176158/1de46de1-2c3d-4971-94fa-f11c56469611)

### Expected behavior

Dark mode settings should persist across page refreshes, ensuring that the user's selected theme preference (dark or light mode) remains consistent throughout their browsing session.

The "Go to Top" button in dark mode should maintain a contrasting color scheme that ensures it stands out against the dark background. This includes using a color for the button and its directional indicator (arrow or icon)

### Steps to reproduce

1. Navigate to the Website
2. Enable Dark Mode
3. Scroll Down
4. Locate the Button
5. Observe Visibility
6.  Refresh the Page

**Comment by jfmartinz** [comment]
This is duplicate issue
