### ISSUE TITLE
💡 [FEATURE] - Add faq section

### ISSUE THREAD

**Issue by Saimanjari777** [jfmartinz/ResourceHub#1317]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to add the faq section which is missing
Please assign this issue to me @jf

**Comment by jfmartinz** [comment]
Please be mindful of mentioning

**Comment by jfmartinz** [comment]
Please use my real username @jfmartinz. This is issue is also assigned to someone esle
