### ISSUE TITLE
💡 [FEATURE] - <Add Computer Networks Interview questions>

### ISSUE THREAD

**Issue by AmruthaPariprolu** [jfmartinz/ResourceHub#1319]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by jfmartinz** [comment]
Compile every resources you want to add and then create new PR for it. Or you can work on other areas of the project, [link](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)

**Comment by jfmartinz** [comment]
Avoid creating issue again and aagain with the same issue, just create one PR for every resource you want to add
