### ISSUE TITLE
💡 [FEATURE] -  Enhancement: Add "Interest in Working on the Issue" Checkbox to Issue Template

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#132]
### Idea Contribution

- [X] I have read all the feature request issues.

### Explain feature request

We're constantly striving to improve our project's workflow and collaboration experience. One of the aspects we're looking to enhance is the clarity around contributors' interest in actively working on the issues they raise. Additionally, for those participating in programs like GSSOC (Global Summer of Code), we'd like to know if you're part of the organization.

### Explain your solution

To achieve this, we're proposing the addition of a new feature to our issue template: a checkbox indicating your interest in working on the raised issue and whether you're part of the GSSOC organization. This will help us prioritize and assign tasks more efficiently, ensuring that contributors who are willing to contribute get the opportunity to do so.

The proposed changes include:

Adding a checkbox labeled "I'm interested in working on this issue" to the issue template.
Adding a checkbox labeled "I'm part of GSSOC organization" to the issue template.
By including these checkboxes, contributors can explicitly communicate their intentions regarding the raised issue, facilitating smoother collaboration and task allocation.

**Comment by jfmartinz** [comment]
It seems like you opened a PR into your forked repository instead of in this project.

This link might be helpful for solving the problem:
It seems like you opened a PR into your forked repository instead of in this project, please check it 

If you need help, please dont hesitate to ask me, so we can fix this together,, thank you!

**Comment by Unknownmaster0** [comment]
Hii, PA I would like to make this to make a webpage, not only in the readme.md form. 
would you like to assign this task to me

**Comment by hars-21** [comment]
I would like to work on this issue. Please assign it to me

**Comment by MeetParmar2302** [comment]
i have done a pull request into main branch of your repo. sorry for the inconvenience that i merged it to my forked repo at first.
