### ISSUE TITLE
💡 [FEATURE] - Add Frontend Web Development Resource

### ISSUE THREAD

**Issue by rahul-p19** [jfmartinz/ResourceHub#133]
### Idea Contribution

- [X] I have read all the feature request issues.

### Explain feature request

I'd like to add the HTML and CSS tutorial and JavaScript tutorial by SuperSimpleDev to the resources table. They're very in-depth and I really like his teaching, and I believe people could benefit by watching his videos.
[HTML and CSS Course](https://www.youtube.com/watch?v=G3e-cpL7ofc)
[JavaScript Course](https://www.youtube.com/watch?v=EerdGm-ehJQ)

### Additional Context

To take this project even further, we could add tutorials and resources for Git and GitHub. We could also create a website to display these resources, as people could find a nice website easier to navigate than the documentation of the repository. Just a suggestion. If you like the idea, I'd be willing to create a basic HTML and CSS frontend, which people can improve on throughout the course of GSSOC 24. Sorry if this is not the correct place to be writing all of this.

**Comment by jfmartinz** [comment]
> ### Idea Contribution
> * [x]  I have read all the feature request issues.
> 
> ### Explain feature request
> I'd like to add the HTML and CSS tutorial and JavaScript tutorial by SuperSimpleDev to the resources table. They're very in-depth and I really like his teaching, and I believe people could benefit by watching his videos. [HTML and CSS Course](https://www.youtube.com/watch?v=G3e-cpL7ofc) [JavaScript Course](https://www.youtube.com/watch?v=EerdGm-ehJQ)
> 
> ### Explain your solution
> _No response_
> 
> ### Any alternative approaches/features
> _No response_
> 
> ### Additional Context
> To take this project even further, we could add tutorials and resources for Git and GitHub. We could also create a website to display these resources, as people could find a nice website easier to navigate than the documentation of the repository. Just a suggestion. If you like the idea, I'd be willing to create a basic HTML and CSS frontend, which people can improve on throughout the course of GSSOC 24. Sorry if this is not the correct place to be writing all of this.

Yes the project really need a website, if you can, please raise a seperate issue and I will assign it to you, I will give higher level for it (level 3). Thank you

**Comment by jfmartinz** [comment]
Assign it to you, @rahul-p19. Appreciate the suggestion!
