### ISSUE TITLE
FAQ  link is not working

### ISSUE THREAD

**Issue by Garima-149** [jfmartinz/ResourceHub#1330]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

@jfmartinz In the provided screenshot,when user clicks on faq link,then it is not working,no faq page or section is coming up.
I want to add a faq file if it is not in list or debug this link which is not working.I want to add this issue.Please assign me with this.

### Expected behavior

![Screenshot (70)](https://github.com/jfmartinz/ResourceHub/assets/143211271/666045e2-e006-410b-9ca0-2e72706f0c53)

**Comment by jfmartinz** [comment]
This is assigned to someone else, ill close this issue for now
