### ISSUE TITLE
Adding more social icons with already present

### ISSUE THREAD

**Issue by Garima-149** [jfmartinz/ResourceHub#1332]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

In provided screenshot,Currently page has only  github and discord icons.I want to add some more social icons to it. @jfmartinz Please assign me with this issue.

### Explain your solution

![Screenshot (70)](https://github.com/jfmartinz/ResourceHub/assets/143211271/59b3d5af-44fb-43e2-9ddb-0c1da4f65fcb)

**Comment by jfmartinz** [comment]
Unfortunately we're not adding more icons for now, ill close this issue for now
