### ISSUE TITLE
➕ [RESOURCE] - <add data science interview questions>

### ISSUE THREAD

**Issue by AmruthaPariprolu** [jfmartinz/ResourceHub#1336]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
I just said, adding one resource and creating PR for it might lead to spams, so what you can do is to create one PR that includes all the resources that you want. 

What's happening is, one pr includes one resources and do it again, and again. 

Compile and gather all resources you want to add and then create one PR for it. ill close this issue for now
