### ISSUE TITLE
🐞 [BUG] - Error 404 Page not found

### ISSUE THREAD

**Issue by r7projects-shayan** [jfmartinz/ResourceHub#134]
### Issue Verification

- [X] I have verified that this is a new bug report.

### Describe the bug

If the url is not valid we will be directed to 404 not found page. This will alert the users that they're on the wrong url.

### Expected behavior

A dedicated Error 404 page for when the users click on or search for any wrong url. This will maintain the originality of the website.

### Steps to reproduce

Create a separate Error 404 Page for the users to know that they're visiting a wrong link.

**Comment by r7projects-shayan** [comment]
Hey @jfmartinz I would like to work on this issue. Kindly assign it to me under Gssoc '24

**Comment by jfmartinz** [comment]
I just need to clarify, what you want to do is to create a unique 404 error page whenever the clicked resource is not valid? Is that right?

**Comment by r7projects-shayan** [comment]
Yes you're right @jfmartinz

**Comment by jfmartinz** [comment]
Okay, assigned it to you.

**Comment by r7projects-shayan** [comment]
Thanks a lot @jfmartinz

**Comment by Missdivyaa** [comment]
hey @jfmartinz I would like to contribute on this issue. kindly assign it to me.

**Comment by r7projects-shayan** [comment]
@Missdivyaa I'm already working on this issue. Please check another issue. I'm almost close to completion
