### ISSUE TITLE
➕ [RESOURCE] - Add a RoadMap in UI-UX design

### ISSUE THREAD

**Issue by ImmidiSivani** [jfmartinz/ResourceHub#1344]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

in roadmap section in UI/UX

### Provide the URLs of the resources you are adding

https://roadmap.uxuiopen.com/

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
Hi @ImmidiSivani since I see that you're actively contributing to the project, I advise to gather or compile all the resources that you watn to add in the project instead of creating one pr for one resource at a time. It will lead to spam PRs. Ill close this issue for now.
