### ISSUE TITLE
🐞 [BUG] - The links in the footer are not responsive 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#1345]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The links in the footer is not responsive yet on medium size it is overflowing and for small screen it is not showing 

### Additional Context

![Screenshot 2024-06-19 224511](https://github.com/jfmartinz/ResourceHub/assets/118350936/fc733ac6-bc54-4ddc-b2e5-c93aa99c85a5)
![Screenshot 2024-06-19 224457](https://github.com/jfmartinz/ResourceHub/assets/118350936/c3887022-5c91-422e-9e99-74a7b0eda213)

**Comment by jfmartinz** [comment]
This issue was assigned to someone else
