### ISSUE TITLE
➕ [RESOURCE] - add free book and paid books under DSA

### ISSUE THREAD

**Issue by chaanakyaaM** [jfmartinz/ResourceHub#1352]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

I  would like to add free books and paid books for learning DSA.

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
I just said, adding one resource and creating PR for it might lead to spams, so what you can do is to create one PR that includes all the resources that you want. 

What's happening is, one pr includes one resources and do it again, and again. 

Compile and gather all resources you want to add and then create one PR for it. ill close this issue for now

**Comment by chaanakyaaM** [comment]
Thank you for the clarity.
