### ISSUE TITLE
💡 [FEATURE] - Add 'C# Programming Language' Complete Resources

### ISSUE THREAD

**Issue by Vipullakum007** [jfmartinz/ResourceHub#1354]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

C# Programming Language is missing, which is widely used for developing desktop applications, web applications, and games.

### Explain your solution

I propose adding resources for learning C# from basics to advanced levels, which will include:

C# Basics:

- Data types (integers, floats, strings, etc.)
- Variables and operators
- Control structures (if-else, loops)
- Methods and properties
- Object-Oriented Programming (classes, inheritance, polymorphism, encapsulation)

Data Manipulation:

- Working with collections (arrays, lists, dictionaries)
- File I/O operations

Web Development:

- Introduction to ASP.NET Core
- Creating RESTful APIsMVC (Model-View-Controller) architecture

Desktop Applications:

- Windows Forms
- WPF (Windows Presentation Foundation)
- UWP (Universal Windows Platform)

Game Development:

- Introduction to Unity with C#
- Basic game mechanics
- Developing 2D and 3D games

**Comment by Vipullakum007** [comment]
hey @jfmartinz , please assign to me as GSSOC'24 contributor.

**Comment by jfmartinz** [comment]
This is already present on the project,  ill close this issue for now
