### ISSUE TITLE
➕ [RESOURCE] - Computer Architecture New resource

### ISSUE THREAD

**Issue by PradnyaGaitonde** [jfmartinz/ResourceHub#1356]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

I want to add a new resource for Computer Architecture.

### Provide the URLs of the resources you are adding

https://onlinecourses.nptel.ac.in/noc22_cs15/preview 

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
Hi @PradnyaGaitonde since GSSOC announced recently about the spam PRs. So instead of craeting PR for each resource, compile or gather all the resources you want to add and then create on PR for it. 

 ill close this issue for now
