### ISSUE TITLE
Feature 🌟: Add "Licensing Page" Reflecting "MIT Licence"

### ISSUE THREAD

**Issue by aslams2020** [jfmartinz/ResourceHub#1377]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hey @jfmartinz ,
Here is the feature request i want to implement - 

To provide clear information about the licensing of the website's content and code, we need to add a dedicated "Licensing Page" that reflects the use of the MIT License. 
This page will help users understand the terms under which they can use, modify, and distribute the website's resources.

Like this : 

![image](https://github.com/jfmartinz/ResourceHub/assets/131389695/4e757973-9ba7-4522-b553-905f313ae974)

### Explain your solution

**Steps to Implement**
1. Create Licensing Page :
- Develop a new page titled "Licensing" accessible from the main navigation menu or footer.
2. Content for Licensing Page:
- Include a brief introduction explaining the importance of licensing.
- Provide the full text of the MIT License.

Could you please assign me this issue.

**Comment by jfmartinz** [comment]
So in index.html, under License section, when the URL is clicked, the link should redirected into dedicated page which is what you're talking about here, am i right?

**Comment by aslams2020** [comment]
Yes @jfmartinz
