### ISSUE TITLE
🐞 [BUG] - <title>About link in navbar not redirecting anywhere

### ISSUE THREAD

**Issue by shraddhha** [jfmartinz/ResourceHub#1378]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

**Issue**: The "About" link in the navbar is not redirecting to the About section of the page. 

_This could be because:_

- Incorrect or missing href attribute in the "About" link.
- Missing   About section.
- JavaScript issues preventing the link from working properly.
- CSS interference that might be affecting the link's behavior.

**Expected Behavior:** The page should scroll down to the About section smoothly on clicking the link in the navbar.

**Actual Behavior:** Clicking the "About" link does not result in any scrolling or redirection to the About section. The page remains static, indicating that the link is not functioning as intended.

**This can be resolved**
The about section can be added   and the link should be properly mentioned in the href attribute .

### Expected behavior

**Expected Behavior:** The page should scroll down to the About section smoothly on clicking the link in the navbar.

### Steps to reproduce

The about section or the about page should be created first then the link of the html file or the about section should br provided in the href attribute.

**Comment by jfmartinz** [comment]
Actually, about page doesnt exist yet thats why. also someone is already working on it, close this issue for now, thanks

**Comment by shraddhha** [comment]
I will add the About page and then provide the link in the navbar.

**Comment by jfmartinz** [comment]
Sorry @shraddhha but this issue is assigned to someone else already. You can find any other issues in the website, theres a lot. Thanks
