### ISSUE TITLE
💡 [FEATURE] Creating a 404 page 

### ISSUE THREAD

**Issue by Jagpreet153** [jfmartinz/ResourceHub#1385]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding a 404 page will make the user to know when they are visiting a wrong route

### Explain your solution

I would be adding a 404 page which would be completely responsive and matching the theme of project.

### Any alternative approaches/features

The page will contain a animation and back to home button 

### Additional Context

![Screenshot 2024-06-21 222148](https://github.com/jfmartinz/ResourceHub/assets/119691733/b8edcded-6074-45b3-a0e9-4f5f5ba4a616)

Kindly assign this task to me under GSSoC'24

**Comment by jfmartinz** [comment]
We have 404 page already. you can look at that in the root folder, ill close this issue for now
