### ISSUE TITLE
Auto-Commenting Feature for PR Merged

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#140]
To enhance our communication and acknowledgment process, we're implementing an auto-commenting feature for specific events within our project repository. This feature will automatically generate comments under the following circumstances:

PR Merged: Upon the successful merging of a pull request (PR), an auto-comment will be added to the corresponding issue, indicating that the PR has been merged and expressing gratitude to the contributor for their valuable contribution.

This is the message that should pop up: "[Auto-Comment]: 🎉 Your pull request has been successfully merged! 🎉 Thank you for your valuable contribution to our project. Your efforts are greatly appreciated. Feel free to reach out if you have any more contributions or if there's anything else we can assist you with. Keep up the fantastic work! 🚀
"

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@jfmartinz I would like to work on this as part of GSSOC'24. Can you please assign the issue to me?

**Comment by Rajneeshkarya** [comment]
Hi @jfmartinz I would like to work on this issue. Could you please assign this issue to me under GSSOC'24?

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@jfmartinz please change the tag from Level 2 to level2 or it won't get counted towards the leaderboard. Thank you.

**Comment by jfmartinz** [comment]
> @jfmartinz please change the tag from Level 2 to level2 or it won't get counted towards the leaderboard. Thank you.

Thank you for reminding,
