### ISSUE TITLE
💡 [FEATURE] -  improve UI of footer 

### ISSUE THREAD

**Issue by heli0707** [jfmartinz/ResourceHub#1403]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

![image](https://github.com/jfmartinz/ResourceHub/assets/95361125/d337988e-262f-4100-b116-9659af9e7071)

Spacing and Alignment: Increase the spacing between the links on the right side to make them more distinct and easier to click. Could you align the text elements vertically for a cleaner look?
Icons: Enhance the visibility of the GitHub icons by slightly increasing their size or adding some padding around them. This will make them more noticeable and user-friendly.
Typography: Use a bolder font for the heading "ResourceHub" and ensure consistent font sizes for the body text and links. This will improve readability and visual hierarchy.
Incorporating these adjustments will create a more polished and user-friendly footer design.

**Comment by jfmartinz** [comment]
This issue is assigned to someone else. (duplicate issue). Ill close this issue for now, sorry.
