### ISSUE TITLE
💡 Add a Rate Us Option

### ISSUE THREAD

**Issue by sailaja-adapa** [jfmartinz/ResourceHub#1407]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24 @jfmartinz

**Comment by jfmartinz** [comment]
Isnt it 'Feedback' and 'Rate Us' the same thing, i mean we can just include it in the feedback form right? and also my concern about this issue is, is it really necessary to add this rate us? can you tell me more about it? And how youre going to do it?

**Comment by sailaja-adapa** [comment]
I would like to make the rate us like this @jfmartinz

![IMG_20240623_112415](https://github.com/jfmartinz/ResourceHub/assets/161804629/cad862c5-ae03-424c-89aa-adb39e97b382)

**Comment by sailaja-adapa** [comment]
I think there is no Feedback form in the website @jfmartinz Nowadays every website is having feedback form right  so i thought it would be better if we too had it

**Comment by jfmartinz** [comment]
This issue is duplicate @sailaja-adapa  #1331. Are you the one to propose this before?

**Comment by jfmartinz** [comment]
I cant really tell who is the first one who raised thios issue

**Comment by sailaja-adapa** [comment]
NO @jfmartinz

**Comment by sailaja-adapa** [comment]
No problem i will close this issue @jfmartinz

**Comment by sailaja-adapa** [comment]
> This issue is duplicate @sailaja-adapa #1331. Are you the one to propose this before?

no i didn't proposed it @jfmartinz

**Comment by jfmartinz** [comment]
Okay, thanks @sailaja-adapa
