### ISSUE TITLE
💡 [FEATURE] - <title>Adding a home button at each resource page at exploring resources

### ISSUE THREAD

**Issue by shraddhha** [jfmartinz/ResourceHub#1408]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

After exploring a resource if the user wish to see or explore other resources it comes difficult for him to navigate back to the homepage to see other resources as there is no such button provided that redirects to the home after seeing each page.

### Explain your solution

I would like to add a button on each resource page to navigate to the homepage after exploring a particular resource .
It will become user friendly and will also look professional.

### Additional Context

Please assign me this issue under gssoc . I assure that i will start working on it immediately.

**Comment by jfmartinz** [comment]
You can add 'back' button

**Comment by jfmartinz** [comment]
same thing that you can see in the feedback form

**Comment by shraddhha** [comment]
okk i will add the home button in the feedback form also
