### ISSUE TITLE
🐞 [BUG] Dark mode scroll to top button not looks perfect.

### ISSUE THREAD

**Issue by zalabhavy** [jfmartinz/ResourceHub#1421]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/126322584/6d8eefd2-47a8-4cf9-ad0e-308040037374)

I will fix this by make color of arrow black in dark mode.

**Comment by zalabhavy** [comment]
@jfmartinz Please assign me !

**Comment by jfmartinz** [comment]
This issue is duplicate. And the issue was resolved
