### ISSUE TITLE
💡 [FEATURE] - New Resource for Front End Development

### ISSUE THREAD

**Issue by BagchiShreya** [jfmartinz/ResourceHub#143]
### Idea Contribution

- [X] I have read all the feature request issues.

### Explain feature request

This resource helped me with my journey in web development. 

### Explain your solution

I think this resource would also help other students who want to beginning their own web development journeys.

**Comment by BagchiShreya** [comment]
Hi @jfmartinz 
I as a GSSoC'24 contributor would like to add this resource to this extremely important and helpful repository of yours. It would be if you assign this issue to me.

**Comment by jfmartinz** [comment]
> Hi @jfmartinz I as a GSSoC'24 contributor would like to add this resource to this extremely important and helpful repository of yours. It would be if you assign this issue to me.

Okay, but can you please provide the link of that resource and then you can start adding it to the project

**Comment by BagchiShreya** [comment]
> > Hi @jfmartinz I as a GSSoC'24 contributor would like to add this resource to this extremely important and helpful repository of yours. It would be if you assign this issue to me.
> 
> Okay, but can you please provide the link of that resource and then you can start adding it to the project

Sure
Link to the resource
https://www.youtube.com/playlist?list=PLEPye7A7EcQaCkSNNSTLdlfPm4f2fkQgG

**Comment by BagchiShreya** [comment]
> > Hi @jfmartinz I as a GSSoC'24 contributor would like to add this resource to this extremely important and helpful repository of yours. It would be if you assign this issue to me.
> 
> Okay, but can you please provide the link of that resource and then you can start adding it to the project

Sure
https://www.coursera.org/specializations/web-design?skipBrowseRedirect=true
This is a Coursera course link

**Comment by jainaman78** [comment]
@jfmartinz I'm eager to contribute to your project through GSSOC. Could you please assign me issue. there are some resources that i personally used 
(free: https://www.youtube.com/watch?v=ChVE-JbtYbM&t=36231s)
(paid: https://www.codingninjas.com/mern-full-stack-development-course)

**Comment by jfmartinz** [comment]
> @jfmartinz I'm eager to contribute to your project through GSSOC. Could you please assign me issue. there are some resources that i personally used (free: https://www.youtube.com/watch?v=ChVE-JbtYbM&t=36231s) (paid: https://www.codingninjas.com/mern-full-stack-development-course)

Okay, sure. You can create your PR right away. You can add these resources into [Tutorial or Courses](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#tutorials-or-courses) under [Full Stack Development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#full-stack-development). You can refer to this issue on how to add a [resource](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
