### ISSUE TITLE
Typos in UI/UX and Web development section.

### ISSUE THREAD

**Issue by Saloni-0465** [jfmartinz/ResourceHub#144]
These are few typos i found after reading the Categories section of the website.

1.   Under the "UX Collective Newsletter" description, it says:
       Original:    "UX Collective is the premier Medium publication for UX content with a high editorial standard We believe designers 
                        are thinkers as much as they are makers."
       Correction: "UX Collective is the premier Medium publication for UX content with a high editorial standard. We believe 
                             designers are thinkers as much as they are makers."
       Comment:   Added a period after "standard" for proper punctuation.

3.  Under the "Colors" section, there's a closing tag that's not properly formatted:
      FlatUIColors	This resource provides a collection of flat and trendy colors that work well for modern web design.</td> 
      
     
     
                                  
4. Under the "UI Components" section, there's a typo in the description of the "Semantic UI" resource:
      Semantic UI	Semantic UI is an open-source framework that uses CSS and jQuery to build great user interfaces. It is the 
                                  same as a bootstrap for use and has great different elements to use to make your website looks more amazing. 
                                  It uses a class to add CSS to the elements. 
                                  
  
  
                                  
5.  Under the "Forntend Interview Questions" section:
     Forntend Interview Questions	  This is the collection of interview question which will be helpful in your learning journey. 
     
     
     
6. Under the "Solid principles" section:
    Solid principles	At one place "medium article" is mention whereas it should be "Medium article".

@jfmartinz Please let me fix the issues.

**Comment by jfmartinz** [comment]
Good attention details @Saloni-0465, assigned it to you!

**Comment by Saloni-0465** [comment]
Hey! @jfmartinz 

I've addressed the issues mentioned and made the necessary changes in the pull request. Please take a look and let me know if there's anything else that needs attention. Thanks!
