### ISSUE TITLE
💡 [FEATURE] - Adding logo beside title

### ISSUE THREAD

**Issue by harinisayani** [jfmartinz/ResourceHub#1450]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to add logo beside title in navbar.
![Screenshot (17)](https://github.com/jfmartinz/ResourceHub/assets/143276011/27cf303f-ca02-4583-ac58-06a8e4915297)

### Additional Context

Please assign me this task.

**Comment by meenakshiiyer2531** [comment]
Hello @jfmartinz,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer

**Comment by jfmartinz** [comment]
Please add the icons for both themes:
- dark theme (white icon)
- light theme (dark icon)
