### ISSUE TITLE
💡 [FEATURE] - Adding feedback form

### ISSUE THREAD

**Issue by harinisayani** [jfmartinz/ResourceHub#1451]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I observed that there is no feedback form in webpage.
I want to add it.

### Additional Context

Please assign me this task.

**Comment by meenakshiiyer2531** [comment]
Hello @jfmartinz,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer

**Comment by jfmartinz** [comment]
We have a feedback form, ill  close this issue for now
