### ISSUE TITLE
💡 [FEATURE] - Adding contact us page

### ISSUE THREAD

**Issue by harikasayani** [jfmartinz/ResourceHub#1454]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I observed that there is no contact us page in webpage.
I want to add it in webpage

### Additional Context

I am GSSOC'24 contributor.
Please assign me this task.

**Comment by meenakshiiyer2531** [comment]
Hello @jfmartinz,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer

**Comment by jfmartinz** [comment]
Icons represents our contact. Ill close this issue for now
