### ISSUE TITLE
🐞 [BUG] -  About Us page not changing color in dark mode

### ISSUE THREAD

**Issue by RohithChitrada** [jfmartinz/ResourceHub#1460]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The bug involves the "About Us" page not changing color when the website is switched to dark mode, resulting in it displaying a white background while the rest of the site adheres to the dark mode settings. This discrepancy suggests that the dark mode styles are not being correctly applied to the "About Us" page.

![Screenshot 2024-06-24 214415](https://github.com/jfmartinz/ResourceHub/assets/120176158/0bbc570a-285a-4829-b813-ea6f0ca752d5)

### Expected behavior

The "About Us" page should update to dark mode, displaying a dark background with light text, consistent with the rest of the website.

### Steps to reproduce

1. Navigate to the website and ensure it is in light mode.
2. Switch the website to dark mode using the designated toggle or switch.
3. Observe that while most of the site updates to a dark background with light text, the "About Us" page remains with a white background and black text.

**Comment by meenakshiiyer2531** [comment]
Hello @jfmartinz,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer

**Comment by jfmartinz** [comment]
This issue was resolved.
