### ISSUE TITLE
💡 [FEATURE] Social Icons visibility in dark mode without hover

### ISSUE THREAD

**Issue by Picodes10** [jfmartinz/ResourceHub#1465]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The social links Discord and GitHub icons are not visible in the dark mode until hover. Anyone who hasn't paid much attention to the navbar and turned on dark mode will miss those two.

![Screenshot 2024-06-24 234537](https://github.com/jfmartinz/ResourceHub/assets/91375618/e9e01f33-0de3-46eb-8ad4-9caa40fcd146)

### Explain your solution

The icons will switch color according to the toggle even without hover.

**Comment by Picodes10** [comment]
Hello! @jfmartinz, I want to work on this issue under GSSOC 24.

**Comment by jfmartinz** [comment]
Hi, this issue was resolved. I will close this issue for now.
