### ISSUE TITLE
🐞 [BUG] - No change in color of about us section in dark mode.

### ISSUE THREAD

**Issue by meetarora10** [jfmartinz/ResourceHub#1467]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

No change in color of about us section in dark mode.
![Screenshot (511)](https://github.com/jfmartinz/ResourceHub/assets/143121854/3d565750-5c22-450e-bed8-a517469a5b3e)

### Expected behavior

The color of the entire website must be changed on clicking the toggle button.

### Steps to reproduce

Assign this task to me and I can fix this issue.

**Comment by jfmartinz** [comment]
This issue was resolved.
