### ISSUE TITLE
🐞 [BUG] - No effect on clicking of resources,organization,faq tabs on the navbar on the contributors page.

### ISSUE THREAD

**Issue by meetarora10** [jfmartinz/ResourceHub#1468]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

No effect on clicking of resources,organization,faq tabs on the navbar on the contributors page.
![Screenshot (512)](https://github.com/jfmartinz/ResourceHub/assets/143121854/31478dec-f60a-4d7f-8e5a-0f534cf8d6de)

### Expected behavior

On click of these tabs the page must go back to home page.

### Steps to reproduce

Assign this task to me and I can fix this issue.

**Comment by jfmartinz** [comment]
I dont get the issue, can you explain it more? what do you want to do, describe the problem, and more

**Comment by meetarora10** [comment]
Actually when I created this issue , contributors page was opening as a new page and in that page the tabs on the navbar were not working.
But now the contributors page is not a new page it is a section in the website so navbar is common and there is no problem now.

**Comment by jfmartinz** [comment]
Can you check it again, its working alraedy. We remove the contributors.html and just included it in the index.html.
