### ISSUE TITLE
💡 [FEATURE] - Making a Landing Page

### ISSUE THREAD

**Issue by Divyanshu832** [jfmartinz/ResourceHub#148]
### Idea Contribution

- [X] I have read all the feature request issues.

### Explain feature request

I think we should make a landing page that should be visually appealing but not too fancy and should redirect the user to any of three domains of Web dev, UI/UX or Web3.

### Explain your solution

 We can make nice looking tables for it and can simply attach our resources by grouping them. Then User can be redirected to that area of page in one click. And he can explore the resources there.

### Additional Context

It would make the landing page much better and even it can be more easy to spread and understand for newbies.

**Comment by jfmartinz** [comment]
Are you considering using a Static Site Generator (SSG)? We aim for a website that seamlessly reflects any new contributions made by our valued contributors. This means that when a contributor adds a new resource, the website should automatically update to reflect these changes. This dynamic functionality ensures that our website remains up-to-date and reflective of the ever-evolving nature of our project. By implementing such a feature, we enhance the user experience and provide real-time access to the latest resources available.

If yes, I can give you level 3 for this issue, let me know if you can and I will assign this issue to you right away. Or if you have any suggestions or plan then feel free to say it here, thank you!

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by GauriGA** [comment]
@jfmartinz Can you please assign this issue to me under the GSSOC'24 label?

**Comment by Mahimatestgithub** [comment]
I want to work on this task.Please assign me this issue.

**Comment by jfmartinz** [comment]
Issue is currently assigne to someone else

**Comment by GauriGA** [comment]
@jfmartinz Can you assign me an issue?
