### ISSUE TITLE
Enhancement : Improving UI of the website.

### ISSUE THREAD

**Issue by Changingthegame** [jfmartinz/ResourceHub#1484]
I  viewed your website but there I saw that mostly white or similar to white color are mostly used such as in the resources section there is only whitish color and the background page is also white and when we hover then also there is whitish appearance so there a nice looking and dashing color can be used . Also, in  the contributors and the license section, there is also not proper sentence writing so there should also be a change to make the website making good looking and making the user experience excellent.

![Screenshot 2024-06-26 161321](https://github.com/jfmartinz/ResourceHub/assets/169473705/0727d51d-aa9b-476f-991b-ae11e97149c3)
![Screenshot 2024-06-26 161414](https://github.com/jfmartinz/ResourceHub/assets/169473705/02b416a7-ea4c-4996-8f36-4206baa87656)

Here there is inappropriate   lines some are half on the webpage  some are of different length which is not looking good, so it should be changed.

**Comment by Nikhiljangra04** [comment]
I think it is time taking for me as I am not completely ready for it so I am unassigning myself from this issue. Thanks for  your response to me @jfmartinz .
