### ISSUE TITLE
💡 [FEATURE] -  Adding Proper Comments To all files

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#1496]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I will add a proper comments to all files

### Explain your solution

THis can be done by understanding the whole code line by line and then add comments to it .

**Comment by jfmartinz** [comment]
This is too simple. It might not be counted as level 1
