### ISSUE TITLE
➕ [RESOURCE] - Add a flexbox froggy

### ISSUE THREAD

**Issue by maradadivyasree020** [jfmartinz/ResourceHub#1506]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

Flexbox froggy is used to understand the properties of flexbox in an interactive manner.

### Provide the URLs of the resources you are adding

https://flexboxfroggy.com/

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
This resource  is present already in the project.
