### ISSUE TITLE
[Feature Request] : ✨ Add a Page Scroll Progress Bar at the Top of Your Startup Webpage 

### ISSUE THREAD

**Issue by TheNikhilRaj** [jfmartinz/ResourceHub#1513]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hey @jfmartinz ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no Page Scroll Progress Bar at the Top of Your Startup Webpage , which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Explain your solution

ScreenShot :
![progress_indicator](https://github.com/jfmartinz/ResourceHub/assets/129590267/7f17e9d3-41c5-4fb0-a558-caf334552764)

@jfmartinz 
Could you please assign me this issue under gssoc'24 ?

GSSOC'24

**Comment by jfmartinz** [comment]
This feature already implemented before but unfortunately, it suddenly stop working, maybe you can fix it.

**Comment by MastanSayyad** [comment]
> This feature already implemented before but unfortunately, it suddenly stop working, maybe you can fix it.

i think while resolving merge conflicts in index.html someone just removed the progress bar as it is working fine in resource contents, I request you to remind the contributors to not remove or undone the previous changes while resolving conflicts @jfmartinz

**Comment by TheNikhilRaj** [comment]
> This feature already implemented before but unfortunately, it suddenly stop working, maybe you can fix it.

okay i can fix it!
@jfmartinz please mention the levels in the lables.

**Comment by TheNikhilRaj** [comment]
@jfmartinz  my points hasn't updated yet for this issue on gssoc'24 leaderboard?
