### ISSUE TITLE
💡 [FEATURE] -Add hover effects on FAQ quations

### ISSUE THREAD

**Issue by zalabhavy** [jfmartinz/ResourceHub#1527]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I will add hover effects when some one hover on text of FAQ quation color of text change.

**Comment by zalabhavy** [comment]
@jfmartinz Please assign me this task !

**Comment by Akuu-27** [comment]
I would like to work on this task.
