### ISSUE TITLE
Typo in feature.yml section

### ISSUE THREAD

**Issue by Official-Lovely-kumari** [jfmartinz/ResourceHub#154]
###  **typos I found after reading the Feature.yml section:-**

-    Originally :- **_id: whats-your-idea_**
     Correction:- **_id: what's-your-idea_**

- Originally :- **_id: whats-your-solution_**
   Correction :- **_id: what's-your-solution_**

![Screenshot (1026)](https://github.com/jfmartinz/ResourceHub/assets/140309090/2c070598-5982-4641-a64b-1c1ea1497825)

@jfmartinz Please let me fix these issues.

**Comment by Official-Lovely-kumari** [comment]
Please assign it to me

**Comment by jfmartinz** [comment]
Assigned it to you! 👍

**Comment by Official-Lovely-kumari** [comment]
@jfmartinz Thank you for assigning the task to me!
