### ISSUE TITLE
💡 [FEATURE] - Add Social Media Icons to Website

### ISSUE THREAD

**Issue by TBorundia** [jfmartinz/ResourceHub#1543]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Currently, our website lacks a way for visitors to easily connect with us on social media platforms. This could limit our outreach and engagement with the community.

### Explain your solution

I propose adding social media icons for Instagram, Facebook, and Twitter to our website. These icons will link directly to our respective social media profiles, allowing visitors to connect with us more easily.

### Any alternative approaches/features

None

### Additional Context

Adding these icons will improve our community engagement and make it easier for visitors to follow our updates and activities on social media.

**Comment by Akuu-27** [comment]
I would like to work on this task.

**Comment by TBorundia** [comment]
@jfmartinz , please assign this issue to me under GSSoC'24.
Thank You!

**Comment by vermagithubcs** [comment]
@jfmartinz , please assign this issue to me under GSSoC 24 for adding the social media icons to the website and adding animation to the icons.

**Comment by sahkanishk01** [comment]
I would like to work on this task. Please assign this issue to me under GSSoC'24.

**Comment by Soujanya2004** [comment]
hi, I have been following your project and would love to contribute, please assign me
