### ISSUE TITLE
💡 [FEATURE] - Deploying project on vercel and providing live link in the repo

### ISSUE THREAD

**Issue by Debarunn1806** [jfmartinz/ResourceHub#159]
### Idea Contribution

- [X] I have read all the feature request issues.

### Explain feature request

I didn't find a live link in the repo so would like to add deployed vercel link to the project. As further changes are made in the github repo they will also be reflected in the live application .This would further increase the reach of the application .

**Comment by Kumar-Ankit56** [comment]
Hi @Debarunn1806 
Before assigning the issue to you can please let me know if we deployed the code to vercel will it reflects anything. As this repo has resources containing no UI part is involved.

**Comment by Debarunn1806** [comment]
No the live link would only display the elements with some ui element ,further when the other sections will be developed they will be added consequently.

**Comment by Debarunn1806** [comment]
If this will be fine do assign me this feature to implement,as a live link would greatly increase the accessibility of the app @Kumar-Ankit56 . Thanks

**Comment by Debarunn1806** [comment]
Yes that seems to be one way to achieve it , but here might be other efficient ways to I would like to work on this can you assign me under GSSOC24

**Comment by jfmartinz** [comment]
> Yes that seems to be one way to achieve it , but there might be other efficient ways too, I would like to work on this can you assign me under GSSOC24

Okay, assigned it to you. Let me know if you have any quesitions about the issue.

**Comment by jfmartinz** [comment]
Are you going to use Static Site Generator? @Debarunn1806

**Comment by Debarunn1806** [comment]
I might not be able to work on this right now , you may assign it to someone else at from my end it may take some time to execute

**Comment by Debarunn1806** [comment]
Sorry for the trouble

**Comment by jfmartinz** [comment]
No worries @Debarunn1806.
