### ISSUE TITLE
Add UI or UX Design YouTube Channels Resource

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#16]
Our UI/UX design resources currently lack youtubers. To cater to different learning preferences, your task is to find and add informative UI/UX design YouTube channels to our resources list. These channels should offer tutorials, design critiques, industry insights, or any other valuable content related to UI/UX design.

**Comment by jfmartinz** [comment]
Please make sure that you read the [Contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before raising a pr

**Comment by Sugamgoel28** [comment]
@jfmartinz I want to work on this issue, Can you please assign this to me sir/ma'am?

**Comment by jfmartinz** [comment]
You can start working on the issue bro and then I will add the labels in the PR

> @jfmartinz I want to work on this issue, Can you please assign this to me sir/ma'am?
