### ISSUE TITLE
💡 [FEATURE] - Add Web Development(Frontend Resources)

### ISSUE THREAD

**Issue by komal-agarwal5** [jfmartinz/ResourceHub#163]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to add a few resources for UI Components and 1 generator resource under the front-end web development tools section

### Any alternative approaches/features

NA

### Additional Context

Please assign me this issue under GSSoC'24.

**Comment by jfmartinz** [comment]
Assigned to you @komal-agarwal5!
