### ISSUE TITLE
Add GitHub Desktop Contribution Instructions

### ISSUE THREAD

**Issue by PradnyaGaitonde** [jfmartinz/ResourceHub#165]
I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others.

**Comment by jfmartinz** [comment]
> I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.
> 
> I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.
> 
> Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others.

Thats a good idea @PradnyaGaitonde, where do you plan to put the instruction exactly?

**Comment by PradnyaGaitonde** [comment]
I would like to add the instructions for contributing through GitHub Desktop in the README section, right below the instructions on submitting a pull request, so that contributors can explore that option as well according to their convenience. Could you please assign me this task under gssoc24?

**Comment by jfmartinz** [comment]
Sure @PradnyaGaitonde. :)
