### ISSUE TITLE
💡 [FEATURE] Your cool repo whants cool website .

### ISSUE THREAD

**Issue by pandeyji711** [jfmartinz/ResourceHub#166]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Generally, students may not have the time to search through multiple repositories.

### Explain your solution

 Therefore, I propose a new feature for a website named “ResoHub”. This website would consolidate all repositories, enabling students to directly visit their preferred repository.

 Please assign this new feature to me under GSoC 2024.”

**Comment by pandeyji711** [comment]
@jfmartinz please assign this to me  under Gssoc 2024

**Comment by jfmartinz** [comment]
Hey @pandeyji711 , here's the link to the [website](https://jfmartinz.github.io/ResourceHub/), but currently, it's quite messy. I'm planning to create a simpler version to enhance accessibility and navigation for potential users. The goal is to provide a seamless experience, allowing them to access resources without having to search through the repository. Instead, they can directly visit the website.

Moreover, I want the website to be dynamic, so any updates or additions to the project will automatically reflect on the website. For instance, adding a new resource should also update the website accordingly. I'm considering using a Static Site Generator for this purpose, but I'm unsure if it's the best approach. Do you have any thoughts on this?

**Comment by DharshiBalasubramaniyam** [comment]
@jfmartinz 
What if we created separate html files for each category/section.

So users can add resources directly to respective html files

**Comment by DharshiBalasubramaniyam** [comment]
> Hey @pandeyji711 , here's the link to the [website](https://jfmartinz.github.io/ResourceHub/), but currently, it's quite messy. I'm planning to create a simpler version to enhance accessibility and navigation for potential users. The goal is to provide a seamless experience, allowing them to access resources without having to search through the repository. Instead, they can directly visit the website.
> 
> Moreover, I want the website to be dynamic, so any updates or additions to the project will automatically reflect on the website. For instance, adding a new resource should also update the website accordingly. I'm considering using a Static Site Generator for this purpose, but I'm unsure if it's the best approach. Do you have any thoughts on this? I am giving level 3 for this issue.

What if we created separate html files for each category/section.

So users can add resources directly to respective html files

**Comment by pandeyji711** [comment]
@jfmartinz, I comprehend your concerns. I have a strategy in mind to accomplish this task using APIs. Could you please assign this to me for GSSOC 2024? I assure you that with some time, I will definitely complete this.

**Comment by pandeyji711** [comment]
@jfmartinz please assign me under Gssoc and mark it level 3

**Comment by jfmartinz** [comment]
@pandeyji711

**Comment by jfmartinz** [comment]
Assigned to you @pandeyji711, you can work on this issue.

**Comment by pandeyji711** [comment]
ok thanks

**Comment by pandeyji711** [comment]
@jfmartinz   I plan to implement an API that seamlessly retrieves data from GitHub and displays it on a website. The concept involves creating individual ‘cards’ for each resource. Students can interact with these cards to navigate directly to the corresponding GitHub repository. This system is designed to be dynamic, ensuring that any new resources added in the future will automatically be displayed on the website

**Comment by jfmartinz** [comment]
One question, are you going to utilize HTML CSS JS on this even youre using SSG?

**Comment by pandeyji711** [comment]
@jfmartinz  site requires dynamic content and interactivity, using HTML, CSS, and JavaScript directly can be a good approach.
This allows to build a more interactive user experience, where the client-side JavaScript dynamically fetches data and renders the page in the browser

**Comment by jfmartinz** [comment]
Okay, thanks

**Comment by pandeyji711** [comment]
I’m currently working on it, @jfmartinz. Please be aware that it may take some time to complete

**Comment by jfmartinz** [comment]
@pandeyji711 what tech stack are you using? only HTML CSS JS, no REACT or VUE?

**Comment by pandeyji711** [comment]
html,css,js, rest api

**Comment by jfmartinz** [comment]
> @jfmartinz html,css,js, rest api

Okay.

**Comment by pandeyji711** [comment]
Hello @jfmartinz, I wanted to inform you that the API is functioning correctly. Attached is a demo video for your referenc

https://github.com/jfmartinz/ResourceHub/assets/154527778/60400950-b83b-48e8-ac19-d23773d390a6

**Comment by jfmartinz** [comment]
Thanks. Looks good, just maake it work, and then futher enhancement to be made after it was merged.

**Comment by pandeyji711** [comment]
@jfmartinz, I would like to personally connect with you regarding a repository query for the backend.

**Comment by jfmartinz** [comment]
Where do you want? I have Linkedin, Discord, and Twitter

**Comment by jfmartinz** [comment]
Hey @pandeyji711, what if someone help you with the issue, someone who you cacn talk tto speed it up? I will give both level 3 so no worries.

**Comment by pandeyji711** [comment]
@jfmartinz I made connection request on linkedin ,if you accept please let me know

**Comment by hars-21** [comment]
Hey @pandeyji711 @jfmartinz I would like to collaborate on creating a website for this project. I can help in designing of site or on backend part if needed.

**Comment by pandeyji711** [comment]
@jfmartinz  The project has reached deployment stage. Could you please get in touch with me at your earliest convenience?
