### ISSUE TITLE
💡 [FEATURE] - <Resourses for backend development with spring boot>

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [jfmartinz/ResourceHub#167]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I have 3 medium blog articles related to spring boot

- [ ] Getting started with Microservices
- [ ] Securing Spring boot applications with JWT
- [ ] Building a RESTful User CRUD with Spring Boot: A Step-by-Step Guide

I would like to share them.

**Comment by jfmartinz** [comment]
You can add it under backend section in web development category. Thank you :)

**Comment by Divya-1612-reddy** [comment]
please assign me this issue
