### ISSUE TITLE
💡 [FEATURE] - Adding new resources related web development

### ISSUE THREAD

**Issue by Official-Lovely-kumari** [jfmartinz/ResourceHub#170]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

**I've seen a lot of resources and review it but one thing I wanna to add resources in Hindi Language . I also learn from them and it helped in my fronted journey.**

### Additional Context
**Please allow me to add resources. It'll help lot of learners.**
_No response_

**Comment by jfmartinz** [comment]
Sure @Official-Lovely-kumari, just specify that the resource is in Hindi Language so people will know.

**Comment by Official-Lovely-kumari** [comment]
Okay, I'll do.

**Comment by Divya-1612-reddy** [comment]
assign me this issue
