### ISSUE TITLE
💡 [FEATURE] - Resources for Databases

### ISSUE THREAD

**Issue by chaanakyaaM** [jfmartinz/ResourceHub#174]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Databases are also an important thing in web development so I want to add the resources for web development.

### Explain your solution

I would like to add the resources (tutorials) for Databases.

**Comment by Divya-1612-reddy** [comment]
please assign me this issue

**Comment by Braj-01** [comment]
Please assign me this issue.
