### ISSUE TITLE
💡 [FEATURE] - Addition of a section called Popular UI/UX Design Challenges to improve designing skills

### ISSUE THREAD

**Issue by syrnxalno** [jfmartinz/ResourceHub#179]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I think it is essential to consistently take up various design challenges that would help you identify your strengths and weaknesses and what's better than putting your creativity to the test.

### Explain your solution

I would like to suggest addition of a section under the UI/UX Design documentation, comprising of a collection of popular design challenges.

**Comment by jfmartinz** [comment]
Sure, @syrnxalno. I will assigned it to you.

**Comment by jfmartinz** [comment]
Can you please also provide at least 2-3 resources? Follow the [format](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md#important-rules). Use table

**Comment by syrnxalno** [comment]
Yes of course @jfmartinz, I was actually thinking of adding upto 5 of them.

Thank you for the consideration

**Comment by jfmartinz** [comment]
> Yes of course @jfmartinz, I was actually thinking of adding upto 5 of them.
> 
> Thank you for the consideration

Thanks :)
