### ISSUE TITLE
Add Youtube Resources

### ISSUE THREAD

**Issue by PradnyaGaitonde** [jfmartinz/ResourceHub#187]
I would like to contribute to your repository by recommending a YouTube channel for web development. This channel features high-quality tutorials and guides on various aspects of web development, including frontend and backend technologies, frameworks, and best practices.

I believe that adding a curated list of YouTube channels to your repository would benefit developers looking to enhance their skills in web development. These channels provide valuable insights and learning resources that can help developers stay updated with the latest trends and techniques in the field.

Please assign this issue under gssoc24

**Comment by Divyaraj33** [comment]
I would like to work on this project. Please assign it to me.

**Comment by varshithar12** [comment]
I would like to contribute to your repository by recommending a YouTube channel for web development. This channel features high-quality tutorials and guides on various aspects of web development, including frontend and backend technologies, frameworks, and best practices. 
Can you please asign me the issue ?
