### ISSUE TITLE
Adding Roadmap for UI/UX

### ISSUE THREAD

**Issue by Arpcoder** [jfmartinz/ResourceHub#188]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by Arpcoder** [comment]
@jfmartinz sir, please correct the syntax of label 'Level 1' to 'level1' as per the recent update from GSSoC. Thank you.

**Comment by jfmartinz** [comment]
> @jfmartinz sir, please correct the syntax of label 'Level 1' to 'level1' as per the recent update from GSSoC. Thank you.



> @jfmartinz sir, please correct the syntax of label 'Level 1' to 'level1' as per the recent update from GSSoC. Thank you.

I changed it. Thank you for reminding me :)

**Comment by Arpcoder** [comment]
> > @jfmartinz sir, please correct the syntax of label 'Level 1' to 'level1' as per the recent update from GSSoC. Thank you.
> 
> > @jfmartinz sir, please correct the syntax of label 'Level 1' to 'level1' as per the recent update from GSSoC. Thank you.
> 
> I changed it. Thank you for reminding me :)

Sir please change 'L' to 'l' in Level'...Thank you once again.

**Comment by jfmartinz** [comment]
oh, haha. Sry
