### ISSUE TITLE
💡 [FEATURE] - Adding Interactive Flexbox Learning Link

### ISSUE THREAD

**Issue by Astha86** [jfmartinz/ResourceHub#190]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I propose adding an interactive Flexbox learning resource to the Web Development section. This resource allows users to learn Flexbox while playing, offering an engaging and effective learning experience.

I believe integrating this resource will enhance the learning journey for users interested in mastering Flexbox.

### Explain your solution

Here's the link to the interactive Flexbox tutorial: 

https://labs.codehelp.in/fruitbox-flex

Screenshot:
![Screenshot 2024-05-14 082101](https://github.com/jfmartinz/ResourceHub/assets/142304973/75a1296e-3e6c-4dbd-91ef-a5100e91214c)

Hey @jfmartinz , I want to contribute in this project. Please label it under GSSOC and assign this to me.

**Comment by jfmartinz** [comment]
Assigned it to you @Astha86, goodluck

**Comment by nafreenanjum** [comment]
I wanted to work on this .I would appreciate it if you could consider assigning this issue to me.
