### ISSUE TITLE
Grammatical errors I found after going through the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Sneha6290** [jfmartinz/ResourceHub#194]
In the "How to Contribute" section under "Add Valuable Resources" :

Raise an Issue: Create an issue and provide details about the resource you'd like to add. I'll review it, and if it aligns with contributing guidelines. I'll add it it into the project.

- Originally :I'll add it it into the project
- Corrected: I'll add it to the project

In the closing statement :

Thank you for considering contributing to ResourceHub! Your contributions plays a crucial role in making this project a valuable resource for the web development community. 🌐✨

- Originally: Your contributions plays a crucial role
- Corrected: Your contributions play a crucial role

  @jfmartinz please let me fix the issues.

**Comment by jfmartinz** [comment]
Good attention detail @Sneha6290, I assiged it to you :)

**Comment by Sneha6290** [comment]
Thank you @jfmartinz
