### ISSUE TITLE
[FEATURE] - Need to add DevOps Roadmap & Resources

### ISSUE THREAD

**Issue by Astha86** [jfmartinz/ResourceHub#199]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I noticed that under the Web Development section there's currently no specific roadmap & resources for DevOps. 

I believe it's essential to include a dedicated roadmap & resources to guide developers in this domain as it is the part of the modern software development.

### Explain your solution

By Adding a separate DevOps resources could greatly enhance the utility of the ResourceHub project.

I'd like to take on the task of adding the DevOps Roadmap  & Resources.  I believe this addition will enhance the completeness and usefulness of the DevOps Roadmap for the community.

### Additional Context

Hey @jfmartinz , I want to work on this. Kindly assign this task to me.

**Comment by jfmartinz** [comment]
Great! Thanks for the idea @Astha86, I assigned it to you. Please follow the formatting of the table, thank you. You can find it in [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
