### ISSUE TITLE
Create Feature Request (Issue Template)

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#2]
We need to make it easier for people to suggest new features for our project. We want to set up a simple template that people can fill out when they have an idea. Your job is to create this form so that it's easy for everyone to use. This will help us keep track of feature requests and make our project better.

**Comment by kom-senapati** [comment]
I have an idea in my mind for this. I would like to work on this issue.

**Comment by jfmartinz** [comment]
Hello thank you for interest in  contributing to the project!  I assign this issue to you. Goodluck! :)

> I have an idea in my mind for this. I would like to work on this issue.
