### ISSUE TITLE
💡 [FEATURE] - Addition of "Decentralized Finance (DeFi) Projects" in Web3 Resource List

### ISSUE THREAD

**Issue by SkSadaf** [jfmartinz/ResourceHub#205]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to request the addition of a new section titled "Decentralized Finance (DeFi) Projects" in the existing Web3 Resource List. This section aims to provide users with information about notable decentralized finance platforms and protocols within the Web3 ecosystem.

### Explain your solution

The proposed "Decentralized Finance (DeFi) Projects" section will enhance the README by offering users insights into the diverse range of financial applications available in the Web3 space. These projects play a crucial role in reshaping traditional finance by leveraging blockchain technology and smart contracts to offer decentralized financial services such as lending, borrowing, trading, and yield farming. Including this section will benefit users who are interested in exploring the diverse range of financial applications available in the Web3 space. It will provide them with valuable insights into popular DeFi projects, enabling them to learn more about decentralized finance and participate in the growing DeFi ecosystem.

**Comment by jfmartinz** [comment]
Assigned to you @SkSadaf.

**Comment by SkSadaf** [comment]
Thank you for assigning me this issue. I've implemented the proposed feature and submitted pull request #214 . Please review it, and let me know if any further changes are needed.
