### ISSUE TITLE
Need for adding platforms for practice and showcasing skills.

### ISSUE THREAD

**Issue by Braj-01** [jfmartinz/ResourceHub#211]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Providing the platform for practice will give hand on experience to learners.

**Comment by Braj-01** [comment]
am excited to contribute to your repository by adding resources for practice. Could you please assign me this issue under GSSOC'24

**Comment by jfmartinz** [comment]
WHere are you going to add it? Web dev, UI UX, etc?

**Comment by aditig80** [comment]
@jfmartinz kindly assign this to me! I can add different resources for practice in Web dev section and DBMS section!

**Comment by Braj-01** [comment]
Web dev @jfmartinz

**Comment by jfmartinz** [comment]
You can add the resource in this [section](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#challenges)
