### ISSUE TITLE
[Feature] - Resources for Machine Learning

### ISSUE THREAD

**Issue by chaanakyaaM** [jfmartinz/ResourceHub#212]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Machine learning is a important category to learn in this AI era, so resources for machine learning will help everyone to learn machine learning for free.

### Explain your solution

I would like to add the resources of machine learning including the maths required, programming language, types of machine learning algorithms and more.

**Comment by MIpaltan007** [comment]
I have a soft copy of single page containing all the resources(can be accessed with a simple click) and Roadmap to Machine Learning. If assigned, i will contribute that one along with few useful courses for getting started with ML.
