### ISSUE TITLE
💡 [FEATURE] - Request to Add Top 25 Web3 Coding Challenges

### ISSUE THREAD

**Issue by SkSadaf** [jfmartinz/ResourceHub#216]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to request the addition of a list of the top 25 Web3 coding challenges to this GitHub repository. These challenges cover a wide range of topics in Web3 development, including smart contract development, decentralized finance (DeFi), blockchain integration, and more. By adding these challenges, we can provide valuable resources for developers looking to improve their skills in Web3 development and contribute to the growth of our community.

### Explain your solution

The solution involves adding a the list of the top 25 Web3 coding challenges. Each challenge will be accompanied by a brief description and a link to the respective resource or tutorial. This will make it easy for developers to access these challenges and engage with them to enhance their knowledge and skills in Web3 development. Additionally, it will contribute to the repository's value as a hub for Web3-related resources and educational content.

**Comment by jfmartinz** [comment]
Assigned to you @SkSadaf, thanks

**Comment by SkSadaf** [comment]
Thank you for assigning me this issue. I've completed the implementation of the proposed feature and submitted in pull request labeled #234. Please review and let me know if any changes are to be made.
