### ISSUE TITLE
 [FEATURE] - Table of Contents for README

### ISSUE THREAD

**Issue by SkSadaf** [jfmartinz/ResourceHub#218]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding a Table of Contents to the README file addresses the potential issue of users finding it challenging to navigate through different sections of the document, especially as it grows longer. Without a Table of Contents, users may have difficulty quickly locating specific information, leading to frustration and reduced usability of the document.

### Explain your solution

The solution involves adding a Table of Contents section to the README file, listing the main sections and subsections of the document with hyperlinks for easy navigation. This Table of Contents will provide users with a clear overview of the document's structure and enable them to jump directly to the desired section by clicking on the corresponding link. By implementing this solution, users will experience improved readability and usability of the README file, enhancing their overall experience with the project documentation.
<img width="704" alt="image" src="https://github.com/jfmartinz/ResourceHub/assets/113595262/d930eeab-7ed3-482e-9968-c675f27e087b">

**Comment by jfmartinz** [comment]
Assigned to you @SkSadaf, thanks for the idea
