### ISSUE TITLE
Create a short description for the Roadmap in Web Development Category

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#220]
Currently in the Web Development Category under [Roadmap](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#roadmap) section does not have any description to describe what the resources included in the section. THe task is to create simple and short description, something like this in [Tutorial or Courses](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#tutorials-or-courses) section

**Comment by himadeepthi1** [comment]
Hello ! @jfmartinz  , I would like to work on this issue

**Comment by himadeepthi1** [comment]
Hello @jfmartinz !!  I have added  a brief description in [Tutorial or Courses]  section in the Web Development Category under [Roadmap](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#roadmap) section , please merge my commit #235

**Comment by anushkasaxena07** [comment]
Hi ! @jfmartinz , I would like to work on this issue

**Comment by himadeepthi1** [comment]
hello ! @jfmartinz , kindly look into #266 and please see whether it is appropriate or not and merge accordingly , thankyou .

**Comment by JSuhas123** [comment]
Hey @jfmartinz I am GSSOC contributor can you please assign this issue to me I would love to work on it!
