### ISSUE TITLE
Introducing a "Roadmap" Section in Web3 Category

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#221]
Create a new section in [Web 3](https://github.com/jfmartinz/ResourceHub/tree/main/Web3) category about Roadmap. The resources must be about step by step or a roadmap for learning web3.  Provide at least 3 resources to include in the table. 

Follow the format for creating new resource and table. You can reference exisiting category to get an idea the format.

**Comment by MIpaltan007** [comment]
Please Assign me this. I can provide some really good resources along with Roadmaps. I have contributed ML Resources, earlier to this repository do check them out.

**Comment by 21atha** [comment]
Hey admin, please assign me this issue

**Comment by arpit4521** [comment]
please assign me this issue to add an extensive and proper roadmap
