### ISSUE TITLE
💡 [FEATURE] - Modify readme.md

### ISSUE THREAD

**Issue by sau-mili** [jfmartinz/ResourceHub#225]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding open source development in Read me

### Explain your solution

Just add it

**Comment by jfmartinz** [comment]
Where is your PR?

**Comment by 21atha** [comment]
Please assign me this issue, so to provide some contributions in this project and idea

**Comment by sau-mili** [comment]
Should I close the issue? Or, do you need to do it to get this considered? @jfmartinz

**Comment by 21atha** [comment]
Please assign me this issue, so I am able to provide some contributions in this project
