### ISSUE TITLE
💡 [FEATURE] - Addition of new domains: DATA SCIENCE and APP DEVELOPMENT, and new resources under DBMS README.md

### ISSUE THREAD

**Issue by samarpitadas** [jfmartinz/ResourceHub#243]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

1.  I would like to add learning resources for two new domains: **DATA SCIENCE** and **APP DEVELOPMENT**. 
2. Moreover I would like to add new resources under DBMS including **Oracle Database, Redis, Microsoft SQL Server** and **Amazon RDS (Relational Database Service)**.

### Explain your solution

@jfmartinz please assign the issue to me as this addition would make this resource platform more versatile.

**Comment by jfmartinz** [comment]
For the Data Science and App Development, you should create a folder and inside the folder it should have README.md file which will include all the resources and links. You can check other domains like web development, ui ux design and more to  get an idea what the README.md file should looks like. 

Anohter reminder, please make sure that the resources youre going to add is not duplicate, thanks

**Comment by samarpitadas** [comment]
> For the Data Science and App Development, you should create a folder and inside the folder it should have README.md file which will include all the resources and links. You can check other domains like web development, ui ux design and more to get an idea what the README.md file should looks like.
> 
> Anohter reminder, please make sure that the resources youre going to add is not duplicate, thanks

Sure, thank you.
