### ISSUE TITLE
💡 [FEATURE] - Adding a resource under web development Readme.md file

### ISSUE THREAD

**Issue by SaileePhal** [jfmartinz/ResourceHub#245]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to contribute to Readme.md file under web development by adding a playlist under YouTube Channels

### Explain your solution

I would like to add the playlist of Apna college which I found was very helpful for beginners

### Any alternative approaches/features

NA

**Comment by jfmartinz** [comment]
Thanks, assigned to you @SaileePhal.
