### ISSUE TITLE
💡 [FEATURE] - I would like to add a block chain section 

### ISSUE THREAD

**Issue by YadlaMani** [jfmartinz/ResourceHub#246]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Blockchain is currently in high demand, so I would like to incorporate it to benefit the students using the resource.

**Comment by jfmartinz** [comment]
Currently we have [blockchain](https://github.com/jfmartinz/ResourceHub/tree/main/Web3#blockchain-technologies) section.  You can add resources on that table, if this what you're referring to, Assigned!

**Comment by YadlaMani** [comment]
@jfmartinz yeah i am reffering to that

**Comment by YadlaMani** [comment]
@jfmartinz  if possible add level 2 tag for this issue

**Comment by YadlaMani** [comment]
@jfmartinz is there any bigger issue i can work on which no one is working on if there is any issue like that pls assign me that issue
