### ISSUE TITLE
💡 [FEATURE] -Adding OS resource to the repo

### ISSUE THREAD

**Issue by YadlaMani** [jfmartinz/ResourceHub#247]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

OS is very useful in techincal interviews and also to understand the system as a whole so i would like to add a OS to the resources so it would be really helpful to the students using the repo

**Comment by jfmartinz** [comment]
Maybe I am not going to add OS for now, since there a lot of categories already in the project and some of them are not even completed yet. I will create another issue for adding new sections to these categories. I will close this issue for now, thanks for understanding :)

**Comment by YadlaMani** [comment]
@jfmartinz do assign me that issue if you do that tho thank you

**Comment by jfmartinz** [comment]
> @jfmartinz do assign me that issue if you do that tho thank you

Ofc
