### ISSUE TITLE
💡 [FEATURE] - Add Java Development Resources

### ISSUE THREAD

**Issue by MastanSayyad** [jfmartinz/ResourceHub#248]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hi @jfmartinz 
I would like to add Complete resources for the domain of **Java development.**

**Java** remains one of the most widely used programming languages, applications ranging from Back end development, Java Full stack and CP to Android mobile apps. it would be a great addition to the ResourceHub project.

### Explain your solution

I propose adding a dedicated category for Java Development which includes:
- Roadmap
- Java Programming Basics
- Object-Oriented Programming (OOP)
- Java Tools and IDEs
- Java Frameworks and Libraries
- Resources focusing on Java EE technologies.
- Java Database Connectivity (JDBC)
- Java Web Development
- Android Development with Java
- Coding platforms to practice JAVA
- JAVA Project Ideas (Beginner, Intermediate, Advanced)
- Free Certification Cources.
- Resources for Java Interview Preperation

### Any alternative approaches/features

I will make it Completely Beginner-friendly to Advanced level.

### Additional Context

As a **Java developer & Contributor** I would like to take on this task, **Could you please assign this issue to me Under GSSoC'24?**

**Comment by jfmartinz** [comment]
Please create another Folder named 'Programming Languages' into the root of the project. Inside add the Java.md to the folder since. Follow this [format](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md#how-to-add-a-resource) for creating table and resources.

**Comment by jfmartinz** [comment]
This is the structure
```md
./
  /Programming Languages
    /Java.md
    /JS
    /Others...
```

Is it clear?

**Comment by MastanSayyad** [comment]
Yeah, Crystal clear. I have been assigned to create two folder, one is Java Development
```
./
  /Java Development
    /README.md
```
other is Programming Languages.

```
./
  /Programming Languages
    /Java.md
    /JS
    /Others...
```

is that right?

**Comment by jfmartinz** [comment]
Yes
