### ISSUE TITLE
💡 [FEATURE] - Creating a website for the repo

### ISSUE THREAD

**Issue by YadlaMani** [jfmartinz/ResourceHub#267]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like a create a website for the whole repo so it can deployed and would be more useful for the students

**Comment by YadlaMani** [comment]
@jfmartinz it would be great if you assign me this issue

**Comment by jfmartinz** [comment]
Somene is already working on it, and hes using SSG and API #166. What are your tech stack? I am not really sure when it is going to completed

**Comment by YadlaMani** [comment]
I want to create a full stack website
using basic html css and bootstrap
or i can use node if you want me to

**Comment by YadlaMani** [comment]
@jfmartinz it's resources so i can make a basic website till then

**Comment by jfmartinz** [comment]
Yea. I think the website needs a lot of improvements so it needs a lot of issues to be resolve and improve the experience for the eusers, just stand by.

**Comment by jfmartinz** [comment]
Sure

**Comment by YadlaMani** [comment]
@jfmartinz thanks
