### ISSUE TITLE
Update Read.me

### ISSUE THREAD

**Issue by sau-mili** [jfmartinz/ResourceHub#269]
Update with App Dev and data science

NB: I am a GSSOC Contributor

**Comment by JSuhas123** [comment]
Hey @jfmartinz I am GSSOC contributor can you please assign this issue to me I would be glad to work on it!

**Comment by sau-mili** [comment]
Check my pull req #283

**Comment by iamkanhaiyakumar** [comment]
I've noticed your project lacks a README.md file, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully. Can you assign me this task? I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

Thank u @jfmartinz

**Comment by jfmartinz** [comment]
> I've noticed your project lacks a README.md file, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully. Can you assign me this task? I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.
> 
> Thank u @jfmartinz

I actually have a [README.me](https://github.com/jfmartinz/ResourceHub/blob/main/README.md) file. Is this what youre referring for?

**Comment by sau-mili** [comment]
@jfmartinz you can close this issue as its done

**Comment by roushanverma23** [comment]
@jfmartinz please assign it to me, i want to work on this
