### ISSUE TITLE
💡 [FEATURE] - Adding more resources under Data Science Readme.md file

### ISSUE THREAD

**Issue by SaileePhal** [jfmartinz/ResourceHub#279]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to add more resources under Tools (approx 10+) in Data Science and would also like to add more resources under Technology that a person needs to master to be a successful Data Scientist

### Explain your solution

NA

### Any alternative approaches/features

NA

**Comment by arpit4521** [comment]
Understood the guidelines and contributing rules 
Assign me so that I can add numerous unique resources resulting in better for second person to understand and take use of these comprehensive unique resources
