### ISSUE TITLE
🐞 [BUG] -Fixing Bug

### ISSUE THREAD

**Issue by SaileePhal** [jfmartinz/ResourceHub#280]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

I would like to correct this bug spotted by me in the Data Science File
<img width="614" alt="typing error in Data Science file" src="https://github.com/jfmartinz/ResourceHub/assets/92790016/84da09c7-d856-44de-b6c1-697a2476d8ba">

### Expected behavior
Sir it should have been **Data Scientist** not App Developer

**Comment by jfmartinz** [comment]
Which bug? Can you describe it?

**Comment by SaileePhal** [comment]
Sir it should have been **Data Scientist** not App Developer

**Comment by SaileePhal** [comment]
Sir with your permission can I edit the above issue (created by me ) with the following bugs too that I have spotted that needs a fix

---DBMS (small documentation fix)
    --typing errors under Interview    
           --HackerRank    (not Hackerrank)

Image of DBMS Readme.md file
<img width="641" alt="typing errors in DBMS under Interview" src="https://github.com/jfmartinz/ResourceHub/assets/92790016/b55eeac1-586e-4395-97f8-86a3295c8b2e">

---UI/UX
   ---typing error of freebiesui  and uxcrush under Figma resources  
          --It should be
               --Freebiesui  (not FreesbieUI)
               --uxcrush  (one word - not ux crush)  (small documentation fix)

Image of UI/UX Readme.md file
<img width="667" alt="typing errors of freebies and uxcrush in UIUX  under figma resources" src="https://github.com/jfmartinz/ResourceHub/assets/92790016/dd621577-e2fe-4fa1-b237-dc76cffafeaf">

actual spelling taken from website:
1. Freebiesui
<img width="351" alt="Actual spelling of freebies in UIUX  under figma resources" src="https://github.com/jfmartinz/ResourceHub/assets/92790016/510ee636-3461-48d9-a970-3c2fbba77487">

2. uxcrush / UXCRUSH
<img width="297" alt="actual spelling uxcrush in UIUX  under figma resources" src="https://github.com/jfmartinz/ResourceHub/assets/92790016/1e14640c-bab1-49a1-9767-932a60c3c73b">

**Comment by SaileePhal** [comment]
@jfmartinz  sir please assign the above issue to me
