### ISSUE TITLE
💡 [FEATURE] - Add Python Development Resources

### ISSUE THREAD

**Issue by Pujan-sarkar** [jfmartinz/ResourceHub#291]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### I propose adding a section to ResourceHub that focuses on "Python Development in Web Development." This section will include:

1. Official Documentation:
    - Python, Django, Flask

2.Frameworks/Libraries:
    -  Django, Flask, Pyramid, FastAPI

3.Tools:
    - Pipenv, Virtualenv, Celery
    
4.Best Practices:
    - Real Python, The Hitchhiker’s Guide to Python, 12 Factors App

### Any alternative approaches/features

1. Ensure that all links are active and lead to relevant, high-quality resources.
2. Aim to include a mix of beginner, intermediate, and advanced resources to cater to a wide range of learners.
3. Suggest resources that offer project-based learning

### Additional Context

As a aspiring Python learner and developer I want to contribute in this issue under GSSoC'24 , could you assign this issue to me please @jfmartinz

**Comment by Pujan-sarkar** [comment]
@jfmartinz  please can you give an reply about this issue or assign me that i can start work on this

**Comment by jfmartinz** [comment]
Okay, assiged it to you, you can also refer to this README.md for reference: https://github.com/jfmartinz/ResourceHub/blob/main/Programming%20Languages/Java.md

**Comment by Pujan-sarkar** [comment]
@jfmartinz i have send a PR regarding this please check it , and could you change the lable of level from level2 to level3 .
I have seen that you have assigned the new resources added under level 3

**Comment by jfmartinz** [comment]
Sure :)
