### ISSUE TITLE
i want to ADD stone-paper-scissors game 

### ISSUE THREAD

**Issue by kartikmehta18** [jfmartinz/ResourceHub#298]
i am a gssoc contributor
i want to ADD stone-paper-scissors game in this 
can you plz allow me to add and plz assign me @jfmartinz
[kartikmehta18.github.io/javascriptgame/](https://kartikmehta18.github.io/javascriptgame/)  LIVE DEMO

**Comment by jfmartinz** [comment]
Hey @kartikmehta18. You should add projects that have a source code, video, tutorial, etc about that project. You can take a look at this [resource](https://www.codewithfaraz.com/content/339/build-a-simhttps://github.com/MohitSojitra/react-blog-website) as example.

**Comment by kartikmehta18** [comment]
> Hey @kartikmehta18. You should add projects that have a source code, video, tutorial, etc about that project. You can take a look at this [resource](https://www.codewithfaraz.com/content/339/build-a-simhttps://github.com/MohitSojitra/react-blog-website) as example.

Yes thanks but Can you please assign me for gssoc24

**Comment by sanjay-kv** [comment]
@jfmartinz Kindly assign issue which you think contributor can help with, else let them know by commenting or closing the issue.

**Comment by jfmartinz** [comment]
> @jfmartinz Kindly assign issue which you think contributor can help with, else let them know by commenting or closing the issue.

Noted

**Comment by kartikmehta18** [comment]
https://github.com/jfmartinz/ResourceHub/issues/298#top
https://github.com/jfmartinz/ResourceHub/issues/298 is solved i hope its helpfull @jfmartinz 
live link = https://kartikmehta18.github.io/javascriptgame/
repo link = https://github.com/kartikmehta18/javascriptgame

![image](https://github.com/jfmartinz/ResourceHub/assets/125860170/449c2c0b-c7c2-42a2-bad2-ac1583c7ff61)
video demo= 

https://github.com/jfmartinz/ResourceHub/assets/125860170/7293038a-16d6-4c42-af15-a9bc7880ec5e


Thank-you

**Comment by kartikmehta18** [comment]
> > @jfmartinz Kindly assign issue which you think contributor can help with, else let them know by commenting or closing the issue.
> 
> Noted

https://github.com/jfmartinz/ResourceHub/pull/428 done plz revew
