### ISSUE TITLE
ADD URL SHORTNER

### ISSUE THREAD

**Issue by kartikmehta18** [jfmartinz/ResourceHub#299]
in this repo i want to add **### url shortner** 
can i add this

**Comment by arpit4521** [comment]
Please assign me this issue so that i can start working upon that asap.

**Comment by jfmartinz** [comment]
Can you explain this issue more? Is this a project for [web development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development) category or something? Please explain

**Comment by kartikmehta18** [comment]
> Can you explain this issue more? Is this a project for [web development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development) category or something? Please explain

Yes this is a Java script,  html , css project 
Can u plz assign me

**Comment by roushanverma23** [comment]
@jfmartinz please assign this task, I want to work on this
![gssoc](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/137530796/bc19c5b1-a3c9-457f-b0f4-09e916b6b627)

**Comment by kartikmehta18** [comment]
> Can you explain this issue more? Is this a project for [web development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development) category or something? Please explain

Can you assign  me this also

**Comment by kartikmehta18** [comment]
[ADD URL SHORTNER](https://github.com/jfmartinz/ResourceHub/issues/299#top)
#299  is solved i hope its helpfull
live link = https://url-shortner-tau-woad.vercel.app/
repo link = https://github.com/kartikmehta18/URLshortner
 video demo = 

https://github.com/jfmartinz/ResourceHub/assets/125860170/f24db637-326d-4513-8f8b-6377bc0fd75f
Thank-you

**Comment by jfmartinz** [comment]
Add it to this [section](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#projects) under web development category and create a PR for it.

**Comment by jfmartinz** [comment]
You can check [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md#how-to-add-a-resource) and follow the format for adding a resource

**Comment by kartikmehta18** [comment]
> You can check [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md#how-to-add-a-resource) and follow the format for adding a resource

https://github.com/jfmartinz/ResourceHub/pull/394 plz review
