### ISSUE TITLE
🐞 [BUG] - App Development Courses Section

### ISSUE THREAD

**Issue by Nayanika1402** [jfmartinz/ResourceHub#302]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In App Development section particularly in the courses section there is a bug
![Screenshot 2024-05-18 085822](https://github.com/jfmartinz/ResourceHub/assets/132455412/0372a424-578d-4cc9-8f60-d77a9c341ad3)
In free courses the second course is not free.
In paid courses the first course link is not working as well as the second and third links are going into the site not directly to the course.

### Expected behavior

I want to fix this bug as well as add more courses.

### Additional Context

@jfmartinz Kindly look into this matter and assign me this issue.

**Comment by jfmartinz** [comment]
Thanks. Can you please also combined these tables into one? Something like this in [UI UX design](https://github.com/jfmartinz/ResourceHub/tree/main/UI-UX%20Design#tutorials-or-courses) Just specify which one is paid and free.

**Comment by Nayanika1402** [comment]
Absolutely no problem🤟🏻
