### ISSUE TITLE
💡 [FEATURE] - Add "Community and Forums" Section to Data Science Resources

### ISSUE THREAD

**Issue by SkSadaf** [jfmartinz/ResourceHub#320]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The current Data Science resources page provides a comprehensive list of tools, technologies, courses, books, and YouTube channels. However, it lacks a dedicated section for communities and forums. These platforms are vital for data science enthusiasts and professionals as they offer spaces to ask questions, share knowledge, and collaborate on projects. Including a "Community and Forums" section would enhance the resource collection by providing avenues for ongoing learning and community engagement.

### Explain your solution

To address this gap, I propose adding a new section titled "Community and Forums" to the Data Science resources page. This section would include a table listing several prominent communities and forums where users can engage with others in the data science field. The table should include the name of the community, a brief description, and a link to the platform.

**Comment by jfmartinz** [comment]
Just add Community, remove the Forum. Thanks

**Comment by SkSadaf** [comment]
Sure, will do it, Please assign this issue to me.
