### ISSUE TITLE
💡 [FEATURE] - Add "Competitions" Section to Data Science Resources

### ISSUE THREAD

**Issue by SkSadaf** [jfmartinz/ResourceHub#321]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The current Data Science resources page lacks a section for competitions. Competitions are valuable for practicing and showcasing data science skills, but there's no dedicated place for users to find these opportunities.

### Explain your solution

Add a new section titled "Competitions" to the Data Science resources page. This section should include a table with the names, descriptions, and links to platforms that host data science competitions.

**Comment by jfmartinz** [comment]
Instead of Competitions, maybe you can add Challenges instead. Assigned to you

**Comment by SkSadaf** [comment]
Thanks for the suggestion, I will do it.
