### ISSUE TITLE
Add Tutorial or courses for UI & UX design

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#33]
Currently there is a few resources in the UI UX design tutorial or courses section, you task is to find valuable resource that you think is helpful and worth sharing to the community.

Please make sure that you read the [Contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before raising a pr

**Comment by Sugamgoel28** [comment]
@jfmartinz I want to work on this issue, Can you please assign this to me sir/ma'am?

**Comment by jfmartinz** [comment]
> @jfmartinz I want to work on this issue, Can you please assign this to me sir/ma'am?

Hello. you can actually start making changes to the repo. Make sure that you don't spann prs so hacktoberfest accepts your contribution. Happy contributing
