### ISSUE TITLE
💡 Add "JavaScript" Complete Resources

### ISSUE THREAD

**Issue by MastanSayyad** [jfmartinz/ResourceHub#338]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hey, @jfmartinz
Add **javascript** complete resources in the programming languages folder **js.md**

### Explain your solution

I will try to include:
- Roadmap
- Basics Syntax and Basic Constructs
- Control Structures: Conditionals (if, else if, else, switch) Loops (for, while, do-while)
- Functions
- Tools and IDEs
- Intermediate JavaScript
- Object-Oriented Programming (OOP)
- Asynchronous JavaScript: Callbacks, Promises, Async/Await
- Error Handling
- DOM Manipulation
- Advanced JavaScript Topics
- Frameworks and Libraries
- Back-End Development with JavaScript
- Projects
- Courses 
- Youtube channel
- And Many more (If any)

**Comment by jfmartinz** [comment]
Hye please take note the instruction I made in your other issue which is about c++, thanks.

**Comment by Yuvraj960** [comment]
@jfmartinz Please assign this issue to me under GSSoC24. I will do this work
