### ISSUE TITLE
Add a tool resource for web development

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#34]
Currently there are only few tools for web development. You task is to find resource that you think is helpful and worth sharing with anyone. 

Please make sure that you read the [Contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before raising a pr

**Comment by Sugamgoel28** [comment]
@jfmartinz I want to work on this issue, Can you please assign this to me sir/ma'am?

**Comment by RitaDee** [comment]
Can I be assigned this?

**Comment by RitaDee** [comment]
Thank you @jfmartinz.

**Comment by jfmartinz** [comment]
No problem @RitaDee.
