### ISSUE TITLE
💡 [FEATURE] - Add LINUX Development Resources

### ISSUE THREAD

**Issue by shuvadeepmondal** [jfmartinz/ResourceHub#346]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to contribute to ResourceHub by adding a comprehensive list of resources focusing on "Linux Development". This will include tutorials, documentation, tools, basic commands in Linux.

### Explain your solution

Sure, here's a shorter version with points:

1. **Research and Compile**: Gather tutorials, documentation, tools, and Linux commands for development.
  
2. **Verify Quality**: Ensure accuracy and relevance of each resource.

3. **Write Descriptions**: Create brief descriptions highlighting key features.

4. **Format for Clarity**: Organize resources for easy navigation.

5. **Engage and Update**: Interact with users, keep the list current.

### Any alternative approaches/features

1.Ensure that all links are active and lead to relevant, high-quality resources.
2.Aim to include a mix of beginner, intermediate, and advanced resources to cater to a wide range of learners

### Additional Context

As a aspiring Linux developer I want to contribute in this issue under GSSoC'24 , could you assign this issue to me please @jfmartinz

**Comment by jfmartinz** [comment]
Please create new folder for it and inside create an readme.md file. Follow the format for creating sections and resources under CONTRIBUTING.md.

**Comment by shuvadeepmondal** [comment]
@jfmartinz  Sir please review and merge it
