### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by suma30** [jfmartinz/ResourceHub#348]
It would be beneficial if the readme file have a live link to the project and I can add it,
please assign me this issue under GSSOC'24
@jfmartinz

**Comment by Chandana-756** [comment]
I would like to work on this issue under GSSOC'24

**Comment by Kumar-Ankit56** [comment]
@suma30 are you saying about repo link ?

**Comment by jfmartinz** [comment]
The website is still in development
