### ISSUE TITLE
Add a books resource for web development

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#35]
Currently there are only few books that are available within the web development category and you need to find a helpful books to add in the list. 

Please make sure that you read the [Contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before raising a pr

**Comment by Sugamgoel28** [comment]
@jfmartinz I want to work on this issue, Can you please assign this to me sir/ma'am?
