### ISSUE TITLE
Add a challenges resource in web development

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#37]
Currently there are few challenges resource list in the web development and you task is to find website that help developers build their coding and problem solving skills. It can be leetcode, front end mentor, or any challenges resources you think is suitable for the list.

Please make sure that you read the [Contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before raising a pr

**Comment by RABBI31** [comment]
Hello,
I can help you find new resources for increasing the community buildup

 thank you

**Comment by Sugamgoel28** [comment]
@jfmartinz I want to work on this issue, Can you please assign this to me sir/ma'am?

**Comment by jfmartinz** [comment]
You can make the pr, this issue is for everyone. Goodluck

> Hello, I can help you find new resources for increasing the community buildup
> 
> thank you

**Comment by RABBI31** [comment]
Please checkout my pr. Give me review if any had.
