### ISSUE TITLE
💡 [FEATURE] - Adding A Section for Data Structures and Algorithms(DSA)

### ISSUE THREAD

**Issue by MIpaltan007** [jfmartinz/ResourceHub#399]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Data Structures and Algorithms (DSA) are the most demanded skills an interviewer looks for in a candidate in an interview. Many times candidates are confused about certain things like what to study, where to study, are these enough? . A dedicated section would really help the candidates crack their interviews and help them land their dream jobs.

### Explain your solution

I would like to share all the Data Structures and their description. Along with that YouTube Channels, Courses, Sites to practice and learn and some useful resources. Also I have one doubt, I have pdfs saved in my local system, how can I upload them so that others too can access them.

**Comment by MIpaltan007** [comment]
@jfmartinz Look into it, you can assign me this after creating a section.

**Comment by GauriGA** [comment]
@MIpaltan007
Hello, I would like to work on this issue. Could you please assign it to me?

**Comment by MIpaltan007** [comment]
@jfmartinz Bro, please look into it once again. This too is a very useful category.

**Comment by jfmartinz** [comment]
Is this a new Category or domain?

> @jfmartinz Bro, please look into it once again. This too is a very useful category.

**Comment by MIpaltan007** [comment]
> Is this a new Category or domain?
> 
> > @jfmartinz Bro, please look into it once again. This too is a very useful category.

@jfmartinz It is the king of all categories. You can't clear the coding round of any company if you are not good at DSA. Also in interviews, no matter how good a developer you are, still you will be asked DSA related questions and that actually decides your placement. This is what I have experienced, also the current scenario in India.

**Comment by jfmartinz** [comment]
Okay, sure. Please add it under Programming Languages and make sure that you follow the format, please take a look carefully.

**Comment by MIpaltan007** [comment]
Sure sir. Before that, Assign me this Issue
