### ISSUE TITLE
🐞 [BUG] - 404 page not found error [Machine Learning Github Repository Section]

### ISSUE THREAD

**Issue by Sneha6290** [jfmartinz/ResourceHub#410]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/92674168/f4a2838f-dde6-407a-8994-1d77f6d9e0d7)
The last link [Books for Learning Machine Learning](https://github.com/dlsucomet/MLResourceshttps://github.com/dlsucomet/MLResources)
after clicking on this 404 page not found error occurred.
![image](https://github.com/jfmartinz/ResourceHub/assets/92674168/6a75c56a-ae76-433b-9281-a7137ceb5768)

### Expected behavior

It should lead to a GitHub repository like others.

### Steps to reproduce

We can remove this part of the section to get rid off this 404 page not found error.

**Comment by jfmartinz** [comment]
Nice. You can either remove it or add any resource, assigned to you!
