### ISSUE TITLE
💡 [FEATURE] - Add 'C# Programming Language' Complete Resources

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [jfmartinz/ResourceHub#420]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

C# Programming Language is missing, which is widely used for developing desktop applications, web applications, and games. It is popular in industry for its versatility, performance, and integration with the .NET framework.

### Explain your solution

I propose adding resources for learning C# from basics to advanced levels, which will include:
C# Basics:
- Data types (integers, floats, strings, etc.)
- Variables and operators
- Control structures (if-else, loops)
- Methods and properties
- Object-Oriented Programming (classes, inheritance, polymorphism, encapsulation)

Data Manipulation:
- Working with collections (arrays, lists, dictionaries)
- LINQ for data querying
- File I/O operations

Web Development:
- Introduction to ASP.NET Core
- Creating RESTful APIsMVC (Model-View-Controller) architecture

Desktop Applications:
- Windows Forms
- WPF (Windows Presentation Foundation)
- UWP (Universal Windows Platform)

Game Development:
- Introduction to Unity with C#
- Basic game mechanics
- Developing 2D and 3D games

Advanced Topics:
- Multithreading and asynchronous programming
- Working with databases (Entity Framework, SQL)
- Integration with Azure services
- Creating and using NuGet packages

Machine Learning:
- Introduction to machine learning with ML.NET
- Data preprocessing
- Building and training models
- Model evaluation and deployment

Project Ideas:
- Real-world applications

### Any alternative approaches/features

To enhance the learning experience, I suggest including important resources such as books, YouTube channels, and websites. This will provide comprehensive and accessible learning material. Additionally, I propose creating a beginner-friendly roadmap to guide learners through the resources step-by-step.

### Additional Context

This feature request aims to enrich the programming language section by providing extensive learning materials for C#, similar to Python. This will cater to the high demand for C# knowledge in software development, game development, and enterprise applications.

**Comment by Santhosh-Siddhardha** [comment]
@jfmartinz please assign me this issue.

**Comment by GauriGA** [comment]
@jfmartinz Can you please assign this issue to me under the GSSOC'24 label?

**Comment by Santhosh-Siddhardha** [comment]
@jfmartinz Please assign me this issue, I want to work on it

**Comment by jfmartinz** [comment]
Assigned to you @Santhosh-Siddhardha. Follow always the guidelines
