### ISSUE TITLE
Add contributor's list in README.md

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#43]
Add a contributors list to the project's README file to acknowledge and showcase the profiles of all the valuable contributors who contribute to the project. Put it next to the license heading

Something like this:
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/9d84de96-027b-44bf-8078-a9c485ae30d9)

**Comment by sasidharirl** [comment]
Hi
I want to work on this issue
