### ISSUE TITLE
💡 [FEATURE] -  Add "Typescript Programming Language" Complete Resources

### ISSUE THREAD

**Issue by Vaibhavsg17** [jfmartinz/ResourceHub#445]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

TypeScript, a statically typed superset of JavaScript, enhances the development experience by providing type safety and improved tooling. Despite its growing popularity and significant adoption in both frontend and backend development, our current documentation lacks comprehensive resources dedicated to TypeScript.

### Explain your solution

TypeScript Basics:
-Setting up the TypeScript environment: Installation and configuration.
-Understanding TypeScript: Type annotations, basic types, interfaces, and type aliases.
-Compiler options and configuration: tsconfig.json setup and common compiler options.
-Type Inference: How TypeScript infers types and best practices.

Advanced TypeScript:
-Generics: Using generics to create reusable components.
-Advanced Types: Union types, intersection types, mapped types, and conditional types.
-Decorators: Understanding and using decorators in TypeScript.
-Namespaces and Modules: Organizing code with namespaces and ES modules.

TypeScript with Frameworks:
-TypeScript with Node.js: Setting up a Node.js project with TypeScript.
-TypeScript with React: Creating and managing React components with TypeScript.
-TypeScript with Angular: Using TypeScript as the primary language in Angular projects.
-TypeScript with Vue: Integrating TypeScript into Vue.js applications.

-TypeScript Tools and Libraries:
-Type Checking and Linting: Using tools like TSLint and ESLint for code quality.
-Testing TypeScript Code: Setting up and using testing frameworks like Jest with TypeScript.
-TypeScript and Build Tools: Integrating with Webpack, Babel, and other build tools.

Performance and Optimization:
-TypeScript Compiler Performance: Optimizing the TypeScript compiler.
-Best Practices: Code organization, strict type-checking, and other best practices.

Deployment:
-Building and Deploying TypeScript Projects: Compiling TypeScript and deploying applications.
-Continuous Integration and Delivery: Setting up CI/CD pipelines for TypeScript projects.

TypeScript Projects:
-Real-world applications: Examples of TypeScript in production projects.

### Any alternative approaches/features

To enhance the learning experience, I suggest including essential resources such as recommended books, YouTube channels, and websites. Additionally, providing a beginner-friendly roadmap can help new developers navigate through the resources step-by-step.

### Additional Context

Books, Courses, and Tutorials: Recommended books, online courses, and tutorials for learning TypeScript.
Community and Support: Useful links to TypeScript communities, forums, and support channels.

**Comment by Vaibhavsg17** [comment]
@jfmartinz  Assign me this issue, I want to work on it

**Comment by jfmartinz** [comment]
I already assigned this to someone else, can you choose other prog language?

**Comment by Vaibhavsg17** [comment]
> I already assigned this to someone else, can you choose other prog language?

@jfmartinz Sure
