### ISSUE TITLE
Hacktoberfest 2023 Contribution Opportunity

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#45]
Hello! I would like to extend an invitation to all of you to contribute to my repository. You can check the listed issues or create new ones. There are plenty of opportunities to make improvements within the project, and your contributions will be greatly appreciated!

**Comment by VinayakGaikwad101** [comment]
Hi! Please assign this issue to me, I would like to contribute, cheers  :)

**Comment by jfmartinz** [comment]
> Hi! Please assign this issue to me, I would like to contribute, cheers :)

Hello @VinayakGaikwad101 you can check the issues here or create a new one. If you're adding a resource create pr automatically otherwise raise an issue.

**Comment by abhisar-yadav** [comment]
@jfmartinz  is this project recognized under hacktoberfest?
