### ISSUE TITLE
💡 [ADD] -Need to add more resources for React Native 

### ISSUE THREAD

**Issue by saikrishna823** [jfmartinz/ResourceHub#459]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I have gone through the app development folder and I found very less resources to learn react native.

### Explain your solution

I have good experience of working with ReactNative and I would like to add more resources to that folder.As we in future react Native will be used widely so adding more resources will help others to learn it fast and easy.

**Comment by jfmartinz** [comment]
Assigned to you

**Comment by saikrishna823** [comment]
@jfmartinz ,Can i create separate readme.md file for react native.I would be nice,adding all the resources related to react native in one separate file.

**Comment by jfmartinz** [comment]
You should add this then in programming languages, but the resources and section should be enough. What do you plan to add in this readme?

**Comment by saikrishna823** [comment]
Okay then I will update existing readme file.

**Comment by saikrishna823** [comment]
As per our project structure,I don't think react native can be added into programming language folder.

**Comment by jfmartinz** [comment]
okay, sorry. You can more resources to that folder, app development

**Comment by saikrishna823** [comment]
@jfmartinz ,Could you please check my pull request?Let me know if any issues exits
