### ISSUE TITLE
💡 [FEATURE] - Add complete resources for NEXT JS

### ISSUE THREAD

**Issue by chaanakyaaM** [jfmartinz/ResourceHub#463]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Next.js is a react based framework, that enables functionality such as server-side rendering and generating static websites for React-based web applications. It simplifies building production-ready applications with minimal configuration

### Explain your solution

I would like to add resources for NEXT JS including:

### Setting up the environment
- Installing Node.js and npm/yarn
- Creating a new Next.js project
- Basic project structure

### Pages and Routing
- Creating pages
- File-based routing
- Dynamic routing
- Catch-all routes

### Static Generation and Server-Side Rendering
- Static generation (getStaticProps)
- Incremental Static Regeneration (ISR)
- Server-side rendering (getServerSideProps)
- Differences and use cases

### API Routes
- Creating API routes
- File-based API routing
- Handling different HTTP methods (GET, POST, PUT, DELETE)

### Components in Next.js
- Creating components
- Importing and using components
- Component styling

### Data Fetching
- Fetching data on the client side
- Fetching data on the server side
- getStaticProps vs getServerSideProps

### Image Optimization
- Using the Next.js Image component
- Configuring image optimization
- Best practices for image handling

### Custom Document and App
- Customizing the Document (Document.js)
- Customizing the App (App.js)
- Adding global styles and scripts

### Middleware
- Using middleware in Next.js
- Creating custom middleware

### Internationalization (i18n)
- Setting up internationalization
- Localized routing
- Managing translations

### State Management Options
- Using React Context API
- Using Redux with Next.js
- Other state management libraries (e.g., Zustand, Recoil)

### CSS and Sass
- Importing CSS files
- Using Sass/SCSS
- CSS Modules

### Styled-components
- Setting up styled-components
- Using styled-components in Next.js

### Testing in Next.js
- Setting up Jest for testing
- Using React Testing Library
- Writing and running tests

**Comment by deepak-bhagat-iitr** [comment]
Please assign this issue to me @jfmartinz
