### ISSUE TITLE
💡 [FEATURE] - Add "Dart" Complete Resources

### ISSUE THREAD

**Issue by Vaibhavsg17** [jfmartinz/ResourceHub#500]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Dart, a client-optimized programming language for fast apps on any platform, has gained significant traction, especially with the rise of Flutter for mobile app development. Despite its growing popularity, our current documentation lacks comprehensive resources dedicated to Dart.

### Explain your solution

Dart Basics:
-Setting up the Dart environment: Installation and configuration for different platforms.
-Understanding Dart syntax and features: Variables, data types, functions, and control flow.
-Object-oriented programming in Dart: Classes, objects, interfaces, and inheritance.
-Functional programming in Dart: Lambdas, higher-order functions, and collections.

Advanced Dart:
-Asynchronous programming: Futures, async/await, and streams.
-Error handling: Exception handling and custom exceptions.
-Dart Standard Library: Exploring the standard library and its utilities.
-Interoperability: Using Dart with other languages and platforms.

Dart for Flutter Development:
-Setting up Dart for Flutter: Configuring a Flutter project with Dart.
-Flutter Widgets: Building UIs with Dart and Flutter widgets.
-State Management: Managing state in Flutter applications with Provider, Riverpod, etc.
-Navigation and Routing: Implementing navigation in Flutter apps.
-Dart and Flutter Plugins: Using and creating plugins for Flutter.

Dart for Web Development:
-Dart and HTML: Building web applications with Dart.
-Dart with AngularDart: Using Dart with Angular for web development.
-Server-side Dart: Building backend services with Dart and frameworks like Aqueduct or Shelf.

Performance and Optimization:
-Best Practices: Writing efficient Dart code.
-Profiling and Debugging: Tools and techniques for profiling and debugging Dart applications.

Deployment:
-Building and Deploying Dart Applications: Compiling Dart code and deploying applications.
-Continuous Integration and Delivery: Setting up CI/CD pipelines for Dart projects.

Dart Projects:
-Real-world applications: Examples of Dart in production projects.

Additional Resources:
Books, Courses, and Tutorials: Recommended books, online courses, and tutorials for learning Dart.
Community and Support: Useful links to Dart communities, forums, and support channels.

### Any alternative approaches/features

To enhance the learning experience, I suggest including essential resources such as recommended books, YouTube channels, and websites. Additionally, providing a beginner-friendly roadmap can help new developers navigate through the resources step-by-step.

### Additional Context

This feature request aims to enrich the Web Development section by providing extensive learning materials for Dart, similar to existing resources for other technologies. This will cater to the high demand for Dart knowledge in mobile development with Flutter, web development, and backend development, improving the overall utility of our documentation for developers at all levels.

**Comment by jfmartinz** [comment]
Please follow the format, you can check other folders in programming languages folder, thans

**Comment by ayush-848** [comment]
@jfmartinz please assign this issue to me under GSSoC'24

**Comment by Vaibhavsg17** [comment]
> @jfmartinz please assign this issue to me under GSSoC'24

@ayush-848 bro I am working on it

**Comment by Vaibhavsg17** [comment]
@ayush-848 you can't create pull request  until it is assign to you

**Comment by Vaibhavsg17** [comment]
@jfmartinz till 5 pm i will create the pull request for this

**Comment by ayush-848** [comment]
> @ayush-848 you can't create a pull request until it is assigned to you. it really bad practice

I am really sorry bro 
I saw it was 4 days ago and those bot messages

Let me cancel them

**Comment by ayush-848** [comment]
@Vaibhavsg17 Sorry for the inconvenience bro. Continue your work
