### ISSUE TITLE
💡 [FEATURE] - Add Footer to the website

### ISSUE THREAD

**Issue by Sneha123-zudo** [jfmartinz/ResourceHub#502]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to add footer to this website as it improves the UI of the website. 

### Explain your solution

I will add footer to the website.

### Additional Context

Please assign me this issue under GSSOC'24.

**Comment by GauriGA** [comment]
@jfmartinz I would like to work on this issue, could you assign me this under the GSOC'24 label?

**Comment by GauriGA** [comment]
@jfmartinz Please respond!!
