### ISSUE TITLE
ADD Memory Game  using JavaScrip

### ISSUE THREAD

**Issue by kartikmehta18** [jfmartinz/ResourceHub#518]
i want to add Memory Game using JavaScript
![image](https://github.com/jfmartinz/ResourceHub/assets/125860170/3a9b78dc-e18f-4760-bfd0-e5cbb41335c8)

**Comment by jfmartinz** [comment]
No need to reaise an issue if you're adding a resource, create the PR directly unless youre adding a section or new category

**Comment by kartikmehta18** [comment]
> No need to reaise an issue if you're adding a resource, create the PR directly unless youre adding a section or new category

if i do pr directly do can i get gssoc level point??
plz review https://github.com/jfmartinz/ResourceHub/pull/527
