### ISSUE TITLE
💡 [FEATURE] - Display "NOT FOUND" if a resource is not present

### ISSUE THREAD

**Issue by swetha5157** [jfmartinz/ResourceHub#540]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I and even others get confused when a search bar doesn't display anything, like whether the page is loading or the requested data is not present.

### Explain your solution

Therefore Inclusion of "Not found" String to make users vividly know that requested resource is not present in the website.
![Screenshot_20240528_180325_Chrome](https://github.com/jfmartinz/ResourceHub/assets/123291594/cf902843-b7e1-45e5-a50d-4d8ce0561339)

Kindly assign to me @swetha5157 under gssoc and add level labels

**Comment by swetha5157** [comment]
I am waiting to be assigned by the owner of the repo

**Comment by KomalSrivastava** [comment]
@jfmartinz 
Feature Request:
To enhance user experience and clarity, propose adding a "Not Found" message when the requested resource is not available or cannot be located on the website. This feature aims to reduce confusion and provide immediate feedback to users when they encounter empty search results or unavailable content.

Solution:

Implementation of "Not Found" Message: Integrate logic to detect when a requested resource is not found, such as empty search results or invalid URLs.
Display Mechanism: Display the "Not Found" message prominently on the page, using clear and concise language to inform users of the issue.
Consistent User Interface: Ensure consistency in the appearance and placement of the "Not Found" message across different sections of the website to maintain a cohesive user experience.
Accessibility Considerations: Implement accessibility features to ensure that the "Not Found" message is accessible to all users, including those using screen readers or assistive technologies.
Customization Options: Provide options for website administrators to customize the "Not Found" message to align with the website's branding and tone.
Additional Context:
By including a "Not Found" message, users will receive immediate feedback when encountering empty search results or unavailable content, reducing confusion and improving the overall user experience.

 Please assign this feature request to me, as I'm eager to contribute to enhancing the project's usability. Additionally, please add the "gssoc24" label to track progress on this enhancement.

**Comment by swetha5157** [comment]
Thankyou for assigning the issue @jfmartinz
