### ISSUE TITLE
💡 [FEATURE] - Adding a new resource in the UX/UI section

### ISSUE THREAD

**Issue by sandy-queen** [jfmartinz/ResourceHub#545]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding a new resource to in the UX/UI section.

### Explain your solution

The website I want to add is called [ The Designer's Toolbox](https://www.thedesignerstoolbox.com/).

It contains courses and products, along with various free resources that can help UX/UI designers.  

### Additional Context

**Please assign this issue to me, as I would like to work on it**

**Comment by jfmartinz** [comment]
> I would like to add it in the "Tutorials and Courses" section, because I think that's where it would fit the best.

I think just add it in community section.

**Comment by sandy-queen** [comment]
> I think just add it in community section.

OK. I am working on it. Thank you for assigning this issue to me.
