### ISSUE TITLE
🐞 [BUG] - NavBar alignment and about page

### ISSUE THREAD

**Issue by sau-mili** [jfmartinz/ResourceHub#549]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

Fix navbar alignment and add content in about page
![Screenshot 2024-05-29 003051](https://github.com/jfmartinz/ResourceHub/assets/146661411/0dfdfec1-5575-46ac-aa0b-7f3437440675)

**Comment by katarianikita2003** [comment]
Hello @jfmartinz  , I want to work on this issue. Can you please assign it to me?
