### ISSUE TITLE
💡 [FEATURE] - <title>Enhance Testimonial Section with Flexbox and Flip Card Styling

### ISSUE THREAD

**Issue by DebapriyaJha** [jfmartinz/ResourceHub#563]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to request an enhancement to the styling and layout of the testimonial section on the website. The current design may appear outdated or lacking in visual appeal, which could negatively impact user engagement and overall user experience.

### Explain your solution

To address the issues mentioned above and enhance the testimonial section, I propose implementing the following solutions:

1) Flexbox Layout: Utilize the CSS Flexbox layout module to create a visually appealing grid-like layout for the testimonials.
2) Flip Card Animation: Implement a flip card animation effect for each testimonial, where the front side displays the person image with name and designation, and the back side reveals the full testimonial text or additional details. 

### Any alternative approaches/features

While the proposed solution primarily focuses on using Flexbox and the flip card animation effect, there are alternative approaches and features that could be considered:

Carousel/Slider: Instead of a grid-like layout, the testimonials could be displayed in a carousel or slider format, allowing users to navigate through them seamlessly.

### Additional Context

Front part something looks similar to this- 
![1](https://github.com/jfmartinz/ResourceHub/assets/111692420/2d1f1562-164f-4995-ad75-6ed856b14776)
And the Back part -
![2](https://github.com/jfmartinz/ResourceHub/assets/111692420/19396139-4920-4f52-afad-36eb54575d45)

**Comment by anuukriti** [comment]
@jfmartinz  Please assign this issue to me as well
