### ISSUE TITLE
I want to add the about page💡 

### ISSUE THREAD

**Issue by aindrelasaha** [jfmartinz/ResourceHub#565]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

![image](https://github.com/jfmartinz/ResourceHub/assets/126545390/ed537f9a-e0c5-4475-90d8-39b1a2edc9ea)
I want to add about section explaining the usages of the site and how to use the site.

### Explain your solution

Write about the description of the website and how to use and why its created 

### Any alternative approaches/features

no

**Comment by jfmartinz** [comment]
Hi this issue is already assigned to someone else #549
