### ISSUE TITLE
🐞 [BUG] - out of the box issue in different browsers

### ISSUE THREAD

**Issue by aindrelasaha** [jfmartinz/ResourceHub#566]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/126545390/b8d34278-68dd-45a3-9ba6-e69a5add9d05)
![image](https://github.com/jfmartinz/ResourceHub/assets/126545390/582ea0e5-e79c-46a5-866b-5942f8762876)
the first image is of when the site is opened from edge 
and 2nd is from chrome
the font is different in the two browsers itself and its going out of the box which is making the site look bad

### Expected behavior

the font should be properly fit in the box

### Steps to reproduce

 font size should dynamically adjusted to fit within the box dimensions.
css can be used for this

**Comment by jfmartinz** [comment]
I think this issue is also taken. #564

**Comment by aindrelasaha** [comment]
yeah
