### ISSUE TITLE
🐞 [BUG] - Navbar Menu

### ISSUE THREAD

**Issue by hars-21** [jfmartinz/ResourceHub#572]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In desktop view, the hamburger icon is visible. In mobile view menu screen has less opacity which degrades readability. 
Navbar has extra space which can be reduced.
Also the links doesn't redirect to good place. It redirects to folder structure which is not good.
![Screen Shot 2024-05-29 at 8 50 54 PM](https://github.com/jfmartinz/ResourceHub/assets/144909381/96a590ff-1acd-4f8a-be5a-bcef86ef5934)
![Screen Shot 2024-05-29 at 8 55 06 PM](https://github.com/jfmartinz/ResourceHub/assets/144909381/63a66a6b-625f-4d63-afd3-601546c195b1)
![Screen Shot 2024-05-29 at 9 01 44 PM](https://github.com/jfmartinz/ResourceHub/assets/144909381/bf49a898-fba0-4097-b826-260f95b5ae8f)

### Expected behavior

In Desktop view, hamburger icon should not be displayed. It should only appear in mobile view. 
Enhance navbar menu in mobile view and make it readable for user.
Enhancing Styling for navbar, reducing extra height, adding search option in navbar.
Fixing links to redirect on home page till the further required pages are added.

**Comment by nishant0708** [comment]
i can fix this bug please assign me this issue

**Comment by Kaustubhraidev** [comment]
please assign it to me I have more than 2 years experience
