### ISSUE TITLE
💡 [FEATURE] - Scroll Bar

### ISSUE THREAD

**Issue by hars-21** [jfmartinz/ResourceHub#573]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The scroll bar in website has default styling which does not match the theme of the website and degrades the UI.
![Screen Shot 2024-05-29 at 8 51 12 PM](https://github.com/jfmartinz/ResourceHub/assets/144909381/d96b1aae-e56f-4b31-b6de-82d317527e91)

### Explain your solution

Enhance scroll bar. Changing its colour according to the website theme. Add visibility only when scrolling and disabling after the page is still (while user is not scrolling and stops at particular section).

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.
