### ISSUE TITLE
💡 [FEATURE] - Add Google Login/SignIn

### ISSUE THREAD

**Issue by ritankarsaha** [jfmartinz/ResourceHub#583]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I intend on adding google login/signin to the page which will enable the user to log in with their email into the website. However the user can still use the website without getting logged in. This includes the use of Google API keys in successfully creating an OAuth client.

### Explain your solution

Create a google login/sign in button and adding it up to the top corner of the webpage

### Any alternative approaches/features

nope

### Additional Context

This will provide a better UI, enhancing the functionality of website.

**Comment by ritankarsaha** [comment]
Please assign this issue to me under gssoc'24. Also please add the labels gssoc and level.
Thank You.

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.

**Comment by jfmartinz** [comment]
No need auth for now
