### ISSUE TITLE
Add Favicon 

### ISSUE THREAD

**Issue by heli0707** [jfmartinz/ResourceHub#587]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I Want to add the favicon to the blog page.
Please assign me 

### Explain your solution

![image](https://github.com/jfmartinz/ResourceHub/assets/95361125/7792d1bd-6d11-4699-9f7f-396d3c2959f7)

**Comment by katarianikita2003** [comment]
Hello @jfmartinz  , I want to work on this issue. Can you please assign it to me?
