### ISSUE TITLE
🐞 [BUG] - Container for resources are getting overflow

### ISSUE THREAD

**Issue by MitulSonagara** [jfmartinz/ResourceHub#590]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In main page of website resources are getting overflow from the boxes... i can fix this
![image](https://github.com/jfmartinz/ResourceHub/assets/95460188/d1729640-9a98-4700-911a-5ac46afb5ec3)

**Comment by jfmartinz** [comment]
This is duplicate issue
