### ISSUE TITLE
🐞 [BUG] - Card under text is not proper responsive it move out of the card , I fix this issue

### ISSUE THREAD

**Issue by kaushal8582** [jfmartinz/ResourceHub#591]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

🐞 [BUG] - Card under text is not proper responsive it move out of the card , I fix this issue, plz assign me this issue
![ResourceHub - Brave 30_05_2024 17_36_23](https://github.com/jfmartinz/ResourceHub/assets/137991463/033a39fd-7edd-48dd-8af0-578a7e4dffef)

**Comment by kaushal8582** [comment]
i found this issue , plz assign me for fix it.

**Comment by jfmartinz** [comment]
Duplicate issue, someone is already working on it
