### ISSUE TITLE
💡 [FEATURE] - Add SQL Projects

### ISSUE THREAD

**Issue by ImmidiSivani** [jfmartinz/ResourceHub#601]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to add "Projects" section in DBMS(DataBase)

### Explain your solution

I would like to add 
library Database Management System, Hospital Information Management system  and Student Database Management System SQL projects tutorials and resources.

**Comment by Kaustubhraidev** [comment]
please assign it to me I can resolve this.
