### ISSUE TITLE
🐞 [BUG] - Easy Navigation

### ISSUE THREAD

**Issue by hars-21** [jfmartinz/ResourceHub#604]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

Currently, The index section for every category doesn't work. The Redirection links which were made for easy navigation doesn't link well with the website.
![Screen Shot 2024-05-30 at 9 33 59 PM](https://github.com/jfmartinz/ResourceHub/assets/144909381/ed6489e0-fb5f-4c2a-a854-9b5456136e8e)

### Expected behavior

The Table of content section for every category should navigate to their corresponding section. Currently it contains broken links that should be change to working link that will provide user easy navigation.

**Comment by Kaustubhraidev** [comment]
I can dot it please assign it to me. I have more than 2 years of experience.
