### ISSUE TITLE
🐞 [BUG] - <Favicon.ico not showing in the header>

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [jfmartinz/ResourceHub#606]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/125277258/d7c5a25a-51d8-42be-b556-412ebcb86066)

**Comment by CoderGirl2844** [comment]
I would like to work on this issue please assign this issue to me

**Comment by jfmartinz** [comment]
This issue is resolved
