### ISSUE TITLE
💡 [FEATURE] - Contact page for the website-ResourceHub

### ISSUE THREAD

**Issue by Dsmita03** [jfmartinz/ResourceHub#614]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

<img width="1280" alt="website" src="https://github.com/jfmartinz/ResourceHub/assets/123728188/77df05d2-142f-40e6-90a6-2fcba2dcff6a">
  
[As you can see no contact page is present for the given website, so i want to add it]

### Explain your solution

<img width="640" alt="contact page" src="https://github.com/jfmartinz/ResourceHub/assets/123728188/00c5a902-47a8-44af-ba2d-2821d3d46a50">

For reference- 
The UI design for this will be little bit different

**Comment by jfmartinz** [comment]
duplicate https://github.com/jfmartinz/ResourceHub/issues/574
