### ISSUE TITLE
🐞 [BUG] - texts in Card should be white in light mode

### ISSUE THREAD

**Issue by Sowham-3098** [jfmartinz/ResourceHub#615]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/95470604/dbf5c01a-2152-41e7-ae7f-4df306519e53)

**Comment by jfmartinz** [comment]
issue resolved
