### ISSUE TITLE
💡 [FEATURE] - Scroll to top Button

### ISSUE THREAD

**Issue by zalabhavy** [jfmartinz/ResourceHub#621]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to make button that will help to reach top of website

### Explain your solution

To save time scrolling up, I'll create a button and use JavaScript to provide this functionality. 
I will use this : window.onscroll = function() {scrollFunction()};
![image](https://github.com/jfmartinz/ResourceHub/assets/126322584/72b2db29-f834-43dc-ad4f-3a2f584ba3b7)

**Comment by zalabhavy** [comment]
@jfmartinz can you please add level2 it is hard and takes time please 🥺.

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24.
