### ISSUE TITLE
💡 [FEATURE] -  Rust Resources added.

### ISSUE THREAD

**Issue by Pujan-sarkar** [jfmartinz/ResourceHub#623]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by Pujan-sarkar** [comment]
@jfmartinz can you assign this issue to me... I can't understand what github-actions are saying?

**Comment by Pujan-sarkar** [comment]
@jfmartinz please reply sir

**Comment by Pujan-sarkar** [comment]
@jfmartinz  please reply / or assign this issue or do something about this .....

**Comment by Pujan-sarkar** [comment]
@jfmartinz  you are not replying so that means will i close this issue ?

**Comment by jfmartinz** [comment]
you can work on this issue, if you still wants to

**Comment by Pujan-sarkar** [comment]
No I will work on another issue
