### ISSUE TITLE
🐞 [BUG] - Domain names are overflowing from the container

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#631]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

When i scroll down then i see that some of the domain names are overflowing from the card .
![Screenshot 2024-05-31 093719](https://github.com/jfmartinz/ResourceHub/assets/118350936/bea057d2-85d8-4d47-b472-c8eabf9ecdea)

### Expected behavior

The names must be fitted properly in the card .

**Comment by jfmartinz** [comment]
This issue is duplicate
