### ISSUE TITLE
💡 [FEATURE] - <To add Operating System in the resources>

### ISSUE THREAD

**Issue by ayush-848** [jfmartinz/ResourceHub#635]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Well, I want to add Operating Systems in the resources.

### Additional Context

I will also provide the documentation for it

**Comment by jfmartinz** [comment]
Sorry @ayush-848 but I am not accepting more category in the moment. Maybe you could add resources or new section in existing categories?

**Comment by ayush-848** [comment]
@jfmartinz okk, sure
