### ISSUE TITLE
 [Update] - Carousel cards

### ISSUE THREAD

**Issue by adarsh0011** [jfmartinz/ResourceHub#637]
### Idea Contribution

- [ ] Label this issue under gssoc & level 2

### Explain feature request

The cards displayed on the website don't have proper width.
![Screenshot (504)](https://github.com/jfmartinz/ResourceHub/assets/113614601/ef091784-6316-47dd-bc28-d11753929c72)

### Explain your solution

It can be resolved by adding extra padding to the cards.

**Comment by nishant0708** [comment]
Hey can i work on this issue

**Comment by jfmartinz** [comment]
Can you please tell me more about waht you want to do?

**Comment by adarsh0011** [comment]
> Can you please tell me more about waht you want to do?

Example : programming languages the text are coming out of cards hence the cards aren't provided with enough of the padding that looks odd.

I would like to fix like DevOps one properly aligned at the center and if you want i can add sliding carousel cards.

**Comment by nehal1222** [comment]
![Screenshot 2024-06-01 114350](https://github.com/jfmartinz/ResourceHub/assets/119063830/02d87ac2-1e18-4ef6-9e99-7dbd19d9c081)
![image](https://github.com/jfmartinz/ResourceHub/assets/119063830/518ae786-09ad-4caf-9d4b-721ce861413b)

I would like to form the carousel card like the above examples

**Comment by jfmartinz** [comment]
> ### Idea Contribution
> * [ ]  Label this issue under gssoc & level 2
> 
> ### Explain feature request
> The cards displayed on the website don't have proper width. ![Screenshot (504)](https://private-user-images.githubusercontent.com/113614601/335471634-ef091784-6316-47dd-bc28-d11753929c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNzUzOTcsIm5iZiI6MTcxNzM3NTA5NywicGF0aCI6Ii8xMTM2MTQ2MDEvMzM1NDcxNjM0LWVmMDkxNzg0LTYzMTYtNDdkZC1iYzI4LWQxMTc1MzkyOWM3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMDM4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDhmZDM5NmZmMGIyODIzYzA2ZTcwYTA4ZjIzYjY2MDVmMjk4NTVmZmM0MGJmMTBhNTNiN2RmNWFjYmVkM2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yllGyrSZsXPepfCSLUMmXTqXW90oP3cga7UZ5woLx1g)
> 
> ### Explain your solution
> It can be resolved by adding extra padding to the cards.
> 
> ### Any alternative approaches/features
> _No response_
> 
> ### Additional Context
> _No response_

maybe you can add carousel in the testimonial.

**Comment by jfmartinz** [comment]
no need to add carousel in the categories
