### ISSUE TITLE
🐞 [BUG] - Hamburger icon visible in large screens.

### ISSUE THREAD

**Issue by nagalakshmi08** [jfmartinz/ResourceHub#643]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The hamburger is being visible on large screens.
![image](https://github.com/jfmartinz/ResourceHub/assets/121669832/47a9fb03-44ba-4505-afa2-c645272cb412)

### Expected behavior

The hamburger icon is to display menu on small screens

### Steps to reproduce

Change the styling and conditions of hamburger to make sure that it is visible only on small screens.

### Additional Context

Please assign me this issue, I would like to contribute to this project under GSSoC'24.

**Comment by jfmartinz** [comment]
I think someone is already working on this issue.
