### ISSUE TITLE
DOC: Adding GSSOC'24 banner in README.md

### ISSUE THREAD

**Issue by Maheshwari-Love** [jfmartinz/ResourceHub#654]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

It is a suggestion to add GSSoc banner in the bottom of the README.md file

### Explain your solution

The GSSoc banner is missing 
Go to Readme.md file
The gssoc'24 banner can be added

**Comment by jfmartinz** [comment]
Where do you want to add it?

**Comment by Maheshwari-Love** [comment]
In README. Md file at the bottom

**Comment by jfmartinz** [comment]
you can add it after the technologies
