### ISSUE TITLE
🐞 [BUG] - Adding backtotop icon to the main web page

### ISSUE THREAD

**Issue by SuhainaFathimaM** [jfmartinz/ResourceHub#656]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

Adding back to top icon will help in quick navigation from bottom of the page to top

### Additional Context

@jfmartinz I would like to work on this issue

**Comment by jfmartinz** [comment]
duplicate
