### ISSUE TITLE
🐞 [BUG] -Text in cards are not visible

### ISSUE THREAD

**Issue by SuhainaFathimaM** [jfmartinz/ResourceHub#657]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/153417476/5727aebd-b7d0-4791-9093-9351ee382627)

### Additional Context

@jfmartinz I would like to work on this issue

**Comment by jfmartinz** [comment]
Duplicate
