### ISSUE TITLE
🐞 [BUG] - Footer contents are not visible

### ISSUE THREAD

**Issue by SuhainaFathimaM** [jfmartinz/ResourceHub#658]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/153417476/ba95593a-dcac-47ba-aea9-72cd788069b3)

### Additional Context

@jfmartinz I would like to work on this issue

**Comment by jfmartinz** [comment]
duplicate
