### ISSUE TITLE
Headings in footer are not visible in light mode 

### ISSUE THREAD

**Issue by meghana9044** [jfmartinz/ResourceHub#660]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I see a issue that headings in the footer such as Resources, Platforms and Course Platforms are not visible in light mode.
<img width="1440" alt="Screen Shot 2024-05-31 at 8 49 56 PM" src="https://github.com/jfmartinz/ResourceHub/assets/105973009/de2ea9f1-0af6-4531-abc4-b01482c036c3">

### Explain your solution

I will change the font color to white from black

**Comment by jfmartinz** [comment]
issue resolved
