### ISSUE TITLE
Content in the testimonial section are invisible in light mode

### ISSUE THREAD

**Issue by meghana9044** [jfmartinz/ResourceHub#662]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The users of this website won't be able to read the content from testimonials section
<img width="1440" alt="Screen Shot 2024-05-31 at 8 53 02 PM" src="https://github.com/jfmartinz/ResourceHub/assets/105973009/9128984b-cc60-457a-aafa-f90c1d3a11b4">

### Explain your solution

I will change the font colot to white from black

**Comment by jfmartinz** [comment]
duplicate issue
