### ISSUE TITLE
🐞 [BUG] - in light mode View Enhancement

### ISSUE THREAD

**Issue by Yashgabani845** [jfmartinz/ResourceHub#671]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

i am expecting 4 chnages in light mode every changes either adding enhancement or much needed 

1.  logo is not visible in light-mode (much needed)
2. enhace dark-mode toggler i will add icons of sun and moon to it more attarctive
3. white button with this tyle is not looking go i will enhance it and make it black and more beautiful
4. font of course cards are dull
5. reviews are still in black colour text

![Screenshot (269)](https://github.com/jfmartinz/ResourceHub/assets/127788321/b1e36005-a4cc-41ad-a97b-3bdd5bb142e7)

![Screenshot (268)](https://github.com/jfmartinz/ResourceHub/assets/127788321/0ad0f804-b2e0-4773-a35f-16c06d2e06e2)

![Screenshot (264)_LI](https://github.com/jfmartinz/ResourceHub/assets/127788321/1a89e94e-ea61-47f8-b97e-dc48d799866b)

### Expected behavior

i think these 4 changes will make light view of the website more beautiful and attractieve

### Steps to reproduce

i will chnage required css and js 

### Additional Context

i will request you to assign me this issue
and also request to make it's label level 3
beacuse i am not making 5 seprate issue for this enhancement it will increse you work

**Comment by Yashgabani845** [comment]
@jfmartinz pleae assign me this issue

**Comment by jfmartinz** [comment]
only Work in 3 and 4 issue. some issuee was resolved

**Comment by Yashgabani845** [comment]
@jfmartinz okay sir
