### ISSUE TITLE
🐞 [BUG] - Navbar changiing behaviour with pages

### ISSUE THREAD

**Issue by Yashgabani845** [jfmartinz/ResourceHub#672]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

in home,contact,service page navarbar is on full top 
but in about page someone has chnages css of navbar so it is adding paddinf top 
so it not consistent
also in about page navbar does not hav any dark mode toggler
![Screenshot (271)_LI](https://github.com/jfmartinz/ResourceHub/assets/127788321/a3e36477-0c73-493e-bd14-cf507e325809)

### Expected behavior

navbar always should be fixed
with same size,same margin , same position
also there should be same options in all of the pages

### Steps to reproduce

i will change css and js as well wherever requires

### Additional Context

please assign me this issue 
i will make sure that other thing won't be affected on my changes 
Thanks you

**Comment by Yashgabani845** [comment]
@jfmartinz  please assign me this issue

**Comment by jfmartinz** [comment]
You can work on the fixed nav

**Comment by Yashgabani845** [comment]
@jf okay sir

**Comment by jf** [comment]
> @jf okay sir

what? not me, please work on fixing your mentions

**Comment by Yashgabani845** [comment]
@jf sorry brother
