### ISSUE TITLE
💡 [FEATURE] - Create Sign In and Sign Up Pages and Add Buttons to Navbar

### ISSUE THREAD

**Issue by AsmitaMishra24** [jfmartinz/ResourceHub#675]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

- The frontend of our website currently lacks a user authentication system.
- Users encounter difficulties accessing personalized features or content due to the absence of sign-in/sign-up functionality.
- This deficiency leads to a suboptimal user experience, potentially resulting in user frustration and decreased engagement.

### Explain your solution

Create Sign In Page:
- Design and develop a user-friendly Sign In page.
- Include form fields for email and password.

Create Sign Up Page:
- Design and develop a user-friendly Sign Up page.
- Include form fields for username, email, password, and confirm password.

Add Navbar Buttons:
- Design "Sign Up" and "Login" buttons to match the website's visual style.
- Integrate the buttons into the navbar for easy access.
- Implement functionality to navigate users to the respective Sign Up and Sign In pages when clicked.

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by jfmartinz** [comment]
We don;t need yet user auth, maybe in the future
