### ISSUE TITLE
💡 [FEATURE] - <title> add logo in title box

### ISSUE THREAD

**Issue by shuhaki** [jfmartinz/ResourceHub#676]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

<img width="207" alt="Screenshot 2024-06-01 at 1 17 44 AM" src="https://github.com/jfmartinz/ResourceHub/assets/145912232/316f8083-8f5f-497a-a322-c8c038ca78e0">

### Explain your solution

add logomin title box

**Comment by jfmartinz** [comment]
the issue was resolved
