### ISSUE TITLE
🐞 [BUG] - Uneven size of the Testimonials cards

### ISSUE THREAD

**Issue by shreya-paul-17** [jfmartinz/ResourceHub#678]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In the Testimonials sections the cards are not having equal size. Thus, the cards are looking irregular. Basically the cards size has got dependent on the amount of text it has. Thus the  marked containers have become smaller in size (as shown in the screenshot below)

Here is an attached screenshot:
![resource-hub-3](https://github.com/jfmartinz/ResourceHub/assets/135226069/e290985d-5a9d-4d0f-bacf-fefd5ae1070d)

### Expected behavior

All the cards size needs of equal size.

### Steps to reproduce

NA

### Additional Context

NA

**Comment by shreya-paul-17** [comment]
@jfmartinz Could you please assign me this task?

**Comment by jfmartinz** [comment]
the issue was sresolved
