### ISSUE TITLE
🐞 [BUG] - <title> toggle-navbar hiding for big screen size and enabling for for small screen size

### ISSUE THREAD

**Issue by Damini2004** [jfmartinz/ResourceHub#680]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/119414762/e3e9fd27-30c5-409c-9e14-fd575d57708f)
hiding the toggle-navbar as it is no use in Big screen size as it maily work for small screen size.
I will be beneficial for you website enhancement to hiding the toggle-navbar as they doesn't contribute in big screen size.

### Expected behavior

![image](https://github.com/jfmartinz/ResourceHub/assets/119414762/f8b24ce9-52b9-44ce-b26f-b681ddb86cfb)
It will be show like this...

### Steps to reproduce

Just will adjust it with screen size.

### Additional Context

Kinldy assign this issue to me in order to enhance website display assign it with proper gssoc label and levels.

**Comment by jfmartinz** [comment]
The issue was resolved
