### ISSUE TITLE
🐞 [BUG] - 3 lines icon in Navbar

### ISSUE THREAD

**Issue by HK853** [jfmartinz/ResourceHub#682]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/113816862/1dcc4871-b34a-4b65-862d-0741ba09eff0)
In Navbar we can not add 3 lines icon at desktop screen.
At the time of Collapsing the icon should be visible other wise display should be none.

### Steps to reproduce

display none for laptop screen size and at the time of collapsing the screen we display block to that icon

**Comment by jfmartinz** [comment]
the issue was resolved
