### ISSUE TITLE
💡 [FEATURE] - Adding jump to top arrow button

### ISSUE THREAD

**Issue by harinisayani** [jfmartinz/ResourceHub#686]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I observed that their is no jump to top arrow button so I want to add it. 

### Additional Context

I want to work on this issue.
Please assign me this issue.

**Comment by jfmartinz** [comment]
The issue is resolved
