### ISSUE TITLE
💡 [FEATURE] - Text alignment properly

### ISSUE THREAD

**Issue by harinisayani** [jfmartinz/ResourceHub#687]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

![Screenshot (9)](https://github.com/jfmartinz/ResourceHub/assets/143276011/3b7c9fa7-1a23-4e7a-a3d4-1a0a0a3923ac)

### Explain your solution

I want to align the text properly

### Additional Context

I want to work on this issue.
Please assign me this issue.

**Comment by tikaram1912** [comment]
Hello, I'm interested in working on this issue. Please assign it to me.

**Comment by jfmartinz** [comment]
What do you man asslign? you mean the text overflow?

**Comment by jfmartinz** [comment]
Dis is duplicate issue
