### ISSUE TITLE
🐞 [BUG] - text at hamburger menu is not visible in bright mode

### ISSUE THREAD

**Issue by SuhainaFathimaM** [jfmartinz/ResourceHub#691]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/153417476/8b98a74e-1515-4332-a549-f0e87266ee2e)

Menu at the hamburger is not visible

### Additional Context

@jfmartinz I would like to contribute under GSSoC

**Comment by SuhainaFathimaM** [comment]
@jfmartinz I would like to contribute under GSSoC

**Comment by jfmartinz** [comment]
The issue was resolved
