### ISSUE TITLE
💡 [FEATURE] - Changing logo 

### ISSUE THREAD

**Issue by harinisayani** [jfmartinz/ResourceHub#694]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to change the logo.
Because when we are applying toggle button the logo is not visible.

### Explain your solution

By changing logo we can able see the logo properly

**Comment by ananyag309** [comment]
Hello, I'm interested in working on this issue. Please assign it to me.

**Comment by jfmartinz** [comment]
Duplicate issue
