### ISSUE TITLE
💡 [FEATURE] - [adding contact page for the website]

### ISSUE THREAD

**Issue by manikumarreddyu** [jfmartinz/ResourceHub#698]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

this website doesnot have contact page

### Explain your solution

i want to add responsive contact page for this website

<img width="811" alt="image" src="https://github.com/jfmartinz/ResourceHub/assets/133508962/4275749c-5b9b-40b7-97c4-12735135e3d8">

**Comment by manikumarreddyu** [comment]
Please assign me this issue under GSSOC'24

**Comment by ananyag309** [comment]
Hello, I'm interested in working on this issue. Please assign it to me.

**Comment by jfmartinz** [comment]
Duplicate issue
