### ISSUE TITLE
Categorize the table for Tutorial or Courses

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#70]
Categorize the resources in `tutorials or courses`  section into different section: Front End, Back End, and Full Stack Development for improved user navigation. You can access the section [here](https://github.com/jfmartinz/ResourceHub/blob/main/Web%20Development/README.md#tutorials-or-courses)

Use this template for creating the table:

```bash
<table width="100%">
      <tr>
        <th>Resource Name</th>
        <th>Description</th>
      </tr>
    <tr>
         <td>Resource Name 1</td>
         <td>Description</td>
    </tr>

</table>
```

Something like this:
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/325abf80-6802-4dd9-8623-915d158d90da)
Notes: Use h4 to the headings

**Comment by Karan-Palan** [comment]
I'd like to work on this issue, please assign it to me

**Comment by ayushsgithub** [comment]
Hey @jfmartinz, can you please assign this to me, I would love to work on this issue.

**Comment by jfmartinz** [comment]
Assign to you. GOodluck

**Comment by Karan-Palan** [comment]
@jfmartinz please add the hacktoberfest-accepted labels to the closed PRs(just a sugesstion)

**Comment by jfmartinz** [comment]
> @jfmartinz please add the hacktoberfest-accepted labels to the closed PRs(just a sugesstion)

Done. thanks
