### ISSUE TITLE
🐞 [BUG] - Issues in light mode

### ISSUE THREAD

**Issue by Shivanipandey31** [jfmartinz/ResourceHub#701]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In the light mode ,the color of testimonials is black and the text written inside the testimonials is also black and that's why the text is not visible at all.

![Screenshot 2024-06-01 134409](https://github.com/jfmartinz/ResourceHub/assets/142419781/c1b957c7-66fa-4916-aad4-a56a769eabfe)

### Expected behavior

I think the color of the text written should be white and we can try a different color for the box, I think that will look better.

**Comment by Yashgabani845** [comment]
already raised it before in #671 
please close it
