### ISSUE TITLE
🐞 [BUG] -  Card is not in the size of text wgich is wiitten

### ISSUE THREAD

**Issue by Gamerking177** [jfmartinz/ResourceHub#703]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/130808542/a4a664b9-1dde-4b60-bf9b-2c332e19ef24)

**Comment by jfmartinz** [comment]
Duplicate issue
