### ISSUE TITLE
💡 [FEATURE] - Enhance Testimonals Section

### ISSUE THREAD

**Issue by Hemashree21** [jfmartinz/ResourceHub#704]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The current testimonals section displays all the user reviews taking up unnecessary space. I want to work on making it in a slider view so that when the section is scrolled, the next user review appears. I will also make it responsive across all devices.

![image](https://github.com/jfmartinz/ResourceHub/assets/138188163/867719e8-5692-4fff-85c1-d4c1caf29a48)

![Screenshot 2024-06-01 110647](https://github.com/jfmartinz/ResourceHub/assets/138188163/fecbd7e0-ceac-4f11-adf3-54f0c3dedd0e)

@jfmartinz can you please assign this issue to me?

**Comment by jfmartinz** [comment]
#644 duplicate issue
