### ISSUE TITLE
Categorizing Community Section Resources

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#71]
Currently the community section within our web development platform lacks proper organization and categorization. Your task is to categorize the resources in the community section into distinct tables to enhance user experience and accessibility. The primary categories for resource classification are as follows:

- **Twitter**: 
- **Facebook Groups**: 
- **Reddit**: 
- **Discord**: 
- **Website**: 

You can access the community section [here](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#communities)

use this template for creating the tables:

```bash
<table width="100%">
      <tr>
        <th>Resource Name</th>
        <th>Description</th>
      </tr>
    <tr>
         <td>Resource Name 1</td>
         <td>Description</td>
    </tr>

</table>
```

Expected output: (Add the other tables for discord and website) 
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/e1fc9730-d255-494f-a991-054097833ece)

Notes: Use h4 to the headings

**Comment by Karan-Palan** [comment]
I'd like to work on this issue, please assign it to me

**Comment by Karan-Palan** [comment]
@jfmartinz  I made the desired changes. Tell me what else can be improved in this
