### ISSUE TITLE
💡 [`BACK TO TOP ` ] - <Adding a back to top button>

### ISSUE THREAD

**Issue by Ketanop321** [jfmartinz/ResourceHub#712]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding a back to top button on the bottom of the home page ,In an effort to improve user experience on our website.

**Comment by jfmartinz** [comment]
This issue is duplicate
