### ISSUE TITLE
💡 [FEATURE] - <`BACK TO TOP BUTTON`>

### ISSUE THREAD

**Issue by Ketanop321** [jfmartinz/ResourceHub#713]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding a back to  top button on bottom of the web page

### Explain your solution

In an effort to improve user experience on our website,  "Back to Top" button. This feature will enhance navigation, especially on pages with extensive content, by allowing users to quickly return to the top of the page with a single click.

### Any alternative approaches/features

Back to top button

### Additional Context

It will increase user experience

**Comment by tikaram1912** [comment]
Hello, I'm interested in working on this issue. Please assign it to me.

**Comment by jfmartinz** [comment]
duplicate issue #699
