### ISSUE TITLE
💡 [FEATURE] - Adding About Section 

### ISSUE THREAD

**Issue by aasthakourav20** [jfmartinz/ResourceHub#716]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to enhance About section by adding the descriptive parts of the projects, what the project  is  & what it offers to the users .

**Comment by ananyag309** [comment]
Hello, I'm interested in working on this issue. Please assign it to me.

**Comment by jfmartinz** [comment]
This is duplicate issue
