### ISSUE TITLE
💡 [FEATURE] - Adding Contact Section 

### ISSUE THREAD

**Issue by aasthakourav20** [jfmartinz/ResourceHub#718]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to add Contact section that will help users to get in touch with the project/website maintainer & add feedback form to it 
Kindly assign this issue to me under GSSoC'24

**Comment by tikaram1912** [comment]
Hello, I'm interested in working on this issue. Please assign it to me.

**Comment by jfmartinz** [comment]
this guy raised the issue first:
 https://github.com/jfmartinz/ResourceHub/issues/698
