### ISSUE TITLE
Join Us for Hacktoberfest 2023!

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#72]
🌟 Welcome to Hacktoberfest 2023! 🌟

Calling all developers, coders, and open-source enthusiasts! We're excited to invite you to participate in this year's Hacktoberfest and contribute to our project. Whether you're a seasoned pro or just getting started, there's a place for you here.

**Comment by Karan-Palan** [comment]
I'd love to contribute

**Comment by jfmartinz** [comment]
> I'd love to contribute

Take a look at these  issues:

#71 
#70

**Comment by Karan-Palan** [comment]
Sure

**Comment by Archie200** [comment]
I would love to contribute @jfmartinz

**Comment by jfmartinz** [comment]
> I would love to contribute @jfmartinz

Sorry for the late reply. You can look at this issue #76.

**Comment by TW-Tribe** [comment]
Sorry for joining late. We would love to help with requirements on technical documentation, API documentation, Developer documentation, technical content writing, and website content writing.

**Comment by jfmartinz** [comment]
> Sorry for joining late. We would love to help with requirements on technical documentation, API documentation, Developer documentation, technical content writing, and website content writing.

Hello @TW-Tribe thank you for the interest contributing on this project. Currently the project is lacking resources and providing some resources would be helpful either in [ui & ux design](https://github.com/jfmartinz/ResourceHub/tree/main/UI-UX%20Design) or [web development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development). Or if you have suggestions or ideas for the project's improvement would be good also. 

Check [contributing.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) for more information. THanks

**Comment by chemicalsculptor** [comment]
Hello, are there any issues that I can work on?

**Comment by jfmartinz** [comment]
> Hello, are there any issues that I can work on?

You can work on this issue #104. If you want to work on it just comment so I can assign you. Thanks

**Comment by chemicalsculptor** [comment]
I'm actually looking for codes to contribute with HTML and CSS
