### ISSUE TITLE
🐞 [BUG] - Color distortion on light mode toggle

### ISSUE THREAD

**Issue by aasthakourav20** [jfmartinz/ResourceHub#720]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In case of Light mode all the colors got distorted 
Kindly assign this issue to me under GSSoC'24

![Screenshot (265)](https://github.com/jfmartinz/ResourceHub/assets/148269962/1875c065-d9dd-43f9-96dc-7aa3f057e3a0)

**Comment by jfmartinz** [comment]
The issue was resolved.
