### ISSUE TITLE
💡 [FEATURE] - Programming Language "Swift" Resources

### ISSUE THREAD

**Issue by aasthakourav20** [jfmartinz/ResourceHub#721]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by aditya1492025** [comment]
I can curate a collection of high-quality tutorials, documentation, and other learning materials that will be beneficial for both beginners and experienced developers.

Could you please assign this issue to me? I am excited to start working on it and provide valuable resources for the community.

Thank you!

**Comment by jfmartinz** [comment]
Swift is already exist in the project. Check [this](https://github.com/jfmartinz/ResourceHub/tree/main/Programming%20Languages/Swift)
