### ISSUE TITLE
🐞 [BUG] - items are not properly contained in the boxes

### ISSUE THREAD

**Issue by Rupalpy** [jfmartinz/ResourceHub#728]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

items are not properly contained in the boxes. Looks awful.
![Screenshot_20240602_122129](https://github.com/jfmartinz/ResourceHub/assets/121295967/5e40f2ba-5a66-4e1b-a900-0510b44c4fae)

**Comment by jfmartinz** [comment]
You mean the text oeverflow?

**Comment by jfmartinz** [comment]
Duuplicate issue
