### ISSUE TITLE
🐞 [BUG] - no use of the icon in the navbar

### ISSUE THREAD

**Issue by Rupalpy** [jfmartinz/ResourceHub#729]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

An
![Screenshot_20240602_122444](https://github.com/jfmartinz/ResourceHub/assets/121295967/921dcce7-9f10-4573-bd9a-7976e50d5dca)
![Screenshot_20240602_122453](https://github.com/jfmartinz/ResourceHub/assets/121295967/2cd4241e-5798-484c-b608-f8d991714fd0)
 icon at the right side of navbar is of no use , has no functionality in it , either add something to it or remove it.

**Comment by jfmartinz** [comment]
This is duplicate issue, the issue was solved
