### ISSUE TITLE
💡 [FEATURE] - missing favicon logo in about page

### ISSUE THREAD

**Issue by jayanththalla** [jfmartinz/ResourceHub#730]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

missing logo in  the about page and enhance the footer  

### Explain your solution

add a logo resourceshub logo to the about page and the enhance the footer by remove the text decoration underline and align the resources in the footer.

### Additional Context

please assign me @pa

**Comment by Gokilp** [comment]
please assign the issue to me

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
