### ISSUE TITLE
💡 [FEATURE] - Addition of resources to C, Java, Python and C++

### ISSUE THREAD

**Issue by samarpitadas** [jfmartinz/ResourceHub#732]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

There are some more resources I would like to add to C, Java, Python and C++.

### Explain your solution

Here is what I would like to add:

## Java :

- A free certification course in my knowledge.

## C:

- Interview Preparation links
- A free certification in my knowledge

## C++:

- Interview Preparation links
 
## Python:

- Projects(Beginner, Medium and Hard)
- Interview Preparation links

**Comment by tikaram1912** [comment]
hey @jfmartinz ,I want to work on this issue please assign issue to me as GSSOC'24 contributor.
