### ISSUE TITLE
🐞 [BUG] - No contact page 

### ISSUE THREAD

**Issue by isandhyadev** [jfmartinz/ResourceHub#738]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

While clicking to contact page no contact page found.

### Steps to reproduce

navbar then click on contact

**Comment by tikaram1912** [comment]
Describe the bug: While clicking to contact page no contact page found.
Can you assign this issue to me. I want to work on it under GSSoC'24.

**Comment by jfmartinz** [comment]
Duplicate issue
