### ISSUE TITLE
💡 [FEATURE] - <add Cyber security Section>

### ISSUE THREAD

**Issue by Vipullakum007** [jfmartinz/ResourceHub#744]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

- As cyber security is one of the most important and demanding field nowadays so, it is important to have a section for cyber security.
- This section includes mind-map, tools, repo, article, web-resources, yt video and much more.

### Explain your solution

- As cyber security is one of the most important and demanding field nowadays so, it is important to have a section for cyber security.
- This section includes mind-map, tools, repo, article, web-resources, yt video and much more.

**Comment by Vipullakum007** [comment]
hey @jfmartinz , please assign issue to me as GSSOC'24 contributor.

**Comment by tikaram1912** [comment]
hey @jfmartinz ,I want to work on this issue please assign issue to me as GSSOC'24 contributor.

**Comment by jfmartinz** [comment]
I will not add more category for now. Some category needed some resources and issues to fixed before adding another category or domain
