### ISSUE TITLE
💡 [FEATURE] - Adding a section about Git and GitHub

### ISSUE THREAD

**Issue by MIpaltan007** [jfmartinz/ResourceHub#745]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

A section dedicated to Git and GitHub. Everything about Git, its commands and how GitHub is used in today's world as a technology.

### Explain your solution

A list of all Git commands, basically a Git cheat-sheet will be provided. Introduction to GitHub, its uses and how it is valuable to a developer.

**Comment by tikaram1912** [comment]
I want to work on this issue, please assign it to me under GSSoC'24.

**Comment by MIpaltan007** [comment]
@jfmartinz I have created this Issue. So I can work on this. Assign me this one. I have added some good resources before, and will continue adding them .

**Comment by jfmartinz** [comment]
I think no need to add this for now
