### ISSUE TITLE
💡 [FEATURE] - <Add Contact page>

### ISSUE THREAD

**Issue by HimangshuRanjan** [jfmartinz/ResourceHub#746]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to add contact page to the website as there is no contact section, with better UI/UX please assign me this issue under GSSOC'24.

**Comment by jfmartinz** [comment]
Duplicate issue
