### ISSUE TITLE
🐞 [BUG] - <Responsiveness of the website>

### ISSUE THREAD

**Issue by tikaram1912** [jfmartinz/ResourceHub#749]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

This website is not completely responsive.
![Screenshot (305)](https://github.com/jfmartinz/ResourceHub/assets/123519180/4cb9d9e5-fa6c-4893-b085-2906c749cc50)

### Expected behavior

I can update this website into fully responsible for all devices.

**Comment by jfmartinz** [comment]
Duplicate issue. Please take a look at related issues
