### ISSUE TITLE
🐞 [BUG] - <Add about page>

### ISSUE THREAD

**Issue by tikaram1912** [jfmartinz/ResourceHub#750]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In this website , there is a blank about section.

### Expected behavior

I can add about section for this website so Please assign this issue to me under GSSoC'24.

**Comment by jfmartinz** [comment]
Duplicate issue
