### ISSUE TITLE
💡 [FEATURE] - Add DSA Projects

### ISSUE THREAD

**Issue by ImmidiSivani** [jfmartinz/ResourceHub#759]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

DSA is most important skills were every computer science student should know. Creating projects will provide better  understanding in Data Structures.

### Explain your solution

I want to add "Projects" section in DSA, I will add tutorials of following projects
1. Snake Game
2. Sudoko Solver
3. Sorting Visualizer
4. File Zipper

**Comment by jfmartinz** [comment]
Is this really a project for DSA?

**Comment by ImmidiSivani** [comment]
@jfmartin For the above projects  code  we can use  linked list ,bubble sort ,queues etc . I will provide the tutorials to the above projects where  data structures  implementation are used.

**Comment by jfmartinz** [comment]
I think you can the algorithms for each programming language how is that algo used in that specific language. Add at least 3 prog language and give also 3 algo for that languages. 

For example, in JS. QuickSort in JS, something like that. 

Please refer to CONTRIBUTING.md for more information on how to create the table or format.


### Algorithms by Language
#### JavaScript
Algorithm 1
Algorithm 2
