### ISSUE TITLE
Categorize Web Development Tools

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#76]
To organize and improve the accessibility of our web development resources, we are looking for contributions to categorize the tools listed in web development [tool section](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#tools). This will make it easier for users to find the specific tools they need based on their area of interest.

Use this template for creating the table:

```bash
<table width="100%">
      <tr>
        <th>Resource Name</th>
        <th>Description</th>
      </tr>
    <tr>
         <td>Resource Name 1</td>
         <td>Description</td>
    </tr>

</table>
```
> Notes: Use h4 to the headings

Something like this:
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/9e136a52-9a4e-4968-af68-d8f19e45480d)

Check this example in [communities section](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#communities)

The categories you should add:

- Typography
   - Fontpair
- Colors
  - Palletemaker
  - Realtime Colors 
- CSS Generators
   - CSS Portal
   - Fancy Border Radius Generator
   - Glassmorphism CSS Generator
   - Neumorphism.io 
   - CSS Gradient Generator
   - Buttons Generator
   - CSS Grid Generator
- Icons
   - Boxicons 
- CSS animation
  - Animista
- Code Playgrounds
   - Codepen 
- Chrome extenstion
   - Pesticide for Chrome
- Stock Photos & Videos
- SVGs
  - SVG Viewer
  - Hero Patterns
  - SVG Backgrounds
  - Haikei 
- Others
  - OVER API

**Comment by Karan-Palan** [comment]
I'd like to work on this issue, Kindly assign this to me!

**Comment by jfmartinz** [comment]
Assign to you @Karan-Palan  since youre the first time comment to the issue. Goodluck! If you have any clarification just ask.

**Comment by Karan-Palan** [comment]
Thanks for assigning me!

**Comment by Karan-Palan** [comment]
@jfmartinz , I have made the desired changes.
