### ISSUE TITLE
💡 [FEATURE] Adding Login/Sign page

### ISSUE THREAD

**Issue by Maheshwari-Love** [jfmartinz/ResourceHub#764]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

There is no Login/SignUp page in this project I can add the login/signup page to authenticate users.

### Any alternative approaches/features

Some what like this
![image](https://github.com/jfmartinz/ResourceHub/assets/142833275/f3895591-ec8c-4b4b-be07-035979455412)

![image](https://github.com/jfmartinz/ResourceHub/assets/142833275/ed0719a9-b34d-418c-8ad4-e30a26aa0e35)

**Comment by Maheshwari-Love** [comment]
@jfmartinz can you assign me this issue with appropriate labels

**Comment by jfmartinz** [comment]
This is nto needed at the moment
