### ISSUE TITLE
🐞 [BUG] - <title> Fixing the card as text getting outside of the box

### ISSUE THREAD

**Issue by agastya3636** [jfmartinz/ResourceHub#769]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/124435030/9f13abe1-f3d3-4196-aba3-2aa4c40abdf4)

Fixing the card as text getting outside of the box

### Expected behavior

text should be inside the box

**Comment by jfmartinz** [comment]
issue is duplicate
