### ISSUE TITLE
🐞 [BUG] - The DSA section is going out of the BOX

### ISSUE THREAD

**Issue by MuraliDharan7** [jfmartinz/ResourceHub#773]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In the resource section the DSA text is going out of the box.

### Expected behavior

The text should be within the box or the layout,

### Additional Context

![image](https://github.com/jfmartinz/ResourceHub/assets/130668745/549389e3-b6b6-4563-96a5-fe5ae5b4efa2)

Please assign this issue me under GSSoC'24.

**Comment by jfmartinz** [comment]
Duplicate issue
