### ISSUE TITLE
💡 [FEATURE] - Adding Pages for the headers

### ISSUE THREAD

**Issue by MuraliDharan7** [jfmartinz/ResourceHub#775]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want the add the desired pages for the headers below
![image](https://github.com/jfmartinz/ResourceHub/assets/130668745/12e05eaa-412c-46a9-9cfd-d8cb0ae1cda1)

### Explain your solution

I can add pages for home and for services I can include the services you do and for contacts as well.

### Additional Context

Please assign this issue me under GSSoC'24.

**Comment by jfmartinz** [comment]
Duplicate
