### ISSUE TITLE
🐞 [BUG] - Large text size of learnings

### ISSUE THREAD

**Issue by kanakmaheshwari3115** [jfmartinz/ResourceHub#776]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The text size in learning section is very large and going out of the border. It disrupts the view of the website .
Hovering functionality does not provide good view too (dark text on dark background in some)

### Expected behavior

The text should be small enough to fit inside the box.

### Steps to reproduce

I will lower the text size, and improve the looks of the website.
Please assign me this issue.

**Comment by kanakmaheshwari3115** [comment]
Please assign me this issue.

**Comment by jfmartinz** [comment]
Duplicate issue
