### ISSUE TITLE
💡 [FEATURE] - ADDING A CONTACT ME PAGE TO THE WEBSITE

### ISSUE THREAD

**Issue by Varsha010101** [jfmartinz/ResourceHub#778]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Currently contact page redirects to home page. Creating a contact me page, it will contain a form which users can fill out. 

### Explain your solution

Save the details of the user to the database. Queries of the user can be saved to the database, Any feedback or suggestion. Their message can be retrieved from the site's database.

### Any alternative approaches/features

![Screenshot 2024-05-31 153519](https://github.com/jfmartinz/ResourceHub/assets/142898488/e8362697-b435-45b0-902d-103fe168bd13)

### Additional Context

Kindly assign me this issue and label it under GSSoC. @jfmartinz

**Comment by jfmartinz** [comment]
Duplicate
