### ISSUE TITLE
Changing alignment  to the css

### ISSUE THREAD

**Issue by SHANMUGAPRIYA-1** [jfmartinz/ResourceHub#780]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

When Start Learning button is clicked there are courses that are listed down. But the alignment of this page and courses listed are not in proper order .Hence I will try best in making it to correct position. So please do assign this task to me.

**Comment by jfmartinz** [comment]
Its working on my end, can you give me a video about the problem youre facing

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
