### ISSUE TITLE
🐞 [BUG] - All available categories not mentioned in the main README.md

### ISSUE THREAD

**Issue by samarpitadas** [jfmartinz/ResourceHub#783]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The main README.md has a section containing available Categories in this project. But it is not up-to-date.
![Screenshot_2024-06-03-17-50-52-157](https://github.com/jfmartinz/ResourceHub/assets/162856568/e5af3262-7b9f-4568-b087-e217981d5694)

### Expected behavior

I would like to update all the categories that have been available so far. I will add the category 'Data Structure and Algorithms', and new sections under Programming language containing all the languages for easy navigation.

**Comment by jfmartinz** [comment]
Okay, you can add the avail languages in the project in the table of contents
