### ISSUE TITLE
🐞 [BUG] - <issue 2 : enhance UI of service page>

### ISSUE THREAD

**Issue by Vipullakum007** [jfmartinz/ResourceHub#785]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

UI of service page is not good , text goes out of boxes

![Screenshot 2024-06-03 073457](https://github.com/jfmartinz/ResourceHub/assets/127659443/43cbcff9-f07c-41b4-a98d-0ad67f65eb49)

### Expected behavior

it should be better . text should be in box

**Comment by Vipullakum007** [comment]
hey @jfmartinz  , please assign this issue to me as GSSOC'24 contributor.

**Comment by jfmartinz** [comment]
duplicate issue
