### ISSUE TITLE
💡 [FEATURE] - Adding a Contact Us page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#788]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I will add a contact us page for the website 

### Explain your solution

I will do this using email js for mailing functionality and will create the contact page of same theme as the website

**Comment by jfmartinz** [comment]
duplicate issue
