### ISSUE TITLE
💡 [FEATURE] - Add About Page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#789]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I will add an about us page for the website 

### Explain your solution

This will help the user to get an abstract view of the website

**Comment by jfmartinz** [comment]
duplicate issue
