### ISSUE TITLE
Add table content for the web development tools

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#79]
To make it easier for people to navigate in the tools section in web development. Your task is to make the table of contents for the tools section for web development. 

- Tools
   - Typography
   - Colors
   - CSS Generators
   - ETC.

Something like this:
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/2cfe51f7-5dba-4b9d-b651-af3ef3370c37)

**Comment by Karan-Palan** [comment]
I'd like to work on it!
