### ISSUE TITLE
Add Data Structures and Algorithms (DSA) Implementations for Each Programming Language

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#796]
Enhance the repository by adding [Data Structures and Algorithms (DSA)](https://github.com/jfmartinz/ResourceHub/tree/main/Data%20Structures%20and%20Algorithm%20(DSA)) implementations for various programming languages. This will provide a comprehensive resource for learning and reference.

Create a new section called "DSA by Language," with each table containing different DSA categories like arrays, linked lists, stacks, queues, trees, graphs, etc.

Each implementation should include:

Common data structures (e.g., arrays, linked lists, stacks, queues, trees, graphs)

**Comment by Pujan-sarkar** [comment]
@jfmartinz I can do it , can you please assign this issue to me under GSSoC'24

**Comment by Ananya-Nair20** [comment]
Hello

I am participating in GSSOC'24. I am interested in resolving this issue Could you please assign this task to me under GSSOC'24 with relevant level labels?

Thank you

**Comment by jfmartinz** [comment]
> @jfmartinz I can do it , can you please assign this issue to me under GSSoC'24

This is the structure
### DSA by Languag
> Description
#### JavaScript
array
string
...
#### C++
#### Java

**Comment by jfmartinz** [comment]
Add atleast 3 prog language

**Comment by Pujan-sarkar** [comment]
@jfmartinz  can I add C++, Java, Python, Javascript under this sections.

**Comment by jfmartinz** [comment]
yes
