### ISSUE TITLE
Documentation Issue Template

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#798]
Implement a new issue template for documentation-related issues. This template will help users provide detailed and structured information about the documentation that needs to be added or improved. The template should include the following fields:

Documentation Area: Specify the area or section of the documentation that needs attention.
Issue Description: Describe the documentation issue or improvement needed.
Relevant Links: Provide any relevant links, if applicable.
Contribution Confirmation: Confirm that you have read the [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) file.

![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/9ce757df-a04c-41e8-a812-75b88753ee50)
Name: 📃Documentation
About: Document issue or enhancement?
Label: documentation

**Comment by Nayanika1402** [comment]
@jfmartinz Kindly assign me this issue.
