### ISSUE TITLE
💡 [FEATURE] - Footer UI can be better

### ISSUE THREAD

**Issue by Heena31** [jfmartinz/ResourceHub#803]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

![image](https://github.com/jfmartinz/ResourceHub/assets/79543358/1d4cae62-9887-4bad-95c7-a634f7b8e5be)

In the footer there is no icon as it looks basic design

### Explain your solution

I can enhance the ui and also can add Icon to give this basic design more attractive

### Additional Context

Kindly Assign this issue to me

**Comment by Heena31** [comment]
@jfmartinz Hello sir! Could you please assign me this issue

**Comment by jfmartinz** [comment]
This is duplicate
