### ISSUE TITLE
💡 Add a Rate Us Option

### ISSUE THREAD

**Issue by sailaja-adapa** [jfmartinz/ResourceHub#806]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

**Comment by jfmartinz** [comment]
How are you going to that? Can you explain more?

**Comment by sailaja-adapa** [comment]
I would like to add rate us option in this way 

![new](https://github.com/jfmartinz/ResourceHub/assets/161804629/6a2a27f2-7502-4562-8f48-d87030fe0961)

I will change everything according to the project background to correctly suit for it

**Comment by jfmartinz** [comment]
I think ill stop assigning people about website issues for now since we're going to change the website UI soon. Maybe you can add it once the website is finished
