### ISSUE TITLE
🐞 [BUG] - Table of Content not visible in light mode 

### ISSUE THREAD

**Issue by Devaki01** [jfmartinz/ResourceHub#809]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

When switched form light to dark mode, the font color of the table of contents does not change in all thee pages.

<img width="959" alt="image" src="https://github.com/jfmartinz/ResourceHub/assets/147143243/352d4150-a75e-4cfe-9fee-2f1d1e0ee9be">

<img width="959" alt="image" src="https://github.com/jfmartinz/ResourceHub/assets/147143243/1c07dd8e-7a66-4790-8b0e-2fd5adc2aa18">
 

### Expected behavior

The font color of text should change when the theme is switched from dark to light.

### Steps to reproduce

Scroll to the second section on the home page.
Select any domain. 

<img width="959" alt="image" src="https://github.com/jfmartinz/ResourceHub/assets/147143243/5c81a9ea-848a-4738-9c86-ef2fc7db5265">

Toggle dark to light mode.

### Additional Context

Can you please assign me this issue under ggsoc'24?

**Comment by jfmartinz** [comment]
I think ill stop assigning people about website issues for now since we're going to change that soon
