### ISSUE TITLE
Lack resources in tools section for web development

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#81]
The tools section of our web development resource repository is currently in need of additional resources. Your task is to add a valuable resources that can be included in the [tools](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#tools) section. 

You can suggest as many resources as you like.

Categories that lack resources:

- Typography
- Colors
- Icons
- Stock Photos & Videos

**Comment by jfmartinz** [comment]
this issue is up for grab

**Comment by Dev-Abhay01** [comment]
please assign me this ...
