### ISSUE TITLE
🐞 [BUG] - Component Overlapping Issue

### ISSUE THREAD

**Issue by the-code-artist** [jfmartinz/ResourceHub#817]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

domain section is not having proper layout and thus "Programming languages" domain is overlapping the "testimonial" heading in other devices due to lack of responsiveness
![image](https://github.com/jfmartinz/ResourceHub/assets/115625321/6d4fa2db-2ddd-400d-854c-454e68339495)

### Expected behavior

proper spacing between the "Programming languages" and "testimonial" heading such that there is no overlapping between the components
![image](https://github.com/jfmartinz/ResourceHub/assets/115625321/0338d7f0-aa51-45b4-86fe-5bbee7cd7777)

### Steps to reproduce

Fix the marginal space between the 2 components

### Additional Context

hey @jfmartinz ..please assign me this issue as GSSOC'24

**Comment by jfmartinz** [comment]
Duplicate issue
