### ISSUE TITLE
Lack resources in tools section for web development

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#82]
The tools section of our web development resource repository is currently in need of additional resources. Your task is to add a valuable resources that can be included in the [tools](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#tools) section. 

You can suggest as many resources as you like.

Categories that lack resources:

- CSS animation
- Chrome Extenstion
- Code Playground

**Comment by RishabhDhawad** [comment]
I would like to work on this issue.

**Comment by jfmartinz** [comment]
> I would like to work on this issue.

Assigned to you.

**Comment by sakshams23** [comment]
Please assign me with this issue I want to contribute.

**Comment by jfmartinz** [comment]
You can check on this issue #81

**Comment by jfmartinz** [comment]
> I would like to work on this issue.

Please make sure that you at least add 1 resource in each category

**Comment by RishabhDhawad** [comment]
> > I would like to work on this issue.
> 
> Please make sure that you at least add 1 resource in each category

Sure, I am adding at least 5 resources minimum in each category mentioned above.

**Comment by sakshams23** [comment]
#87
