### ISSUE TITLE
💡 [FEATURE] - Enhancement of the about page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#828]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

i will enhance the about page according to the website main theme currently IMO about page not looking so good .

### Additional Context

![Screenshot 2024-06-04 125412](https://github.com/jfmartinz/ResourceHub/assets/118350936/b9b6c526-abe6-478e-9ee8-9bf5c3cd1ac9)

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
