### ISSUE TITLE
🐞 [BUG] - Hamburger is Showing In large displays

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#829]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

I've seen that the hamburger is also showing on large displays but in large displays their is no need for hamburger because it doesn't do anything on clicking it 

### Expected behavior

The Hamburger should not be seen in large devices 

### Additional Context

![Screenshot 2024-06-04 125412](https://github.com/jfmartinz/ResourceHub/assets/118350936/5080f36e-fd36-4286-ad35-17ba4cc8b63b)

**Comment by Gokilp** [comment]
please the issue assign to me

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
