### ISSUE TITLE
Lack resources in community section for web development

### ISSUE THREAD

**Issue by jfmartinz** [jfmartinz/ResourceHub#83]
The community section of our web development resource repository is currently in need of additional resources. Your task is to add a valuable resources that can be included in the [communities](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development#facebook-groups) section. 

You can suggest as many resources as you like.

lacking resources:

- Twitter Groups
- Facebook Groups

**Comment by ayushsgithub** [comment]
Hey @jfmartinz, can you assign this to me? I would love to add the global communities I'm part of and learning from.

**Comment by jfmartinz** [comment]
Assign to you. Thanks

> Hey @jfmartinz, can you assign this to me? I would love to add the global communities I'm part of and learning from.

**Comment by Atheke** [comment]
I would also like to add the resources that is free and open source that I am learning from .I am fairly new in contributing and I would need some assistance

**Comment by jfmartinz** [comment]
> I would also like to add the resources that is free and open source that I am learning from .I am fairly new in contributing and I would need some assistance

You add a resources for facebook groups. You can make your pr and mentioed this issue to your pr. THanks
