### ISSUE TITLE
💡 [FEATURE] - Scroll to services on clicking on services .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#830]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I think after clicking on services in navbar so it must scroll bottom to show all services .

### Additional Context

https://github.com/jfmartinz/ResourceHub/assets/118350936/a03d273f-fcd2-4140-9d74-2765ee42000a

**Comment by Gokilp** [comment]
please the issue assign to me

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
