### ISSUE TITLE
💡 [FEATURE] - Feedback form

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#831]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding a feedback form will help us to know the actual need of the website because users will use the website so this provide facility to the users to share their views .

**Comment by Gokilp** [comment]
please issue assign to me

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
