### ISSUE TITLE
🐞 [BUG] - Testimonials Cards overflowing

### ISSUE THREAD

**Issue by DeadAnjali** [jfmartinz/ResourceHub#836]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

**Issue:**
The Testimonials Section on the website is not completely responsive and overflows on narrow devices.

**ScreenShots:**
![image](https://github.com/jfmartinz/ResourceHub/assets/122856861/ea718f55-7d98-4af3-9a0b-8cb40b96ac17)

### Expected behavior

The card size should either be resizable or should not overflow the viewport.

### Steps to reproduce

1. Go to homepage
2. Scroll down to the testimonials section

**Comment by DeadAnjali** [comment]
Kindly assign me this issue

**Comment by jfmartinz** [comment]
We'll add a caraousel for that, ill close htis issue for now
