### ISSUE TITLE
NOT GOOD for mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [jfmartinz/ResourceHub#839]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Not responsive for mobile screen

### Explain your solution

Fix for mobile screen

### Additional Context

![image](https://github.com/jfmartinz/ResourceHub/assets/124615886/a4897d16-a0b7-495b-b5ac-860ad88bde93)
 I would love to fix it to improve the user experince.

**Comment by jfmartinz** [comment]
Duplicate
