### ISSUE TITLE
🐞 [BUG] - <title>their is some error in the css section 

### ISSUE THREAD

**Issue by shivathmikavemula** [jfmartinz/ResourceHub#850]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

their is some error in the css section so I made some changes to it
### Screenshot - after correction
![Screenshot (25)](https://github.com/jfmartinz/ResourceHub/assets/133566953/3991bce1-5ecf-4e2d-aa20-3a1f2a601dbc)

### Expected behavior

error cleared

### Steps to reproduce

![Screenshot (25)](https://github.com/jfmartinz/ResourceHub/assets/133566953/6324dc41-4e13-49d1-929c-3ea34331fb29)

**Comment by jfmartinz** [comment]
What error? Can you explaiin? Please next time don't work on issue if you're not assigned yet.

**Comment by shivathmikavemula** [comment]
The Braces are not arranged in proper manner 
@jfmartinz

**Comment by shivathmikavemula** [comment]
The Braces are not arranged in proper manner 
@jfmartinz

**Comment by jfmartinz** [comment]
This is too simple. Maybe you can work on adding a new resource?
