### ISSUE TITLE
🐞 [BUG] - Overlapping of About and Theme change icon in navbar in computer screen

### ISSUE THREAD

**Issue by vishnuvardhanreddy31** [jfmartinz/ResourceHub#851]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/104411008/e0961335-9371-499e-aef1-a37eba309dc5)

On the computer screen, there is an issue with the overlapping of the "About" link and the Theme Change Icon in the navbar. As seen in the provided screenshot, the "About" link seems to overlap with the Theme Change Icon, resulting in a visual inconsistency.

### Expected behavior

The expected behavior is that the "About" link and the Theme Change Icon should be properly spaced and displayed without any overlapping. The Theme Change Icon should be clearly visible and separated from other navbar elements.

### Steps to reproduce

To fix the overlapping issue between the "About" link and the Theme Change Icon in the navbar on computer screens, first, inspect the navbar elements and identify the conflicting CSS rules. Adjust the margins or padding to create sufficient spacing between the elements. Ensure responsive design principles are applied for consistent layout across different screen sizes. Test the changes thoroughly across various browsers and devices, gathering feedback and iterating as needed. Finally, commit the fixes to the code repository and deploy the updated version to resolve the issue for users.

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
