### ISSUE TITLE
🐞 [BUG] - Footer Section breakdown

### ISSUE THREAD

**Issue by Parth20GitHub** [jfmartinz/ResourceHub#852]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/142086512/eadb71d9-e6ce-45c1-9736-c3d3595f5661)

### Expected behavior

I would improve this section and align them perfectly

### Steps to reproduce

Using CSS

**Comment by Parth20GitHub** [comment]
Please assign me this issue under GSSOC24

**Comment by jfmartinz** [comment]
I think ill stop assigning people about website issues for now since we're going to change the website UI soon
