### ISSUE TITLE
💡 [FEATURE] - preloader

### ISSUE THREAD

**Issue by gangwarsomya** [jfmartinz/ResourceHub#854]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
