### ISSUE TITLE
🐞 [BUG] - Navbar contain the symbol that should get hidden in big screen size

### ISSUE THREAD

**Issue by Damini2004** [jfmartinz/ResourceHub#861]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The elemnet shouldn't be present at the big screen size its get hide

### Expected behavior

If the screen width reach to less than 900px then it should appear.

### Steps to reproduce

Step 1: Add media query to screen size greater then 900px.
Step 2 : Add hidden property to it.

### Additional Context

![image](https://github.com/jfmartinz/ResourceHub/assets/119414762/5d78f85d-9613-4f84-9f34-9538ad9b8b33)

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
