### ISSUE TITLE
🐞 [BUG] - Files unorganised

### ISSUE THREAD

**Issue by hars-21** [jfmartinz/ResourceHub#864]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

There is a clutter of files, that creates a mess for developers. There are many css files and other extra files that are not needed.

### Expected behavior

I can clear some unwanted files and create a clean repo that will enhance workflow and easy to understand for other contributors.

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
