### ISSUE TITLE
💡 [FEATURE] - <title> footer design is not proper

### ISSUE THREAD

**Issue by siddhant-2002** [jfmartinz/ResourceHub#866]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

the footer is not proper 

i would like to work on the footer to style in websites fashion if you assign it to me under gssoc

![image](https://github.com/jfmartinz/ResourceHub/assets/112260375/e7497a1b-788f-4600-b5af-fa7fbe340be2)

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
