### ISSUE TITLE
💡 [FEATURE] - <title>about section styling</title>

### ISSUE THREAD

**Issue by siddhant-2002** [jfmartinz/ResourceHub#867]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

about section styling is not done properly 

I would like to work on the feature if you would assign it to me under gssoc

![image](https://github.com/jfmartinz/ResourceHub/assets/112260375/9a881ad2-16dc-4112-b1d0-fcc4afcc2aaa)

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
