### ISSUE TITLE
💡 [FEATURE]  contact section

### ISSUE THREAD

**Issue by siddhant-2002** [jfmartinz/ResourceHub#868]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

contact section is not created 

i would like to work on contact section if you assign this to me under gssoc

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
