### ISSUE TITLE
Add OOPS concept resource

### ISSUE THREAD

**Issue by Shreesanyog** [jfmartinz/ResourceHub#874]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Currently there is not resource for OOPs ( object oriented programming) .

### Explain your solution

I will add the resource.

**Comment by jfmartinz** [comment]
Where do you want to oadd it?

**Comment by jfmartinz** [comment]
Is this for Java prog language or..?

**Comment by Gokilp** [comment]
please the issue assign to me

**Comment by Shreesanyog** [comment]
@jfmartinz I will write for OOPs in Python

**Comment by Gokilp** [comment]
Thank you mam

**Comment by Shreesanyog** [comment]
@jfmartinz may I know the reason why you didn't assign it to me even if I raised this issue first.

**Comment by Gokilp** [comment]
I will work
