### ISSUE TITLE
💡 [FEATURE] - Scroll to Top feature

### ISSUE THREAD

**Issue by MuraliDharan7** [jfmartinz/ResourceHub#876]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding Scroll to Top button will take us to top of the page. This is going to be a button when you click that you will be brought to the top of the page.

### Explain your solution

This is going to be a button when you click that you will be brought to the top of the page.

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
