### ISSUE TITLE
💡 [FEATURE] - Adding Contact section 

### ISSUE THREAD

**Issue by MuraliDharan7** [jfmartinz/ResourceHub#877]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Adding contact section will get the user to clear their doubts or other related queries with the admin. This is going to have fields like name, field, queries and other things. 

### Explain your solution

Here user need to enter their details and the query they have. These queries will be sent to the admin or the product owner.

### Additional Context

![image](https://github.com/jfmartinz/ResourceHub/assets/130668745/48f5c300-ad8a-40dd-a3e4-65d29c649ad3)

**Comment by Gokilp** [comment]
please assign to me Under Gssoc 24

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
