### ISSUE TITLE
💡 [FEATURE] - Add contact page

### ISSUE THREAD

**Issue by Saimanjari777** [jfmartinz/ResourceHub#884]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

When we click on contact page, it is missing. I would like to add it.
Please assign this task to me @jfmartinz 

### Explain your solution

I want to create a contact page which is consistent with the theme of our website.

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
