### ISSUE TITLE
💡 [FEATURE] - Add "Scala" Programming language Complete Resources

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [jfmartinz/ResourceHub#892]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Scala, a hybrid functional and object-oriented programming language, requires thorough documentation to assist developers in creating scalable and concurrent applications.

### Explain your solution

I propose adding a dedicated section for Scala resources in the programming language documentation.

Contents of Scala/readme.md:

Scala Basics:
- Setting up the Scala environment
- Understanding the Scala syntax
- Core concepts and the Scala REPL

Advanced Scala:
- Functional programming in Scala
- Object-oriented programming in Scala
- Type system and implicits

Scala Tools and Libraries:
- Using the Scala Build Tool (SBT)
- Popular libraries and frameworks (Akka, Play, Spark)
- Testing with ScalaTest and Specs2

Performance and Optimization:
- Optimizing Scala applications
- Best practices for concurrent programming

Deployment:
- Deployment strategies for Scala applications
- Using Docker with Scala
- Continuous integration and delivery

Scala Projects:
- Real-world applications

### Any alternative approaches/features

To enhance the learning experience, include essential resources such as recommended books, YouTube channels, and websites. Additionally, providing a beginner-friendly roadmap can help new developers navigate through the resources step-by-step.

### Additional Context

@jfmartinz Please assign me this issue

**Comment by code-sans** [comment]
Hey I want to do this as my first contribution in Gssoc , please assign me so that I can work on it .

**Comment by jfmartinz** [comment]
> Hey I want to do this as my first contribution in Gssoc , please assign me so that I can work on it .

Hi. I assigned it already. You can read [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) for more information on how to contribute. thanks
