### ISSUE TITLE
💡 [FEATURE] -  Create a custom 404 not found page for your website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [jfmartinz/ResourceHub#895]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

![image](https://github.com/jfmartinz/ResourceHub/assets/125277258/5d969399-59df-49e6-bd97-eb2c69638c3d)

here the page looks like 

### Explain your solution

i can add some gifs or images to show that in a better manner

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks

**Comment by RamakrushnaBiswal** [comment]
@jfmartinz good listen about it can i get figma design template for your website ??
