### ISSUE TITLE
➕ [RESOURCE] - <Login Page>

### ISSUE THREAD

**Issue by Ojas-Arora** [jfmartinz/ResourceHub#905]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

I want to add a login/signup page. Kindly assign this issue to me @jo

### Additional Context

NA

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
This is not needed yet
