### ISSUE TITLE
🐞 [BUG] - <service page content not visible>

### ISSUE THREAD

**Issue by Vipullakum007** [jfmartinz/ResourceHub#907]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

because some reason service page content not visible

https://github.com/jfmartinz/ResourceHub/assets/127659443/219c0a04-17b5-4768-8743-1c3ee4cff5d8

### Expected behavior

it should be visible

**Comment by jfmartinz** [comment]
Hi, currently we're planning the to redesign the website so for now we are not entertaining more issues about the website since we're going to redesign it sooner. Maybe you can work on other issues, thanks
