### ISSUE TITLE
The navbar sections are not clearly visible when scroll down

### ISSUE THREAD

**Issue by Shreesanyog** [jfmartinz/ResourceHub#913]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

Currently the content and navbar sections are overlapping.

### Expected behavior

There should be clear distinction between navbar sections and contents.

### Steps to reproduce

You can see the bug when scroll down on home page.

In the below screenshot home and about tab not visible clearly.

<img width="925" alt="image" src="https://github.com/jfmartinz/ResourceHub/assets/166977453/09eadb31-4d3c-48a8-aa39-db4f13679563">

Please assign this to me

**Comment by SumithThota** [comment]
please asssign me this issue I wnat to work on it as a GSSoC'24 Contributor

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
