### ISSUE TITLE
➕ [RESOURCE] - Add TCL Resources

### ISSUE THREAD

**Issue by Pujan-sarkar** [jfmartinz/ResourceHub#916]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

I want to add tcl resources, New category TCL.

### Provide the URLs of the resources you are adding

Sources:

1. [Tcl/Tk Documentation](https://tcl.tk/doc/)​ ([Tcl Developer Site](https://tcl.tk/doc/))​
2. [Tcl Developer Site](https://www.tcl-lang.org/)​ ([Tcl Lang](https://www.tcl-lang.org/))

### Additional Context

Purpose: Designed for embedding into applications to provide scripting capabilities.
Usage: Commonly used for rapid prototyping, system automation, and more.
Simplicity and Flexibility: Known for its ease of use and adaptability across various applications.

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by Pujan-sarkar** [comment]
@jfmartinz  will you assign this to me?

**Comment by Pujan-sarkar** [comment]
@jfmartinz  will you give a reply ?

**Comment by jfmartinz** [comment]
Late reply. Don;t add this.
