### ISSUE TITLE
💡 [FEATURE] - adding logo in nav bar

### ISSUE THREAD

**Issue by dnyandeepchute** [jfmartinz/ResourceHub#918]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

adding logo in front of home, about, etc in nav bar

### Explain your solution

adding logo in front of home, about, etc in nav bar

### Any alternative approaches/features

using font awesome

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
