### ISSUE TITLE
💡 [FEATURE] - Adding responsive good looking contact page 

### ISSUE THREAD

**Issue by Husan7** [jfmartinz/ResourceHub#920]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Contact page is not working 
I want to add  responsive good looking contact page by which user will contact us.

Desktop mode

![Screenshot 2024-05-16 132432](https://github.com/jfmartinz/ResourceHub/assets/162671639/27678196-601b-49a6-8e9c-a4176bbefb6d)

Mobile Mode

![Screenshot 2024-05-16 132736](https://github.com/jfmartinz/ResourceHub/assets/162671639/a290a972-158f-4bef-823f-d4754148ed39)

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
