### ISSUE TITLE
feat: REVAMP THE HOME PAGE AND ALSO IMPROVE THE VISIBILITY

### ISSUE THREAD

**Issue by AbhinaySngh** [jfmartinz/ResourceHub#922]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

https://github.com/jfmartinz/ResourceHub/assets/162811933/adb618e2-e1f9-4109-879e-3d7a2e12a298

**Comment by AbhinaySngh** [comment]
@jfmartinz Please assign me this issue under GSSOC'24 label 2.

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
