### ISSUE TITLE
💡 [FEATURE] - Add Complete MongoDB resources 

### ISSUE THREAD

**Issue by jayraj175coder** [jfmartinz/ResourceHub#926]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain your solution

I want to add the  mongodb complete resources.

### Additional Context

COuld you assign me @jf

**Comment by jf** [comment]
no

**Comment by jayraj175coder** [comment]
Complete this @jfmartinz , Assign level and merge it.

thanks
