### ISSUE TITLE
🐞 [BUG] - The Div in the testimonial section is not arranged correctly.

### ISSUE THREAD

**Issue by Vibhu315** [jfmartinz/ResourceHub#928]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The Div in the testimonial section is not arranged correctly.The div in the testimonial section extends beyond the screen.

![image](https://github.com/jfmartinz/ResourceHub/assets/93249125/d8cf304e-ad34-4418-8abe-aa626af55b1f)

**Comment by Vibhu315** [comment]
hey @jfmartinz ,I can fix the issue please assign me this issue.

**Comment by Gokilp** [comment]
please assign the issue to me

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
