### ISSUE TITLE
📃 [ENHANCEMENT] - Would like to redesign footer

### ISSUE THREAD

**Issue by CodeXsubham** [jfmartinz/ResourceHub#934]
### Issue Verification

- [X] I have verified that this is a new documentation issue.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Documentation Area📚

![Screenshot 2024-06-07 221139](https://github.com/jfmartinz/ResourceHub/assets/119094596/93d69923-c1ab-48f9-9c39-0b4303dbf21b)
would like to redesign footer

Also Checkout my last Contributions on footer
**1**
![Screenshot 2024-06-04 131435](https://github.com/SUGAM-ARORA/UniCollab/assets/119094596/0a59ead4-6f91-40fc-a254-c3d502be8222)

**2**
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/119094596/d62d8538-10a1-48ad-b593-15a57688b360)

### Issue Description✍️

Footer Is not well designed

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
