### ISSUE TITLE
💡 [FEATURE] - Improve UI of about us page

### ISSUE THREAD

**Issue by paridhi1509** [jfmartinz/ResourceHub#943]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The UI of the about us page is not that eye catching or visually appealing.

### Explain your solution

I would like to work on making it more attractive to the user by  changing the overall layout and adding some colors and make changes in the font style too.

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
