### ISSUE TITLE
🐞 [BUG] - < button is not proper text going out of the box>

### ISSUE THREAD

**Issue by kartikmehta18** [jfmartinz/ResourceHub#946]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/125860170/904dcb19-2d44-4ed2-b131-8b82f7fa4f70)
 button is not proper text going out of the box

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
