### ISSUE TITLE
🐞 [BUG] - Very less padding between the footer elements

### ISSUE THREAD

**Issue by arpy8** [jfmartinz/ResourceHub#948]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

There's very less padding between the last line and the rest of the urls.

Attaching screenshot for reference:
![image](https://github.com/jfmartinz/ResourceHub/assets/74809468/fcba2791-b937-4abb-a195-73a9ea66f974)

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
