### ISSUE TITLE
🐞 [BUG] - <title> Divs In Textnomals section are not properly aligned

### ISSUE THREAD

**Issue by SumithThota** [jfmartinz/ResourceHub#954]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

 Divs In Textnomals section are not properly aligned
![image](https://github.com/jfmartinz/ResourceHub/assets/108344062/2531bf04-b949-4693-9157-bf62fb9d96db)

### Expected behavior

 making those divs responsive is mandatory

### Additional Context

Please assign me this issue i want to work on it as a GSSOC'24 contributor

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now

**Comment by SumithThota** [comment]
> We're currently redesigning the website so ill close this issue for now

ok
