### ISSUE TITLE
🐞 [BUG] - Resources div card is not aligned well.

### ISSUE THREAD

**Issue by vilasini-v** [jfmartinz/ResourceHub#956]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

![image](https://github.com/jfmartinz/ResourceHub/assets/115165428/18769cdd-d635-4c59-be65-901700ab0fd8)

The text comes out of the div, i would like to work on this as a contributor to gssoc 2024!

### Expected behavior

the text is supposed to remain inside the div card, but is not aligned well.

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
