### ISSUE TITLE
Adding chatbox💡 [FEATURE] - <title>

### ISSUE THREAD

**Issue by sidhigrover** [jfmartinz/ResourceHub#960]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

<img width="1440" alt="Screenshot 2024-06-07 at 9 57 14 PM" src="https://github.com/jfmartinz/ResourceHub/assets/123989540/f358f23d-6dcf-451e-a1fb-e3afad508bda">

i will add similar chatbox on your website.
it will work on predefined questions/answers

### Explain your solution

Chatbox will enable visiter to provide instant responses to others inquiries, reducing wait times and enhancing visiter satisfaction.

### Additional Context
@jfmartinz 
_No response_

**Comment by jfmartinz** [comment]
We can do that. Once the design is finished, raised t he issue again. Ill close this for now

**Comment by sidhigrover** [comment]
> We can do that. Once the design is finished, raised t he issue again. Ill close this for now

Okay, please tag  me when  your website design finish
I will made for your website 😃
