### ISSUE TITLE
💡 [FEATURE] -  To fix home page footer 

### ISSUE THREAD

**Issue by dhairyagothi** [jfmartinz/ResourceHub#961]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Footer oh home page can be ediited in more good way 
![image](https://github.com/jfmartinz/ResourceHub/assets/142989448/dcb2f071-79ca-4d52-8ec1-65c38de12ff9)
i can do this please assign this to me

**Comment by jfmartinz** [comment]
We're currently redesigning the website so ill close this issue for now
