### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by paulkrishanu4** [jfmartinz/ResourceHub#967]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

want to design the contact us page UI  like this

### Explain your solution

![Screenshot_8-6-2024_164856_blog hubspot com](https://github.com/jfmartinz/ResourceHub/assets/169196836/416c9d52-3dd6-48f8-8189-000462df680b)

**Comment by jfmartinz** [comment]
We're currently redesigning the website so you can raise issue about the website after the website is done, ill close it for now
