### ISSUE TITLE
🐞 [BUG] - Fixing the UI of Search Bar and About Page

### ISSUE THREAD

**Issue by shubhammjha22** [jfmartinz/ResourceHub#973]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The UI of the Search Bar isn't good and also in the About Page 

-Search Bar 
![image](https://github.com/jfmartinz/ResourceHub/assets/68507333/99d43669-5830-4783-af4e-2e0fdd2a58f6)

-About Page
![image](https://github.com/jfmartinz/ResourceHub/assets/68507333/1e5fbc93-6f7b-43fb-ab60-f27209d04f00)

### Expected behavior

I want to change the UI of the SearchBar and About Page like this- 

-Search bar 
![image](https://github.com/jfmartinz/ResourceHub/assets/68507333/05f62481-77d6-4a38-9ffd-b33f9d739665)

-About Page
![image](https://github.com/jfmartinz/ResourceHub/assets/68507333/c8d1f808-3305-476d-80c1-dea42f91f942)

### Steps to reproduce

- Go to the Home Page and Scroll down a bit 
- You could see the UI (padding) of the Search Bar is off

-Go to the About Page 
-UI of this Page isnt appealing

**Comment by shubhammjha22** [comment]
@jfmartinz  Can you please assign this issue to me , I would like to work on this

**Comment by jfmartinz** [comment]
We're currently redesigning the website so you can raise issue about the website after the website is done, ill close it for now
