### ISSUE TITLE
💡 [FEATURE] - Add Contact Page.

### ISSUE THREAD

**Issue by zalabhavy** [jfmartinz/ResourceHub#979]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to make contact page.

### Explain your solution

I will give Contact page's path to navbar's contact option.
When anyone click on that then contact page open.

**Comment by jfmartinz** [comment]
We're currently redesigning the website so you can raise issue about the website after the website is done, ill close it for now
