### ISSUE TITLE
💡 [FEATURE] - Improve SEO (Search Engine Optmization ) for the home page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [jfmartinz/ResourceHub#982]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

**Comment by jfmartinz** [comment]
We're currently redesigning the website so you can raise issue about the website after the website is done, ill close it for now

**Comment by Ayushmaanagarwal1211** [comment]
Sure
