### ISSUE TITLE
navbar is not responsive in mobile device

### ISSUE THREAD

**Issue by Prnasin** [jfmartinz/ResourceHub#988]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

it takes extra margin in right of screen 

![Screenshot 2024-06-09 090657](https://github.com/jfmartinz/ResourceHub/assets/125786433/c19dcd53-d257-4ce6-8e03-688383d689f0)

### Expected behavior

it has to fit in whole screen instead of taking  extra  margin 

### Steps to reproduce

just open in mobile device

**Comment by jfmartinz** [comment]
Currently redesigning the website. read #998
