### ISSUE TITLE
💡 [FEATURE] - Adding the dynamic background.

### ISSUE THREAD

**Issue by happyrao78** [jfmartinz/ResourceHub#993]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to add the dynamic background to the website using my react concepts which will enhance the user interaction.

### Explain your solution

I would use the react framer motion and create a component named as fireflies background and then import it to the main home page.

### Additional Context

Here is the demo of what I am talking about which I have used in my  own portfolio:

https://github.com/jfmartinz/ResourceHub/assets/138770813/3253836c-04e2-4e52-9dc2-bb803407d42b

**Comment by jfmartinz** [comment]
Currently redesigning the website. read https://github.com/jfmartinz/ResourceHub/issues/998
