### ISSUE TITLE
💡 [FEATURE] - Adding the Animated Cursor.

### ISSUE THREAD

**Issue by happyrao78** [jfmartinz/ResourceHub#994]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to add the animated cursor to the website for smooth scroll effect.

### Explain your solution

I will use the react animated cursor library to implement this feature.

### Additional Context

Here is the video demonstrating my feature :

https://github.com/jfmartinz/ResourceHub/assets/138770813/d8890c2f-29b2-4342-b31c-baf111c2291d

**Comment by jfmartinz** [comment]
Currently redesigning the website. read https://github.com/jfmartinz/ResourceHub/issues/998
